### ISSUE TITLE
Support specifying minimum skill level for servants

### ISSUE THREAD

**Issue by MathewSachin** [MathewSachin/Fate-Grand-Automata#102]
e.g. This is useful for SkaSka systems (DSS).
Skadi's battery needs to be 10 for most setups, and other skills also need to be at high levels.
We should at least get this done before she arrives on NA.

I've got an idea for this.
Now that we have masked image matching implemented, if we can somehow get the 10 images of skill numbers with transparency, we should be able to detect skill levels without depending on OCR which can get pretty unreliable.

**Comment by reconman** [comment]
Even if we get this pseudo-OCR to work, what level of freedom do we allow? Should the support be only 10/10/10 or do we restrict it only to 1 or 2 skills? For example, the 2nd Merlin skill isn't important for farming.

**Comment by MathewSachin** [comment]
We can give 3 fields for minimum levels which will be 1/1/1 by default, simple.
But, like either all CEs are Prefer MLB or not at a time. The selected skill levels will apply to all preferred servants.

**Comment by reconman** [comment]
Where are you planning to get the numbers from? Photoshopping in that small scale is really difficult.

**Comment by MathewSachin** [comment]
We got another problem now. Template matching of transparent images isn't working as expected. Story Skip button currently matches to almost anything 😢

**Comment by MathewSachin** [comment]
I've implemented the option to individually set for the 3 skills, whether you want them to be maxed or them.
Implemented specific level check other than Lv10 would be too much work and make the support selection slower.
And, skill level 10 is what matters mostly like in DSS. So, closing this issue now. Expect the feature to be available in next release.
