### ISSUE TITLE
[Feature request] Support for chinese server

### ISSUE THREAD

**Issue by caoli5288** [MathewSachin/Fate-Grand-Automata#109]
Currently only support for en and jp servers :-/

**Comment by MathewSachin** [comment]
We would need help from someone who plays Chinese and Taiwan servers to support them.

**Comment by MathewSachin** [comment]
You seem to have programming experience from your profile. We're currently migrating the code to Kotlin (#108) which is Android's default language now and easy to learn for JAVA developers.
If you're willing to help, we can start shooting Chinese server. Chinese server does some things differently from NA and JP. So, unless we have someone who plays on it, we can't really make sure the app works correctly for it.

**Comment by caoli5288** [comment]
@MathewSachin I think it's only cards pictures issues. Currently only the cards priority not works. It's shown "can not detect card type" in the popup messages and select cards in natural order.

**Comment by MathewSachin** [comment]
Yeah, I heard CN changed the design of the command cards. So, we need new images for them. Also, there are less number of images in CN folder. We need all the images that are there in En and Jp folders for Cn.

**Comment by caoli5288** [comment]
Here is a screenshot

![MuMu20200515111853](https://user-images.githubusercontent.com/3120587/82007877-e7ba4e80-969d-11ea-9a67-3ad8c6678a5f.png)

**Comment by MathewSachin** [comment]
I copped these images from your screenshot:

<img width="40" alt="art" src="https://user-images.githubusercontent.com/10654537/82013512-1fbe9300-9698-11ea-80dc-04d5a8cf8b51.png">&nbsp;&nbsp;&nbsp;&nbsp;<img width="30" alt="buster" src="https://user-images.githubusercontent.com/10654537/82013523-23521a00-9698-11ea-82bc-25e280c16a15.png">&nbsp;&nbsp;&nbsp;&nbsp;<img width="34" alt="quick" src="https://user-images.githubusercontent.com/10654537/82013538-2baa5500-9698-11ea-91ad-ded7ef815012.png">

But, we need more images to support CN, specifically:
(or we can temporarily put En/Jp images for some low-priority ones to prevent errors)
- lottery.png, StopGifts.png (will probably have to wait till next lottery on CN)
- **support_region_tool.png (Support Selection screen)**
- withdraw.png (Quest Failed screen where you're given the option to use Command Spells or retreat)
- master_exp.png (Master Exp/Mystic Code EXP gain screen)
- master_lvl_up.png (Master Exp/Mystic Code Level up screen)
- mat_rewards.png (Material Rewards screen which shows quest drops in a grid)
- retry.png (Connection to the server failed screen)

**Comment by caoli5288** [comment]
Here is some screenshots. 

![MuMu20200515133102](https://user-images.githubusercontent.com/3120587/82015049-7637cb80-96b0-11ea-8c72-04247c4b84a9.png)
![MuMu20200515133110](https://user-images.githubusercontent.com/3120587/82015052-78018f00-96b0-11ea-84e4-b69d940ebd13.png)
![MuMu20200515133115](https://user-images.githubusercontent.com/3120587/82015054-79cb5280-96b0-11ea-99e6-04f9927488a5.png)
![MuMu20200515133129](https://user-images.githubusercontent.com/3120587/82015060-7afc7f80-96b0-11ea-82a8-b4fce2c06d9e.png)
![MuMu20200515133141](https://user-images.githubusercontent.com/3120587/82015063-7cc64300-96b0-11ea-880f-6cf6f28f2724.png)

**Comment by caoli5288** [comment]
![MuMu20200515133459](https://user-images.githubusercontent.com/3120587/82015240-e21a3400-96b0-11ea-8682-227160217fbc.png)

**Comment by MathewSachin** [comment]
Thank you for the images, I've cropped the required part from them.
I need to make at least 2 more images: `retry.png` and `withdraw.png`
I've edited my previous comment.

**Comment by caoli5288** [comment]
The game get frozen if I turn off network so I can't got retry screenshot.

![MuMu20200515150441](https://user-images.githubusercontent.com/3120587/82021454-6b376800-96bd-11ea-8841-7883d6035586.png)

**Comment by MathewSachin** [comment]
Can you translate what is written on these buttons for me? I want to make sure which is the Withdraw one because I can't read Chinese 😅 .
Thanks to this, I found that I've made a mistake when translating the Withdraw code from FGO-Lua. I'll do a fix for that too.

**Comment by caoli5288** [comment]
@MathewSachin I'm not quite sure how the game words will be translated correctly. Maybe their position hasn't been changed?

**Comment by reconman** [comment]
@caoli5288 I think you misunderstood. We just want to know what the buttons say from left to right. We know that one is `Use Command Seal`, one is `Use Saint Quartz` and one is `Withdraw`, but which one is which?

**Comment by caoli5288** [comment]
@reconman Maybe the `Holy Crystal` is equals to `Saint Quartz` :-)

**Comment by MathewSachin** [comment]
Cool! So, `withdraw.png` is done too. Now, the only one really needed is `retry.png`.

**Comment by caoli5288** [comment]
Ok I got it. Left is "Quit" and right is "Retry".

![MuMu20200516021027](https://user-images.githubusercontent.com/3120587/82082355-77054780-971a-11ea-833b-e73a877a7e4a.png)

**Comment by MathewSachin** [comment]
@caoli5288 Can you try the `apk` on this page: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/105966006

It will be in a zipped folder. Set the `Game Region` in `More options` to `Chinese`.

**Comment by MathewSachin** [comment]
That's due to the app targetting Android 10 now. There has been a change in permissions. We'll add the permissions and get you a new build to test soon.

**Comment by MathewSachin** [comment]
This build should work: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/106049000

**Comment by caoli5288** [comment]
I'll test it 10 hours after. Now I'm going to sleep. :-)

**Comment by caoli5288** [comment]
@MathewSachin Hi. Same issues :-/

**Comment by MathewSachin** [comment]
Is the installed app's version code `264`?
You can check that from your phones My App or related screen.

**Comment by caoli5288** [comment]
Yes it's 162

**Comment by MathewSachin** [comment]
Can you tell me your phone's model and Android version?

**Comment by MathewSachin** [comment]
I think it was a miss from my side, can you please try this build: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/106587878

**Comment by caoli5288** [comment]
Hi. It's still cannot detect card types.

Here is some pics I tested in lua version. :-)

[image_CN.zip](https://github.com/MathewSachin/Fate-Grand-Automata/files/4639129/image_CN.zip)

**Comment by reconman** [comment]
@caoli5288 And you set the game server to China?

Also what's your device?

**Comment by caoli5288** [comment]
It's my mistakes. I forget to switch to cn server 👎

**Comment by reconman** [comment]
@caoli5288 happens to us too all the time

**Comment by MathewSachin** [comment]
@caoli5288 when doing Free quests, doesn't the app stop after battle on repeat quest screen. Yesterday that screen got added to NA too and I noticed we don't have the CN image for it.
Can you get me a screenshot of that screen on CN?
