### ISSUE TITLE
Support for Ankulua daemon?

### ISSUE THREAD

**Issue by buitim** [MathewSachin/Fate-Grand-Automata#112]
I am not sure how much is shared with fgo lua, but is there any way to use Ankulua's daemon? I think this could get past the media projection issue that emulators are facing.

Also, thank you for this project! I was looking for something like this for the longest time!

**Comment by reconman** [comment]
You have to activate root mode in the "More settings" window and in Nox. That's the only way it works right now.

Ankulua is closed source, we have no idea what is going on in the daemon and therefore cannot do it the same way.

**Comment by MathewSachin** [comment]
Also, FGO JP works with root right now. FGO NA will be getting the engine update in a month after which it can run on Nox with root too.

**Comment by buitim** [comment]
Makes sense, thanks! Just thought it was worth asking. Using Bluestacks atm

> Also, FGO JP works with root right now. FGO NA will be getting the engine update in a month after which it can run on Nox with root too.

I'm very excited for this as I primarily use a jailbroken iPhone lol.

Thanks again y'all for this project!

**Comment by reconman** [comment]
Bluestacks root mode (if you patch bluestacks using 3rd party software) is detected by FGO JP, so you'd have to switch to Nox.

**Comment by buitim** [comment]
> Bluestacks root mode (if you patch bluestacks using 3rd party software) is detected by FGO JP, so you'd have to switch to Nox.

Oh I actually figured out a way around that. You can actually just patch it and not update the SU binary. Bluestacks has the nice translation feature that I just can't give up quite yet haha
