### ISSUE TITLE
Unable to autopick servant

### ISSUE THREAD

**Issue by mcshi** [MathewSachin/Fate-Grand-Automata#113]
**Describe the bug**
A big error message pops up when the script tries to auto select a servant and makes the script stop. This extends across all of my scripts. The script can be restarted once in battle and runs fine then. 

**Screenshots**
![Screenshot_20200518-221633_Fate_GO](https://user-images.githubusercontent.com/64087561/82277669-7ce76c80-9956-11ea-892f-55d418ff7167.jpg)

**Device Info (please fill atleast 'Device model'):**
 - Device model: Samsung s8
 - Screen size: WQHD+
 - Android Version: Android 9
 - RAM: 4gb

**Comment by MathewSachin** [comment]
Can you post screenshots of your `Support` settings and `AutoSkill` settings?
I'm not sure about the error, but, are you using `Support Selection Mode` = `Friend`?

**Comment by mcshi** [comment]
Screenshots attached.

I am using support selection mod = friend only, yes. 

![Screenshot_20200519-120955_FateGrand Automata](https://user-images.githubusercontent.com/64087561/82350845-d937a400-99c9-11ea-92be-51db04051d41.jpg)
![Screenshot_20200519-121011_FateGrand Automata](https://user-images.githubusercontent.com/64087561/82350846-d9d03a80-99c9-11ea-8ee4-2e3141c8e393.jpg)

**Comment by reconman** [comment]
@mcshi You left out a part of the support selection screen at the top. Can you provide that info too?

**Comment by mcshi** [comment]
![Screenshot_20200519-125543_FateGrand Automata](https://user-images.githubusercontent.com/64087561/82355380-20c12e80-99d0-11ea-9cf6-bb5f96c24ff7.jpg)

**Comment by MathewSachin** [comment]
One more thing, can you try after clicking again on `Extract Default Support Images` option? Just in case the support images were deleted or renamed.

If it still doesn't work, have you installed the app on an external-SD card by any chance? I haven't tested the case of app being on an external SD-card.

**Comment by mcshi** [comment]
I tried after extracting, still no luck. I don't have an SD card in my phone to begin with, so there's no chance it's on the SD card.

**Comment by MathewSachin** [comment]
Also, a screenshot of the `More options` screen please.

**Comment by mcshi** [comment]
![Screenshot_20200519-131123_FateGrand Automata](https://user-images.githubusercontent.com/64087561/82356917-4818fb00-99d2-11ea-9698-541236752f55.jpg)
![Uploading Screenshot_20200519-131120_FateGrand Automata.jpg…]()

**Comment by MathewSachin** [comment]
One of the images didn't finish uploading but I can't find a problem in the settings, so it's not a problem.
BTW, I was looking at past issues and you had opened one. Did support selection use to work fine at that time? If so, can you remember the version that started giving this error?

**Comment by mcshi** [comment]
The support selection worked fine through the past apocrypha event. After that, I didn't use the app at all during the Guda Guda 2 event, and when I tried to use it for farming after finishing with the event, the support selection doesn't work. I tried downloading the latest version to see if that was the issue (I had already updated to it, but just in case), and that didn't fix anything.

**Comment by mcshi** [comment]
I figured out what was going on: I had hidden the ce and servant folders in order to have them not show up in my pictures folders, I guess that broke the app somehow.

Thanks for troubleshooting!

**Comment by reconman** [comment]
@mcshi Put a .nomedia file into the folder, then it won't show up. This file is automatically added in newer versions of the app.
