### ISSUE TITLE
Have notification bar list which Autoskill config is Running

### ISSUE THREAD

**Issue by Mysty-chan** [MathewSachin/Fate-Grand-Automata#114]
I build a new configuration, and then often forget to select it for use, or didn't remember which free quest I was last using and therefore which config is active . So if after pressing play, the notification display could change from "script running" to "[config 1] running" would be nice.

**Comment by MathewSachin** [comment]
Yeah, that would be a sweet improvement.

BTW, the FGO-Lua script displays a dialog box which shows a list of AutoSkill configs with the last one you selected when you start the script. You can choose the one you want to run from it.

This would be even better if I'm able to implement it without asking any more permissions from the user. You won't accidentally run the wrong config and then have to stop the script, go to settings, change the selected script, start again.

**Comment by Mysty-chan** [comment]
A pop up that lets you pick would be really nice, but I figured just letting it be stated in the notification bar would be easier to implement

**Comment by MathewSachin** [comment]
I was thinking of a way to show dialogs to users from quite some time.
Finally, had success making a dialog to show for picking AutoSkill config when starting script.

https://www.youtube.com/watch?v=LJuGiT6pvxI
