### ISSUE TITLE
Script won't play, immediately throws error "after Resolution Change"

### ISSUE THREAD

**Issue by arkteck** [MathewSachin/Fate-Grand-Automata#121]
> MAKE SURE YOU TESTED THE LATEST RELEASE.

Using v0.12.0

> See 'SAMSUNG.md' first, if you're a Samsung user.

Done, app had been running fine previously.

**Describe the bug**
Script immediately stops after pressing play button (on support selection screen or battle screen) and throws up a bunch of code.

**Screenshots**
![Screenshot_20200526-212133_Nova Launcher](https://user-images.githubusercontent.com/64213090/82966076-f525e180-9f97-11ea-95c0-bd8f226c47da.png)
![Screenshot_20200526-212112_Fate_GO](https://user-images.githubusercontent.com/64213090/82966077-f5be7800-9f97-11ea-913c-2363275d6a1c.jpg)

**Device Info (please fill atleast 'Device model'):**
 - Device model: Samsung Galaxy S9
 - Screen size: 2960x1440
 - Android Version: Android 10
 - RAM: 4GB

**Comment by MathewSachin** [comment]
Since the app was running fine previously, did you change your screen resolution?
If so, then try going to Accessibility Settings on your phone, turn OFF the app's entry and then turn it ON again. See if the app works after that.

**Comment by arkteck** [comment]
Magical! Yep, that was it. I forgot I had done that.
Thank you so much!

**Comment by MathewSachin** [comment]
I'll keep this issue open. I think that resolution changes should be handled by the app.
It should be such that `Toggle Service` should be sufficient instead of having to turn OFF accessibility service and then ON again.
