### ISSUE TITLE
Crit Star Gain skills block other skills from activating

### ISSUE THREAD

**Issue by reconman** [MathewSachin/Fate-Grand-Automata#122]
I have a SkillCommand with Gilgamesh 3rd skill and then Ishtar 3rd skill. If I put them in this order, Ishtar's 3rd skill is not activated. If I reverse the order, both skills are activated.

While FGO distributes the newly gained stars, it blocks all skill activations.

Actually, the stars gaining animation even blocks NP activations, the script tries to press the attack button, fails and then doesn't find the NP card.

**Comment by MathewSachin** [comment]
Can you make a video of this?
I'm using Hero creation after my Gilgamesh's third skill while heavily farming for bones right now and I haven't seen it miss.
Might be fixable just by tweaking the wait time.

**Comment by reconman** [comment]
https://streamable.com/mu0s24

SkillCommand is `cdg4,#,if5,#,t2hk36`

**Comment by jdomann** [comment]
I've got the same issue, had it in 0.12.0 as well and wondered if I was the only one.  Here's a video of my issue as well: https://streamable.com/plucd3

Tried turning on/off skill confirmation, no change.  My config for these 2 rounds: `4,#,ac4,#,`

**Comment by tchofy** [comment]
Based on a few tests I did, it doesn't look like the NA client blocks skill activation during star distribution in the new engine. Could use a few tests on low end devices though, just to make sure.

**Comment by MathewSachin** [comment]
My phone is like the epitome of low-end devices and I haven't had problems with this yet.

**Comment by reconman** [comment]
I think we can reproduce this negative behavior by using Mozart's Eine Kleine Nachtmusik skill to gain 50 stars. That will keep FGO busy for a second.

**Comment by MathewSachin** [comment]
I think this doesn't happen now.
Even when using DSS with 50-80 stars generated, the first skill in the next turn never missed for me.

**Comment by tchofy** [comment]
I'd say it's safe to close this issue, as it seems the new engine no longer blocks skills while the game is distributing stars. Even trying to trigger this issue manually, like trying to click a skill while it's icon is still fading in, and nothing, so I doubt this app would have any trouble.
