### ISSUE TITLE
[JP] The First Support is always ignored

### ISSUE THREAD

**Issue by AlfredPaguio** [MathewSachin/Fate-Grand-Automata#124]
> MAKE SURE YOU TESTED THE LATEST RELEASE.
Already tested
> See 'SAMSUNG.md' first, if you're a Samsung user.
 I'm not a samsung user

**Describe the bug**
The script/bot/app ignores the first support everytime

**Screenshots**
https://streamable.com/5zl3q0

**Device Info:**
 - Device model: Xiaomi Redmi note 7
 - Screen size: 1080 x 2340
 - Android Version: Android 9
 - RAM: 3GB

**Comment by reconman** [comment]
Can you do another video with debug mode? It reveals more of what's happening.

**Comment by AlfredPaguio** [comment]
Here : https://streamable.com/g6mbbt

**Comment by reconman** [comment]
Even in debug mode it should scroll and select Skadi. Can you try again? There must be a temporary glitch.

**Comment by AlfredPaguio** [comment]
I even go to set the selection mode to first but it's still ignoring the first one and it's still treat the second one the first one as seen in the video

**Comment by reconman** [comment]
Selection mode first is ignored when Autoskill is enabled. I would really appreciate another video with debug mode and working scrolling and selection.

**Comment by tchofy** [comment]
After reading this I noticed I had the same issue on NA. No big deal, but here's the video with debug on.

https://streamable.com/d2rbr0

I got a bit curious and decided to test it with the MLB option disabled, and it picked the first option consistently.
https://streamable.com/018hk4

**Comment by reconman** [comment]
Seems like an issue with detecting MLB. We are currently waiting for a bugfix in the image detection library to be able to use transparent images, which is useful for Story Skip and MLB stars.

**Comment by AlfredPaguio** [comment]
Ahm mine is still skipped when I turn off mlb option

**Comment by MathewSachin** [comment]
I did some analysis on this with the logs I added (#162).
It turns out we're getting only around `0.72` similarity for the MLB star in some cases, whereas the minimum similarity to match it is set to `0.77`.
This should be fixable by setting the similarity for matching MLB star to `0.7`. ~~Or, maybe we can crop images for MLB star again.~~

I'm also making this configurable by the user in #171.
