### ISSUE TITLE
Wrong friend support picked if update list takes too long due to bad internet.

### ISSUE THREAD

**Issue by Wishmater** [MathewSachin/Fate-Grand-Automata#129]
When the update list takes too long loading, or gives connection error, the script will try to update list again instead of retrying. This is ok if the error is shown, but since the update list action is time based (i think); if the script tries to update the list just before the previously called update finishes, it will end up touching a random support servant when it tries to hit the 'ok' button. This happens more than you'd think on my shitty internet.

This is a great project and I hope I was able to help you improve it a little.

**Comment by MathewSachin** [comment]
We already know about this problem.
But, there's no sure shot way to find if support list has been loaded.

The script works by matching images on the screen (time-based waiting in other cases). So, we need to wait for some specific image to appear on the screen. But, the support list design is different based on whether the servant is a story support or friend support. There's also the problem with events where you can set filters and it can happen that no servants match the filter at all. The script would be stuck infinitely with this approach.

Another approach can be matching the Fou running animation for `Loading...` or `Connecting...`.
But, I'm not really sure if that would work.

**Comment by Wishmater** [comment]
Thanks for the quick reply! I think at least for this case checking for the Fou running would fix it...
Thanks and keep up the good work!
