### ISSUE TITLE
Too much scrolling in support selection, resulting in missed supports

### ISSUE THREAD

**Issue by kelpie2** [MathewSachin/Fate-Grand-Automata#136]
> MAKE SURE YOU TESTED THE LATEST RELEASE.

> See 'SAMSUNG.md' first, if you're a Samsung user.

**Describe the bug**
The support selection seems to scroll too much, and often misses the right support.

**Screenshots**
https://streamable.com/fj0h5i

Here I've set Waver and Chaldea Lunchtime as my preferred support/CE, but you can see that it scrolls too much each time and misses it.

**Device Info (please fill atleast 'Device model'):**
 - Device model: [Samsung A70 (SM-A705MN)]
 - Screen size: [1718x1080 (I tweaked it when I used FGOlua)]
 - Android Version: [Android 10]
 - RAM: [not sure]

Great work by the way! I'm am a FGOlua user but I've been trying to port everything over since the UI is so much nicer.

**Comment by MathewSachin** [comment]
From the video, the amount it scrolls seems fine. Waver+Lunchtime is fully on-screen after some scrolls but that Waver isn't matching.
It should be a timing issue, so the script should wait more between scrolls.
I'm holding on adjusting timings before the engine update arrives to NA. After that, the game would run much faster.
I'll probably add some sliders to the app so everyone can customize the wait times to their needs.

**Comment by kelpie2** [comment]
In [this](https://streamable.com/5zl3q0) I found in another thread here, the scroll amount seems to be about one servant at a time, which I assume is the intended behavior. In my video it seems that it scrolls about 1.5 servants at a time. Do you know why this is different? Would a slider for the scroll amount be possible to add?

**Comment by reconman** [comment]
The sliding depends on the device it's running on, there's no reliable way to scroll the same amount on every device.

**Comment by kelpie2** [comment]
If that's the case it seems an option to adjust the scroll amount would be useful. Would that be hard to implement?

**Comment by MathewSachin** [comment]
Not too hard to implement, but I'll be a bit busy for around a month.
So, don't expect much from me for that time.
I should be able to do this before the lottery where this app will really matter.
