### ISSUE TITLE
Question : Deleting/editing preferred Servant and CE list

### ISSUE THREAD

**Issue by azh97** [MathewSachin/Fate-Grand-Automata#138]
Hello there, first of all, thanks for creating this wonderful app. Really useful and quite easy to use.

Like the topic, is there any option like I mentioned? I accidently saved two same CE pics so kinda wondering if there is an option to edit or delete the selection? Tried looking and searching within the app but couldn't find one.

Also kinda wondering if I could access the saved photos and folder of the CE and servants so that I could manage it systematically better. Thanks in advance.

**Comment by tchofy** [comment]
Don't think there's such a function on this app yet, but you can do it with a file explorer app, and going to Internal Memory > Fate-Grand-Automata > support

Now you can either go into the ce folder, to delete CE images, or the servant folder, to delete servants. Another option is renaming the images if you want, to do some organizing. Just remember you can't edit the folder name/location themselves or the app won't be able to locate and use them.

**Comment by azh97** [comment]
Appreciate the fast reply there. So I tried what u had suggested, and it works perfectly. Thank you.

Just remember to unpick/unselect the ce or servant before u delete or u might create a crash loop to the app (when trying to edit autoskills). Luckily copying back the deleted image (name must be the same) to the directory, then unselect the ce i want to delete before deleting resolve the issue.

**Comment by MathewSachin** [comment]
> Just remember to unpick/unselect the ce or servant before u delete or u might create a crash loop to the app (when trying to edit autoskills). Luckily copying back the deleted image (name must be the same) to the directory, then unselect the ce i want to delete before deleting resolve the issue.

v0.13.0 will indeed crash if you delete selected CE. I already have a fix in place which would prevent the crash and instead show a message box reminding you that the image doesn't exist when the script gets to support selection screen. Expect this in the next release.
