### ISSUE TITLE
PSA: With NA update, may need to turn off ignore notch calculation for Samsung devices

### ISSUE THREAD

**Issue by Enfinit** [MathewSachin/Fate-Grand-Automata#143]
This may be a case by case basis but at least for the Note 10+, I had to turn off the ignore notch calculation toggle in order for it to function properly again. Still needs to be forced into full screen though.

**Comment by MathewSachin** [comment]
@Enfinit can you post a screenshot of FGO running on your Samsung phone. I just need to confirm that FGO is completely centered on screen.

**Comment by Enfinit** [comment]
Here you go. 
![pa3yj2ag](https://user-images.githubusercontent.com/22234216/85596866-153cd500-b618-11ea-9809-80835ee4bf6f.jpeg)

**Comment by MathewSachin** [comment]
Great! So it's now the same as on other phones. So, the option won't be needed then. I'll add a note about it to the next release and the SAMSUNG docs. Still, I think we should confirm if this is consistent with all Samsung models.
**If any other SAMSUNG users with notch are reading this, do post a screenshot of FGO running on your phone here.**

**Comment by KingKanji** [comment]
I have an S9, have notch turned off, but always get the message "Failed to determine card type Region." Did I mess with the settings too much or something?
![image](https://user-images.githubusercontent.com/67945147/86730516-9c1c8500-bffc-11ea-91cb-223c1ff378ae.png)

**Comment by MathewSachin** [comment]
Hmm, from the screenshot, it seems you'll still have to keep `Ignore Notch calculation` ON.

I don't really know why this varies between different Samsung models.

**Comment by KingKanji** [comment]
Turned it on, restarted, and it says the same thing.

**Comment by KingKanji** [comment]
Restarted AGAIN, and it worked. Weird.

**Comment by MathewSachin** [comment]
I'm closing this issue to reduce clutter.
I'll still keep it pinned at top of issues as a PSA.
