### ISSUE TITLE
Select the team at the start of the farm

### ISSUE THREAD

**Issue by Leonard-GEHIN** [MathewSachin/Fate-Grand-Automata#145]
First, I want to thank you so much for your work on this project. It really made me appreciate the game a lot more.
Now for the request: I often switch teams to perform other quests (mainly story). So when I go back to the farming and launch fate grand automata, It happen quite often that the team used is not the correct one. Therefor a piece of code that check / switch the team used at the start of a battle would be cool. I know that I can resolv this issue just by thinking about it. But I think this feature would be a good quality of life addition to the project.

**Comment by MathewSachin** [comment]
#35 was support class, this issue is for the party

**Comment by reconman** [comment]
Sorry, you're right.
