### ISSUE TITLE
Preferred Friend's name can't be typed in

### ISSUE THREAD

**Issue by Boost0** [MathewSachin/Fate-Grand-Automata#154]
Open the app>Support(manage support selections)>In the 'Friend' section>Friend names
A blank box with only 'cancel' and 'ok' buttons are present, the box to input names is missing

 - Device model: Pocophone F1
 - Screen size: 1080 x 2246
 - Android Version: Android 10
 - RAM: 6GB
![Screenshot_2020-07-08-08-33-21-610_com](https://user-images.githubusercontent.com/67996224/86883901-5c9d8800-c125-11ea-938a-9731d17971db.png)

**Comment by MathewSachin** [comment]
`Friend names` is misleading. I just keep the same name from FGO lua.
But, those are actually images of your friend's names.
You can make those images using Support Image Maker and pick them from the list like you do for Servant and CE.

**Comment by Boost0** [comment]
I see. I was used to the previous build where you could type in a username...though I think it worked only half the time. thanks for the feedback, I'll give it another go and see if it works!

**Comment by Boost0** [comment]
Alright, it works. Thanks for the feedback!
