### ISSUE TITLE
Support Selection

### ISSUE THREAD

**Issue by Bronzeraptor** [MathewSachin/Fate-Grand-Automata#163]
No matter what setting i use, nothing happens on the support selection screen. everything else seems to work fine

**Comment by reconman** [comment]
Can you activate debug mode and the screen recording mode in More options and upload the video in /storage/emulated/0/Fate-Grand-Automata/record.mp4 to a site like imgur.com?

**Comment by Bronzeraptor** [comment]
I actually got it working. im on samsung and didnt have the app in fullscreen. its working great
