### ISSUE TITLE
Repeat Quest will not wait long enough for the support list to load

### ISSUE THREAD

**Issue by reconman** [MathewSachin/Fate-Grand-Automata#164]
In 70 % of the cases, the app will update the support list after clicking on the Continue button for repeating the quest. Seems like we need to increase the wait time between selecting `Continue` and checking the support list.

**Comment by MathewSachin** [comment]
I've been farming Dust for a few days at Charlotte, never had an issue of app unnecessarily updating the support list yet.
Maybe because support list loads almost instantly after clicking Continue for me.
