### ISSUE TITLE
Cloud support

### ISSUE THREAD

**Issue by Alpayyil** [MathewSachin/Fate-Grand-Automata#165]
Would be nice to be able to save the skill configs somewhere so we can use them on other devices. Maybe an export/import is enough.

**Comment by MathewSachin** [comment]
AutoSkill configurations are dependent on the Servant/CE images used. So, there's no point in moving them around without the images. So, we'll have to zip the configurations along with the images.

Considering the upcoming Android 11 will have heavy restrictions on storage access, we should use a MediaStore or Sharing API for this, so migrating from the current folder structure is easy.

To do this properly will be a LOT of effort. Don't expect anytime soon.

**Comment by MathewSachin** [comment]
See #196. I've added an option to export individual AutoSkill configs and an option to Import multiple AutoSkill configs.
I'm not doing the packing images together thing because it is too much work.
The images can just be copied to the other device so it is not a problem I think.
