### ISSUE TITLE
Card Priority per AutoSkill configuration

### ISSUE THREAD

**Issue by Miepmeister** [MathewSachin/Fate-Grand-Automata#166]
idea is that as na now has skadi and quick is now a big thing, wouldn't it make more sense to put the card priorities from more options into the auto skill configs? this way you can set the card priorities for each auto skill set instead of doing it in general which makes up for further configuration possibilities, I don't know if that's possible tho as of now

**Comment by MathewSachin** [comment]
We already have it planned.
We also have other things to move to AutoSkill configs so the UI might get a bit cluttered, so we're thinking about a redesign.

**Comment by Miepmeister** [comment]
that's nice, I happened to come across that idea bc of the lucky fact that I got skadi myself so there's that
