### ISSUE TITLE
facecards in autoskill config

### ISSUE THREAD

**Issue by Miepmeister** [MathewSachin/Fate-Grand-Automata#167]
would be cool if it was possible to add facecards to autoskill configs, in the way of something like this:

abc%%4,#,ef%5,#, x11d1h6

basically, %(just for the example) puts facecards in so that after skills are done, in the example above, (first battle) facecard facecard np will be done, there wouldn't be any specifics for selection of facecard needed as the card priorities setting takes care of that

**Comment by MathewSachin** [comment]
Already there:
- n1: one facecard before NP
- n2: 2 facecards before NP

Also supported in the AutoSkill Maker.

**Comment by Miepmeister** [comment]
I should read what's new more often lol, my bad

**Comment by MathewSachin** [comment]
Well, FGO lua got this feature before I started making this app.
So, we had this feature from the beginning 😆
