### ISSUE TITLE
The app stopped working correctly

### ISSUE THREAD

**Issue by Aftesmo** [MathewSachin/Fate-Grand-Automata#168]
The app worked perfectly before and then it stopped clicking. I turned debug mode on and I can see the app is reading my game but is unable to click anything. Tried reinstalling, reactivating service, nothing helps.
Edit: fixed by restarting my phone

**Comment by MathewSachin** [comment]
Dude, we don't have supernatural powers 😆 . The issue template is there for a reason.
Tell us what your phone model, maybe post some screenshots or a video in debug mode.
Then we'll be able to help.

I can't really tell anything from what you've posted. Please provide some info.

**Comment by MathewSachin** [comment]
@Aftesmo was your problem solved?
We're not against helping you. Just need enough info to help out.

**Comment by MathewSachin** [comment]
Never mind. Saw the edit
