### ISSUE TITLE
not selecting servant

### ISSUE THREAD

**Issue by akun90** [MathewSachin/Fate-Grand-Automata#169]
Hello i wantedto test this appon doors node i play on  android 10.
I set up everything and prepared autoskill script.
Then i started the app and it select the node i wanted (40ap door) after that it sit on support screen whitout doing anything at all.
Please note that in some cases when i too deep o  level selction screen the app would tap on "i" instead of the node.

Here are the screen form my app, what am i doing wrong?
<img height="500px" src="https://user-images.githubusercontent.com/68243506/87334425-e9d64780-c53e-11ea-8941-f102d58e1f34.jpg" />
<img height="500px" src="https://user-images.githubusercontent.com/68243506/87334428-eb077480-c53e-11ea-9d90-afdbe253039a.jpg" />
<img height="500px" src="https://user-images.githubusercontent.com/68243506/87334431-eb077480-c53e-11ea-8391-c05ac9c76271.jpg" />

Another issue is "img maker not working on select support screen"

**Comment by reconman** [comment]
Please fill out the bug template:

**Describe the bug**
A clear and concise description of what the bug is.
Include steps to reproduce the error if required

**Screenshots**
If applicable, add screenshots to help explain your problem.
If an error occurred, you can find the message by expanding the app's notification.
It is recommended that you atleast add one screenshot of FGO running on your device.

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON (recording functionality is available within the app in `More options`).

**Device Info (please fill atleast 'Device model'):**
 - Device model: [e.g. Xiaomi Redmi 4]
 - Screen size: [e.g. 1280x720]
 - Android Version: [e.g. Android 7.1]
 - RAM: [e.g. 3GB]

**Comment by MathewSachin** [comment]
What is your phone model?
Please don't ignore the issue template. The questions asked in it matter to us for solving your problems.

**Comment by akun90** [comment]
Samsung galaxy s10

**Comment by MathewSachin** [comment]
https://mathewsachin.github.io/Fate-Grand-Automata/SAMSUNG.html

**Comment by akun90** [comment]
I tried it with both ignore notch on and off before making the post.

**Comment by reconman** [comment]
And did you activate full screen mode for FGO?

**Comment by MathewSachin** [comment]
> Make sure you’re running F/GO with Full screen mode ON in Samsung’s settings. Blue-bars should be shown in the space which is not used by FGO. If you did this wrong, that area would be black.

Did you try this? Post a screenshot of FGO running on your phone.

**Comment by akun90** [comment]
Nope how do i do that?

**Comment by MathewSachin** [comment]
https://www.google.com/search?q=samsung+full+screen+mode&oq=samsung+full+&aqs=chrome.1.69i57j35i39j0l6.3903j0j9&sourceid=chrome&ie=UTF-8

**Comment by akun90** [comment]
Now the game has 2 blue bands o  the side isnit oklike that? It seems to work now

**Comment by reconman** [comment]
That's what you want, yes.

**Comment by MathewSachin** [comment]
Please fill the issue template and follow the instructions the next time you open an issue. Thanks.

**Comment by akun90** [comment]
ok thx for the fast answer btw with ignore nocht doesnt work you ha e to disable it now. Btw thx
One last question is there ban risk by using this?

**Comment by MathewSachin** [comment]
>  ignore nocht doesnt work you ha e to disable it now
Yeah, we have an issue stating this pinned and the website link I gave you also says so.

> is there ban risk by using this
Unless you tell DW yourself, you shouldn't get banned.

**Comment by akun90** [comment]
Ty very much for the infos man.

**Comment by akun90** [comment]
One more question what about the repeat screen? Will the app auto repeat or go to the quest selection screen?

**Comment by reconman** [comment]
It will repeat the quest

**Comment by akun90** [comment]
K ty very much

**Comment by akun90** [comment]
Thies the app have an autoupdate function if not how do j update it when new versions comes out?

**Comment by reconman** [comment]
See #135 and you can also click on Watch and then select `Releases only`. That way you'll get an email every time there's a release.
