### ISSUE TITLE
Set up Azure Pipeline for the master branch

### ISSUE THREAD

**Issue by reconman** [MathewSachin/Fate-Grand-Automata#17]
When anything is committed or merged to the branch, a pipeline should be triggered which builds the current APK from that master branch.

At a later date we could also automate releases, Azure supports publishing to Github.

I've spent quite some time today finding out how to get Azure Pipelines to work with the project. https://dev.azure.com/reconman/Fate-Grand-Automata/_build/results?buildId=2&view=artifacts&type=publishedArtifacts

I would suggest us chatting privately because it involves many steps. I have Discord and Skype accounts.

**Comment by MathewSachin** [comment]
Azure pipelines looks like the only CI option to work out of the box with Xamarin.
I was also thinking about trying out GitHub Actions, maybe later.

Discord: mathewsachin#9362

**Comment by reconman** [comment]
I've sent you a friend request
