### ISSUE TITLE
What's the difference between the support servant/CE inside the support tab vs the one inside the autoskill settings

### ISSUE THREAD

**Issue by duradara** [MathewSachin/Fate-Grand-Automata#176]
Sorry if my english is bad.
![Screenshot_20200715-183017](https://user-images.githubusercontent.com/50158352/87598631-9ba17f80-c6c9-11ea-8695-bc0d6fe6d970.png)
![Screenshot_20200715-183028](https://user-images.githubusercontent.com/50158352/87598642-9c3a1600-c6c9-11ea-8efe-17854732ba25.png)

**Comment by reconman** [comment]
The one in the Support settings is mostly for historical reasons.

Back when Autoskill Configurations didn't exist, you were only able to set 1 Servant and 1 CE.

Then with Autoskill configurations, you were able to overwrite the global settings.

The rules are as follows:
* If Autoskill Servant or CE is set, it will overwrite the one in the Support configuration (2nd screenshot)
* If Autoskill Servant or CE is not set (Any), the Support configuration one will be used.
* If you want to match any Servant with a specific CE, you will need to set the Servant to Any in both configurations.
* If you set all Servant and CE settings to Any, you will get an error message.

**Comment by duradara** [comment]
Thx
