### ISSUE TITLE
Can you add skip death animation??

### ISSUE THREAD

**Issue by earht2546** [MathewSachin/Fate-Grand-Automata#185]
If you could, I would really appreciate.

**Comment by MathewSachin** [comment]
No, we've tried before but there's no general way to skip death for every servant

**Comment by reconman** [comment]
Skip which death animation?

**Comment by MathewSachin** [comment]
> Skip which death animation?

I believe they are referring to servant death, most probably for Chen Gong's sacrifices and Arash.
