### ISSUE TITLE
Fine Tuning "Return to Default"

### ISSUE THREAD

**Issue by LeiCiel** [MathewSachin/Fate-Grand-Automata#187]
Considering the warning given in the change log with regards to using the 'Fine Tuning' features, I thought it would be nice if we had a "Return to Default" button in case someone tweaks it too much and wants to return to the original settings but can't remember them.

**Comment by tchofy** [comment]
True, that'd be very useful for experimenting with the fine tuning up to the point you screw up and you don't know what's causing it. I'd also like to see a slider for active skills like Waver's S1, currently the app waits the skill default of 2.5s~3s to click the target, but considering it hasn't been implemented yet, it's probably not something easy to implement in the current code just to save a few seconds in a run.

For now, here's the default values in case someone screwed up and wants to fix them without reinstalling the app:

> Support
> Swipes per Update: 10
> Max Updates: 3
> 
> Similarity
> Min Similarity: 80
> MLB Similarity: 70
> 
> Clicks
> Wait after clicking: 300ms
> Click duration: 50ms
> Delay b/w repeated clicks: 10ms
> 
> Swipes
> Wait after swiping: 700ms
> Swipe Duration: 300ms
> Support Swipe Multiplier: 100%
> 
> Wait
> Wait Multiplier: 100%

**Comment by MathewSachin** [comment]
> I'd also like to see a slider for active skills like Waver's S1, currently the app waits the skill default of 2.5s~3s to click the target

The way the code was written in FGO lua, when a skill is clicked, the script doesn't know if it will be targetted.
After a skill is pressed, the app waits for skill animation to start, by waiting at max 2s for Attack button to disappear. This is for handling any lags that may occur.
But, when a skill is targetted, the Attack button doesn't disappear and that 2s wait happens here even though it is not needed.
We can't entirely remove this wait, but can make the `2s` configurable I think.

**Comment by MathewSachin** [comment]
> May your quick memes be full of Nyantas, Parvaties, Dantes, Melts and Zerkalots!

I doubt I can get all of them being F2P 😆. I have Parvati and Zerkerlot NP1. It'd be nice if I could get the others too!
Though I still haven't raised Skadi yet. Had given up hope on getting her and used the mats I saved on other servants 🤣 but finally got her!

----

Now, setting only the options on Fine-tune screen to default values would be too much redundant code.
So, what I'm thinking is to just to show the default values below the corresponding settings. I think that should solve the problem.

<img src="https://user-images.githubusercontent.com/10654537/88257262-f6933200-ccda-11ea-909b-66b6a2ef1b14.jpg" width="250">

**Comment by MathewSachin** [comment]
Done in 01e0ef94e22f3d1c9f653d8a98608979c80c64e8
