### ISSUE TITLE
Skip auto skill config screen

### ISSUE THREAD

**Issue by buitim** [MathewSachin/Fate-Grand-Automata#189]
Firstly, thank you for the amazing updates! With the new v0.15.0 update, auto skill configs are enabled by default. This is very much a QoL feature I'm requesting, but is it possible to skip the modal that pops up if there is <= 1 config? I rarely use skills when autoing (mainly out of laziness to set up properly) and having to click the "Ok" button on the modal is an extra click/tap that I feel could otherwise be skipped. I like to grind daily nodes for the MP and find myself clicking the play/stop button for FGA often. Not having the modal would simply be a nice thing to have (like in the previous version if you had no skill configs). Of course, it is totally fine if you don't feel this is the way to go. 

Thanks for the awesome app and keep up the amazing work!

Edit: 
![image](https://user-images.githubusercontent.com/29244321/87870663-22bb5580-c95f-11ea-8c4c-b4af549d2a6d.png)

Congrats!!! 🥳

**Comment by MathewSachin** [comment]
The empty dialog that is shown when you have no configs is a clue to the users that there is something called AutoSkill you can set up. And, when only is setup, the radio buttons are a clue that you can set up more.

I'll have to think if I should really not show the dialog in these cases.

> Congrats!!! 

Thank you 😊

**Comment by MathewSachin** [comment]
So, I've come to the decision that I won't be removing this screen, for the reasons in my previous commit.
Though you can keep a fork of this project with that screen removed pretty easily if you want.

**Comment by buitim** [comment]
30caa7f0? And np. Thanks for the update! Keep up the awesome work man 👍
