### ISSUE TITLE
Idea for option to disable repeat for "boost" events

### ISSUE THREAD

**Issue by munchmeister** [MathewSachin/Fate-Grand-Automata#198]
Hi, I just had an idea after using this awesome program in the current Dead Heat Summer Race Rerun (thank so much and thanks to FGOLua too!). 

Currently, the program chooses to click the repeat button on free quests. However, this conflicts with the setting to automatically use boost items, since using the repeat button will skip the boost item choice entirely. So maybe have a sub-setting with the boost-item setting that allows us to choose to not use the repeat button. 

One potential problem with that I'm not sure about is that FGAutomata might not work during the races portion, as the free quest mission difficulties don't automatically show up. I don't know if there is any possible workaround. Perhaps the screen could try to detect that revolving FGO diamond logo that appears on recently selected nodes in order to choose? Not sure if that's possible either, and that'd be a lot of work...

**Comment by MathewSachin** [comment]
See https://github.com/MathewSachin/Fate-Grand-Automata/issues/193 for why we won't be doing this.
