### ISSUE TITLE
Make autoGameArea configurable

### ISSUE THREAD

**Issue by reconman** [MathewSachin/Fate-Grand-Automata#20]
Some devices have weird notch logic like the Samsung Galaxy A50 in this example:
![](https://cdn.discordapp.com/attachments/698141906273828885/698152986211254330/Screenshot_20200410-194753_Fate_GO.jpg)

The widths are as follows:
notch: 77px
left blue bar: 133px
right blue bar: 172px
right white bar: 39px

Seems like FGO treats the notch and the white bar as usable area. On my device, FGO does not use the notch area, so the blue bars on the left and right are the same size.

The app will only work for this device if you can set autoGameArea to false.

**Comment by reconman** [comment]
Actually, it's related to a Samsung-only setting, [Full screen apps](https://www.samsung.com/us/support/answer/ANS00079034/)

Here's a screenshot of FGO with full screen set to `auto`:
![](https://cdn.discordapp.com/attachments/698141906273828885/701219549831233616/Screenshot_20200419-065227_Fate_GO.jpg)

The app may work if you disable fullscreen mode.

**Comment by MathewSachin** [comment]
`AutoGameArea` is a pretty weird name.
If we're going to give an option for this to the user, we should think of a better name too.
