### ISSUE TITLE
Multi-delete at Autoskill list screen

### ISSUE THREAD

**Issue by AlfredPaguio** [MathewSachin/Fate-Grand-Automata#201]
It would be nice if we have multi delete skill list item at autoskill list screen

P.S. sorry for wrong grammar

**Comment by MathewSachin** [comment]
Gave it a try. I'm pretty new to Android so this looks pretty difficult for me right now.

**Comment by MathewSachin** [comment]
After spending a few hours on `RecyclerView`, I think I'm getting the hang of it.
I might be able to do this 🎉

**Comment by AlfredPaguio** [comment]
Thank you very much
