### ISSUE TITLE
Root? (NOX)

### ISSUE THREAD

**Issue by Claey** [MathewSachin/Fate-Grand-Automata#202]
Is it actually safe to play FGO with root on?

**Comment by MathewSachin** [comment]
What do you mean by safe here? Getting banned? I've heard that playing on emulators is against the Terms of Service in the first place.
Not that I've heard about DW banning anyone for playing on emulators.

**Comment by Claey** [comment]
Yes, the banning thing, since FGO used to not be able to be played with root on. Has there been any complain from people who use Nox?

Great app btw I used it on my phone and it really helped.

**Comment by MathewSachin** [comment]
Nope, no one playing on Nox complained. I think you won't get banned unless you go and tell DW yourself that you're playing with root/emulator or using this app.
People have been playing with FGO JP for quite some time on Nox with root ON.
