### ISSUE TITLE
Toggle button in notifications 

### ISSUE THREAD

**Issue by Miepmeister** [MathewSachin/Fate-Grand-Automata#215]
as of now, if you want to disable the button to start a script you always have to go into the app and use the toggle there
the idea now would be to add some sort of toggle into the app notification to eliminate the necessity to swap between apps

PS: wouldn't the head of an automata (with some "grand" signifier) actually make sense as app icon seeing as it's called fate/grand automata?

**Comment by MathewSachin** [comment]
> as of now, if you want to disable the button to start a script you always have to go into the app and use the toggle there
the idea now would be to add some sort of toggle into the app notification to eliminate the necessity to swap between apps

Nice idea. I always thought of doing this but kind of forget. I'll try to prioritize it today.

> wouldn't the head of an automata (with some "grand" signifier) actually make sense as app icon seeing as it's called fate/grand automata?

ehh, but Automatas look so ugly 🤣. We're already happy with the icons so let's just leave it as it is. And, creating good icons for Android is no easy job either. We already spent a few days to make the current icons.
