### ISSUE TITLE
Respond to Repeat quest button faster

### ISSUE THREAD

**Issue by Miepmeister** [MathewSachin/Fate-Grand-Automata#222]
does the clicking options in fine-tune apply to the clicking behavior in the post-quest screen? meaning how long the app clicks until waiting or clicking repeat etc

**Comment by MathewSachin** [comment]
Not yet.
But, rather than making it a fine-tune option, I would like it better to rewrite that part of the code to make it respond faster to repeat quest button.

**Comment by Miepmeister** [comment]
that would have been my next enhancement issue then lol so yeah
