### ISSUE TITLE
Should add the checking if Friend Pt summoning

### ISSUE THREAD

**Issue by shineburst** [MathewSachin/Fate-Grand-Automata#224]
Love the work you guys are doing. I decided to start using the app a couple of weeks ago. Looking at the friend pts summon scripts. I think there should be an option to only allow the script to roll on the friend summon gacha. If someone is not planning attention, all of their SQ can disappear. 

I modified these files to always ensure this. 
[AutoFriendGacha.zip](https://github.com/MathewSachin/Fate-Grand-Automata/files/5013270/AutoFriendGacha.zip)

**Comment by MathewSachin** [comment]
Really appreciate that you're willing to contribute, but, can you open a pull-request for this?
That would make it much easier for us to review the changes you made and also have a build realy to test.

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
