### ISSUE TITLE
After the first or second battle the script keeps refreshing the friend list even though the selection mode is set to "first"

### ISSUE THREAD

**Issue by duradara** [MathewSachin/Fate-Grand-Automata#229]
Sorry if my english is bad.

> MAKE SURE YOU TESTED THE LATEST RELEASE.

I have the latest release

> Samsung user? See https://mathewsachin.github.io/Fate-Grand-Automata/SAMSUNG.html

I am using NOX

**Describe the bug**

After the first or second battle the script keeps refreshing the friend list even though the selection mode is set to "first". 
The script works fine the first time but it bugs after that. 
After it refreshes the list for like 2 to 3 minutes it finally selects a support. 

**Video**

https://www.youtube.com/watch?v=dprjYbfxDXk

**Device Info (please fill atleast 'Device model'):**

 - Device model: NOX
 - Screen size: 720x1280
 - Android Version: Android 7
 - RAM: 4GB

**Comment by reconman** [comment]
Would you mind taking another video with debug mode enabled? It's in `more settings`

**Comment by MathewSachin** [comment]
I think I get the problem. This code assumes support screen loads within 3 seconds after refresh, but takes longer in your case.

https://github.com/MathewSachin/Fate-Grand-Automata/blob/dd2f46708d98c98857844a9d7804156f59e9d450/scripts/src/main/java/com/mathewsachin/fategrandautomata/scripts/modules/Support.kt#L80-L93

I'll try to rewrite in a way to avoid refreshing unless absolutely necessary

**Comment by reconman** [comment]
How about looking for the "Connecting" text in the bottom right in order to check whether loading has finished?

**Comment by MathewSachin** [comment]
> How about looking for the "Connecting" text in the bottom right in order to check whether loading has finished?

 I've tried before. Didn't work reliably for me. Also, iirc, sometimes it shows `Loading ...` too.

**Comment by MathewSachin** [comment]
I'm thinking of looking for `Confirm Support Setup` for real supports and that flag for Story supports to know when support screen is loaded. We can also use the `Extra` class icon to check that the dialogs are opened/closed (other classes get those advantage/diadvantage overlays).
And, when there are no supports matching the filters, we need to check for this screen too:

![support not found](https://user-images.githubusercontent.com/10654537/89398822-3c1a1b00-d72f-11ea-8034-aa778161bfe1.jpg)

Overall, this is pretty complex.

**Comment by MathewSachin** [comment]
#231 is the best I could come up with right now. Seems to work fine for First support selection.
I want a few dead weeks without events to test things properly 😞

**Comment by reconman** [comment]
There's 1 dead week in September and 5 days in October. The rest is events.

![image](https://user-images.githubusercontent.com/12360257/89407205-a8405300-d71e-11ea-94f4-f05edd219a75.png)

**Comment by MathewSachin** [comment]
I'm trying to do the events on natural AP to save Apples for Gilfest. I think with this schedule, we'll have to give up some apples 😢

**Comment by MathewSachin** [comment]
@duradara Can you try downloading the APK from this page: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/196518882
I think it should solve the problem. I'm not releasing yet because I have to test it more.

**Comment by duradara** [comment]
@MathewSachin I tried the apk and its working fine now
