### ISSUE TITLE
Add "Any" option to preferred CEs

### ISSUE THREAD

**Issue by HyunAe21** [MathewSachin/Fate-Grand-Automata#233]
Give an option to not set any preferred CEs when selecting a support servant.

**Comment by MathewSachin** [comment]
Just don't set a preferred CE and it should use Any CE? Did you try that?

**Comment by HyunAe21** [comment]
I apologize.
It seems I am an asshat that does not verify if one time issues can be reproduced.
Yesterday On 3 consecutive tries  to set up a generic daily script it output an error concerning the CE.
Today it works. I am so sorry.

**Comment by MathewSachin** [comment]
Oh, then you should have reported that error instead of asking as a feature.
Well, there is a bug in the released version which can cause that error to happen first time after using a different AutoSkill config.
A fix is already in place. Expect in next release.
