### ISSUE TITLE
Possible timing issue after latest release.

### ISSUE THREAD

**Issue by SeraOverdose** [MathewSachin/Fate-Grand-Automata#237]
> MAKE SURE YOU TESTED THE LATEST RELEASE.

**Describe the bug**
Im receiving an issue after the update, ive tried with ignore notch calc on and off. When i start the app it goes into the quest and selects my support as normal. Then when attempting to do the party change the tap doesnt register, it then taps start quest which doesnt register either.

**Screenshots**
If an error occurred, you can find the message by expanding the app's notification.
It is recommended that you atleast add one screenshot of FGO running on your device.

**Video**
https://youtu.be/rxBH_SJzu-g (Video posted unlisted, github giving me issues when attaching.)

**Device Info (please fill atleast 'Device model'):**
 - Device model: [e.g. Samsung Galaxy S9+]
 - Screen size: [2220x1080]
 - Android Version: [Android 10]
 - RAM: [e.g. 6GB]

**Comment by reconman** [comment]
Which party number is configured in your Autoskill configuration? Party 1?

**Comment by SeraOverdose** [comment]
Yeah party 1

![Screenshot_20200806-162711_FateGrand Automata](https://user-images.githubusercontent.com/69328330/89592592-cfbc1c00-d801-11ea-8b5b-4628637ecfc4.jpg)

**Comment by reconman** [comment]
Just a side note, your SkillCommand seems pretty weird. Lots of unnecessarily targeted skills and you use NPs in multiple rounds, but not multiple waves.

**Comment by SeraOverdose** [comment]
Yeah thanks, i just threw this one together for my first try as i started using this when i started playing the app. Its been working fine for weeks now. Been too lazy to go back and edit it now that im more familiar, but i definitely will!

**Comment by MathewSachin** [comment]
FGO has a problem right now. If you click on the dots on top for the party which is already selected, the start quest and some other buttons on the screen stop working. You then have to switch to a different party and come back.

To account for this, the app checks the current party and clicks only if the party needs to be changed. Right now I'm farming extensively with Party 1 but didn't get this problem, so I'm not sure why it's clicking on already selected party for you. But, I think it's not a timing issue.

And, the help screen opening, in this case, is due to the boost item option.

**Comment by SeraOverdose** [comment]
> FGO has a problem right now. If you click on the dots on top for the party which is already selected, the start quest and some other buttons on the screen stop working. You then have to switch to a different party and come back.
> 
> To account for this, the app checks the current party and clicks only if the party needs to be changed. Right now I'm farming extensively with Party 1 but didn't get this problem, so I'm not sure why it's clicking on already selected party for you. But, I think it's not a timing issue.
> 
> And, the help screen opening, in this case, is due to the boost item option.

**Comment by SeraOverdose** [comment]
Thank you guys for looking into this, im seeing that as well. For some reason after several tries it is working again but everytime i first start the app it resorts back to this. Definitely seems to be on the fgo side. Appreciate the help! And once again thanks!
