### ISSUE TITLE
Option to repeat quest a specified number of times (without overriding number of apple repeat)

### ISSUE THREAD

**Issue by Andybui1012** [MathewSachin/Fate-Grand-Automata#238]
Can this option be implemented? It would be helpful if you just want to run quest once for clear reward using universal team or maybe the number of run needed for shop clear cost less ap than the multiple of apple refill.

**Comment by MathewSachin** [comment]
Any idea how the UI for this should be? I think people would get confused if both options (No. of runs & No. of refills) are there, like which gets priority.

**Comment by Andybui1012** [comment]
I think it can be a tab similar to the refill option with some kind of title like Number of Repeat and in there user can pick unlimited repeat (until run out of ap) or enter a number to limit the number of run (but still stop when no apple left). About the priority i think whichever one each is reached it will stop the script and have a pop up to tell the user the reason so they don't necessary take priority over each other. It just add constraint to avoid accident ap consumption so if people don't want to use it they can just left unlimited repeat.

**Comment by MathewSachin** [comment]
Ok, so if we don't give priority to either, then an option on the Refill page itself below the existing settings should be fine I think. I don't think we should add another top-level menu for this.

**Comment by AlfredPaguio** [comment]
Ahmm can I have suggestion for this?
I think it's better to fuse them like
Repeat Mode: Apples or number of runs

(will use apples* to attain that no. of runs)
*Of course you will not delete the data input at apples (no. of refills , what apple to use etc..)
Sorry for wrong grammar

**Comment by MathewSachin** [comment]
But, even if we add a repeat mode, and set it to number of runs, we still need to specify what kind of apples to use for refill.
And if we're showing both apples and number of runs, when user chose number of runs, I think it is better to keep them separate and stop the script when either of them exceeds the limit.

> Sorry for wrong grammar

No need to write this every time bro, your grammar is good enough.

**Comment by MathewSachin** [comment]
This is the UI I'm planning:

<img width="250" src="https://user-images.githubusercontent.com/10654537/89706634-33bb1d80-d985-11ea-84d3-c20c84752ccb.jpg">

**Comment by AlfredPaguio** [comment]
So if the refill option is off then you will not spend any apples when the run is not achieved?

**Comment by MathewSachin** [comment]
> So if the refill option is off then you will not spend any apples when the run is not achieved?

Correct. Unless you specify which and how many apples are to be used, no apples will be used.

> And if the limit no of run is on then the repetition in the refill category is disabled/hidden?

No. Turning one option ON won't turn OFF the other.
