### ISSUE TITLE
Move 'Brave Chains' & 'Rearrange cards' options to AutoSkill

### ISSUE THREAD

**Issue by Miepmeister** [MathewSachin/Fate-Grand-Automata#239]
ignoring the fact that ignore bravechain and rearrange cards are labeled as experimental my suggestion would be to move them over to the autoskill options as I think this is something that changes with every skillset

**Comment by MathewSachin** [comment]
The reason I didn't put them in AutoSkill is because they're experimental.
I know better than anyone that they belong to AutoSkill configs. I just don't want everyone to just start complaining about these not working, since there are many conditions at play for them to work.

**Comment by MathewSachin** [comment]
I've still not decided if these options will stay as it is. I might even completely change these settings if I found some other better options.

**Comment by MathewSachin** [comment]
Also, I think everyone would like for it to be per-wave since you might want to avoid brave chains in some wave but prefer in another.

**Comment by Miepmeister** [comment]
> Also, I think everyone would like for it to be per-wave since you might want to avoid brave chains in some wave but prefer in another.

was about to write this lol, in the case you decide to keep those features, and if they aren't experimental anymore, then it might be an idea to add them to the card priorities as the toggles they already are in like

**Comment by MathewSachin** [comment]
For the people complaining, I meant Brave chains and rearrange cards don't work in all cases. Like, they won't work if NP spamming is ON and some other cases which I wrote about in the Pull Request and also in the Changelog. I'm sure most people won't go into reading changelogs in detail and then say these features don't work 🤣 
But, there's a bug in the released version of Avoid brave chains, I'll put the fix in the next release.

**Comment by MathewSachin** [comment]
>  I definitely like the stop button in the notification 😁

Yeah, I love that too. Didn't know how much I needed that. Really convenient to not have to open FGA for just turning OFF the service.

**Comment by Miepmeister** [comment]
> > I definitely like the stop button in the notification 😁
> 
> Yeah, I love that too. Didn't know how much I needed that. Really convenient to not have to open FGA for just turning OFF the service.

definitely a qol update that everyone didn't know they need, the next logical step would probably be a start button in the notification, or if we feel really crazy (which isn't that impossible considering I'm having 30°C here atm which will hit all the harder when I go to training in a few minutes lol... I'm gonna die) maybe create a widget lmao
first option would ofc presuppose that the notification is turned somewhat permanent? tho I don't know if that could cause issues

**Comment by MathewSachin** [comment]
Unfortunately, we can't have the start button that way. Accessibility services cannot be started programatically, so we have to send user to settings to turn that ON manually. Also, MediaProjection (which is used for screenshots) also requires permission from users.
In both these cases, to ask permission from user, the app must be in foreground, so we can't start from a notification.

Also, keeping the notification permanent isn't a good idea for many reasons.

**Comment by Miepmeister** [comment]
> Unfortunately, we can't have the start button that way. Accessibility services cannot be started programatically, so we have to send user to settings to turn that ON manually. Also, MediaProjection (which is used for screenshots) also requires permission from users.
> In both these cases, to ask permission from user, the app must be in foreground, so we can't start from a notification.
> 
> Also, keeping the notification permanent isn't a good idea for many reasons.

figured as much already, well it was an idea
would a widget then even somehow work in theory? I can guess the issues would be roughly the same

**Comment by MathewSachin** [comment]
yeah, the UI shown in a widget has many restrictions. I'm not completely sure, but I don't think the permission flow would work there.

**Comment by MathewSachin** [comment]
I started work on this but it's too much effort with Android current UI framework.
A new Android UI framework: Jetpack Compose just released in Alpha which will trivialize the code for this.
I'd rather wait for it become a bit more stable and implement this.
