### ISSUE TITLE
Fine Tune Defaults

### ISSUE THREAD

**Issue by AlfredPaguio** [MathewSachin/Fate-Grand-Automata#243]
Please add button to return the fine tune settings to default and please remove(or make it on/off) that screen transition at app please

**Comment by MathewSachin** [comment]
> Please add button to return the fine tune settings to default

Please look at old issues before opening a new one: #187. I've written about the problems there.

> please remove(or make it on/off) that screen transition at app please

Mind telling why??

**Comment by AlfredPaguio** [comment]
> > Please look at old issues before opening a new one: #187. I've written about the problems there.
> Sorry for duplication ahmm can I ask if this is already implemented?
> > please remove(or make it on/off) that screen transition at app please
> Ahmm I don't know but I have this feeling that ahmm kinda weird or awkward

**Comment by MathewSachin** [comment]
>Sorry for duplication ahmm can I ask if this is already implemented?

It would need too much duplicate code maintaining which would be difficult.

> Ahmm I don't know but I have this feeling that ahmm kinda weird or awkward

Having no animation before felt extremely weird to me, so I added defaults from AndroidX.
I think you'd get used to it soon.
