### ISSUE TITLE
Getting Stuck on Servant Status Screen

### ISSUE THREAD

**Issue by Rajvir8** [MathewSachin/Fate-Grand-Automata#248]
I find that after the latest update that whenever auto accidentally selects a Servant it gets stuck and doesn't ever click out of it.

![Screenshot_20200811-151251](https://user-images.githubusercontent.com/17600697/89939364-dffb3f00-dbe5-11ea-97c4-940ec2d38b8c.png)

I'm hoping that the feature of clicking off to get out of the status screen of the Servant will be added.  Otherwise it can stuck at places as shown on the screenshot.

**Comment by reconman** [comment]
When does that usually happen? Does it happen often?

**Comment by MathewSachin** [comment]
Are you trying to do what you're doing in this issue? https://github.com/29988122/Fate-Grand-Order_Lua/issues/247
We don't detect if skills are on cooldown.

Servant details screen shouldn't open in the first place otherwise (unless due to some lag).
And, if it opens, yeah, the script won't exit it currently.

**Comment by MathewSachin** [comment]
It might have been exiting automatically before due to clicking on all 5 face cards. But, It's not something you should rely on.

**Comment by Rajvir8** [comment]
My first thought is that Skill Cooldown's should have nothing to do with it, but you have a point actually.

It may be because of Skill Cooldowns as it'll exit out of the menu and then click for NP and normal Cards and get into Servent Details Screen.  

I'll watch to be sure.

**Comment by Rajvir8** [comment]
Yes it is because it was clicking a Skill that was on Cooldown.

Unfortunately it was the last skill before starting the card wave which did cause it.

It was happening consistently because of it as well, I'll have to experiment and see if putting my Mystic code at the end of turn 1 Wave three might fix it.

**Comment by Rajvir8** [comment]
I'll have to rewrite it to fix the issue, but I hope that a feature to click off of Servant Detail Screen can be added sometime in the future as it still could have cleared even without the skill.

**Comment by Tallavn** [comment]
I found the way fix this issue. When write command, before everyturn start u need select enemy to attack
