### ISSUE TITLE
App seems to not recognize screen area

### ISSUE THREAD

**Issue by AlwaysDryzen** [MathewSachin/Fate-Grand-Automata#250]
**Describe the bug**
Automata app is the latest release. After starting service and selecting the auto skill, nothing happens. I have set the app to run in full screen mode, however I noticed that the scaling doesn't look right (I haven't actually measured it yet), and there's black bars in multiple areas still. 

**Screenshots**
With debug mode on, this is all that happens in both support select and in battle. 
![Screenshot_20200812-092953](https://user-images.githubusercontent.com/22807456/90042868-1c7b7900-dc80-11ea-9b98-b3f70f8fa582.png)

Here are my settings
![settings](https://user-images.githubusercontent.com/22807456/90043744-6153df80-dc81-11ea-96ba-5bed6f314ce1.png)
![settings1](https://user-images.githubusercontent.com/22807456/90043756-66189380-dc81-11ea-8b4b-706587d6b142.png)
![settings2](https://user-images.githubusercontent.com/22807456/90043755-657ffd00-dc81-11ea-9b92-04610f219526.png)

**Device Info (please fill atleast 'Device model'):**
 - Device model: LGv60
 - Screen size: 2560x1080
 - Android Version: 10
 - RAM: 8GB

**Comment by MathewSachin** [comment]
Can you check if there is a way to get rid of that black bar below the automata app.
It seems the regions are offset by that amount.

**Comment by AlwaysDryzen** [comment]
Yeah, I figured it was the cause. I tried messing around with all the different screen scaling options, but it persists across all of them.

**Comment by AlwaysDryzen** [comment]
I put a bit more critical thought in to it and realized that the bar is being drawn for the sake of android gestures. Turning them off (changing back to the original android app swapping options) gets rid of it and makes things work as intended.
