### ISSUE TITLE
Swapping servants using Master skill (Battle Suit)

### ISSUE THREAD

**Issue by Tenken77777** [MathewSachin/Fate-Grand-Automata#251]
Hi, please implement the ability to swap servants (battle screen <> support) using the Battle Suit Master Skill in the skill maker function.  Thanks!

**Comment by reconman** [comment]
You mean this? https://youtu.be/-KyiaL1qkJw?t=745

**Comment by Tenken77777** [comment]
Oh I didn't see the Order Change function, thanks for the video
