### ISSUE TITLE
Select the desired class list when entering a quest node

### ISSUE THREAD

**Issue by Draw99Gray** [MathewSachin/Fate-Grand-Automata#252]
Hi, could you add a function to select the class list you want?
For example, i want to farm a Rider node, so the friend list automatically points to Assassins, and i need Chaldea Lunchtime which can be found normally in Casters
Or i need a MLB CE which is easily found in the ALL section instead of combing through every class list

**Comment by MathewSachin** [comment]
Duplicate of #35 
Already done in #232
