### ISSUE TITLE
Ability to place CEs with similar effects in a folder.

### ISSUE THREAD

**Issue by tenshimkii** [MathewSachin/Fate-Grand-Automata#257]
For example this bunch of CEs have the same effect, just different art: https://fategrandorder.fandom.com/wiki/Heroic_Spirit_Portrait.

I think it will be a great idea to have a similar function you did for servant ascensions.

**Comment by MathewSachin** [comment]
When making folders for servants, I obviously considered the same for CEs and my conclusion was to NOT support that.
The only case where it is useful was Heroic Spirit Portraits, and even for them, people usually picked the popular ones. Like it is very unlikely you'll come across Mephistopheles' portrait CE.
Also, having too many CEs (10 here) to match would just slow down Support selection too much.

---
More so, it'll be a real pain now to change all the code to support folders for CEs for which I don't see much benefit.
