### ISSUE TITLE
Feature request -- Unique face card selection + Castoria support image

### ISSUE THREAD

**Issue by weiliang321** [MathewSachin/Fate-Grand-Automata#258]
I'm farming bones in Fuyuki now, and what I notice is that I'm often unable to complete a quest in 3 turns using the script as the script sometimes select duplicate cards to attack. Manipulating the card selection priority doesn't help much, so I would appreciate it if the script can prevent the selection of the same Servant card side-by-side.

An example based on card selection priority: Servant 1 WB, Servant 1 WB, Servant 2 B
In a wave of 3 enemies, this would only kill 2 enemies in 1 turn, taking an extra turn to kill the next enemy in the wave. This can easily be avoided if the cards Servant 2 B and Servant 1 WB were swapped, but the script doesn't do that, so what I'm requesting is that the script does not choose a Servant X card if the preceding card is Servant X.

Of course, I can finish it in 3 turns using 3 different NPs, but that's a tad too overkill and I would rather save time by just using face cards instead.

On an unrelated note, can we also have Castoria added to the default support images? Since she'll be used quite frequently by JP players.

**Comment by reconman** [comment]
Castoria is done with #247 

The best we can offer right now for Fuyuki is the feature from #212

**Comment by MathewSachin** [comment]
I'll push 1st ascension of Castoria in a while.
Avoid brave chains has a bug in the released version right now. Expect it to work properly from next release.

Just look at the closed Issues and Pull-requests before opening a new one, It'll save the effort for both you and us.
