### ISSUE TITLE
Sometimes it works, sometimes it doesn't

### ISSUE THREAD

**Issue by DogaGungor** [MathewSachin/Fate-Grand-Automata#259]
I was able to use it for 1-2 days when I first downloaded it, but then it stopped working. Although I press the button, it doesn't play automatically at all. I deleted it again and installed it, it was working at first, then it stopped working again. Also, the commands I gave in the Autoskill section are not detected correctly. Cards are used although I chose to use NP. I'm using Huawei Mate 20 Lite.
Android Ver. 9.

**Comment by reconman** [comment]
Please provide screenshots of your autoskill configuration and provide a video of the app not working with debug mode being turned on.

**Comment by MathewSachin** [comment]
@DogaGungor why did you just delete the BUG template. The things we ask there are important to find the problem.

**Comment by DogaGungor** [comment]
This one is EXP Team configuration
![image](https://user-images.githubusercontent.com/40243870/90254527-8f851b00-de4b-11ea-9f05-2be708b6b801.png)

This one is QP Team configuration
![image](https://user-images.githubusercontent.com/40243870/90254596-ac215300-de4b-11ea-9893-5362331637fd.png)

Video:
https://youtu.be/W02fNmCQQy0

**Comment by DogaGungor** [comment]
> @DogaGungor why did you just delete the BUG template? The things we ask there are important to find the problem.

I didn't know it was a template, I just thought it was an explanation.

**Device Info:**
 - Device model: Huawei Mate 20 Lite
 - Screen size: 2340x1080
 - Android Version: Android 9
 - RAM: 4 GB

**Comment by MathewSachin** [comment]
How are you using Bandicam on your phone? FGA won't work properly if other screen recorders are running.
Use the inbuilt recorder for reporting bugs. It's available in `More options / Record Screen`.

**Comment by DogaGungor** [comment]
Okay, I did it:
https://youtu.be/x_OrSTl3jvA

**Comment by MathewSachin** [comment]
I meant, use the recorder within FGA (the app) itself, not any other recorder on your phone.
Running other recorders can cause problems with FGO.

**Comment by DogaGungor** [comment]
https://youtu.be/i4OYCmSbu-8

I guess i did it.

**Comment by tchofy** [comment]
Not directly related to his issue, but something I noticed that he'll need to fix it later: in skill command, you're using a comma to separate each wave, but for that you want a ",#,", to tell the app you want to use those commands in the next wave, not the next turn. You only use a single comma when you're farming a node that has 4~6 enemies in a single wave, which is very rare.

**Comment by yunamon** [comment]
Not related to OP's issue, but I think this title pretty much describes the issue I noticed.

When the script selecting Merlin support, I notice sometimes it will most of the time skip through Merlin supports with final ascension art even though it fits the criteria of the options (10,10,10 skill; no CE preference for example).

Perhaps the PNG used for the final ascension have issues in detection?

Also, will we get the option for new Castoria support too?

**Comment by reconman** [comment]
@yunamon You could look into the logs using adb and logcat. It's not user friendly and hard to search for, but every time images are compared, a message is logged containing the similarity value.

Castoria will be included in the next release.

**Comment by DogaGungor** [comment]
Is there no solution to my problem?

**Comment by reconman** [comment]
I only just now watched the video, the behavior is really strange. Something seems to be blocking the clicks.

**Comment by DogaGungor** [comment]
Could it not be working because I use Castoria?

**Comment by MathewSachin** [comment]
@DogaGungor I don't have a solution yet. another person with a Huawei phone said that they have the same problem. But, there are Huawei users not having any problems.
I can only give generic advice here.
1. Don't run other screen recording apps when running FGA.
2. Clear cache for the app or restart your phone.
3. Disable battery optimization for the app: https://dontkillmyapp.com/huawei
4. Are there any other apps that could kill FGA. e.g. Battery doctor, antivirus.

---
Castoria shouldn't be a problem.

**Comment by DogaGungor** [comment]
Another application might be interfering, but I don't know if there is. I do not use such applications.

**Comment by DogaGungor** [comment]
When I delete the app's data, it gets fixed, but then it gets corrupted again somehow.

**Comment by reconman** [comment]
@DogaGungor Try disabling and then enabling the accessibility service.

**Comment by MathewSachin** [comment]
@DogaGungor after how much time does it get corrupted? You won't have to delete data. Just clearing the cache should be enough.

**Comment by DogaGungor** [comment]
> @DogaGungor after how much time does it get corrupted? You won't have to delete data. Just clearing the cache should be enough.
I don't think it happens after a certain time, I guess it happens after using the app several times a day. Clearing the cache didn't work, I tried.

> @DogaGungor Try disabling and then enabling the accessibility service.
It doesn't work either.

**Comment by MathewSachin** [comment]
You might want to look at #354. They said their issue was solved by the tweaking the battery saver settings as said on dontkillmyapp.com

**Comment by MathewSachin** [comment]
#363 solved by following the same steps as #354. So, I think that should work fort you too.
