### ISSUE TITLE
Issues with selecting supports

### ISSUE THREAD

**Issue by joshualxw** [MathewSachin/Fate-Grand-Automata#260]
> MAKE SURE YOU TESTED THE LATEST RELEASE.
Yes
> Samsung user? See https://mathewsachin.github.io/Fate-Grand-Automata/SAMSUNG.html

**Describe the bug**
Bug where the app doesn't scroll through the support list but only taps on the left side of the screen. To add on, app only works properly when the top of my phone is facing the right. Not sure how to explain it but on a set orientation?

My settings are the prefered servants which are currently Raikou.png and Arjuna.png which were created using the Support Maker script.

**Screenshots**
If an error occurred, you can find the message by expanding the app's notification.
It is recommended that you atleast add one screenshot of FGO running on your device.

**Video**
[https://streamable.com/t795h8](url)

**Device Info (please fill atleast 'Device model'):**
 - Device model: Asus ZenFone 5Z
 - Screen size: 1080 x 2246
 - Android Version: Android 10
 - RAM: 6GB

**Comment by joshualxw** [comment]
I forgot to say that my I set to preferred servants which are currently Raikou.png and Arjuna.png which were created using the Support Maker script.

**Comment by MathewSachin** [comment]
The problem is FGO isn't taking up the whole screen. Pretty similar to what happens on Samsung phones.
Can you check if there is any option to make FGO run as a Full Screen app on your phone.
Those blue borders should fill the black area of the screen.

**Comment by joshualxw** [comment]
I've tried what you said and I've gotten it running in Full Screen. It managed to scroll up once and then it continued behaving like whats seen on the video again. I've tried it with and without notch option.

**Comment by MathewSachin** [comment]
Upload the video in full screen please.

**Comment by joshualxw** [comment]
[https://streamable.com/l3ir9w](url)
Here you go. Thanks a lot by the way.

**Comment by reconman** [comment]
Seems like scrolling doesn't work for some reason. Also what is rotating the screen?

**Comment by MathewSachin** [comment]
Something's really weird here, how does FGA look on your phone?
Is it not full screen? Can you post a screenshot of the app?
@reconman even the Debug mode rectangles aren't rendering completely.

**Comment by joshualxw** [comment]
> 
> 
> Seems like scrolling doesn't work for some reason. Also what is rotating the screen?

Ahhh sorry, its just me trying it on the different orientation cause before this I had issues where only when it was counter clock-wise, the app would work properly.



> 
> 
> Something's really weird here, how does FGA look on your phone?
> Is it not full screen? Can you post a screenshot of the app?
> @reconman even the Debug mode rectangles aren't rendering completely.
[https://imgur.com/a/LL2sxUT](url)

Here you go, its full screen though.

**Comment by MathewSachin** [comment]
Oh, I meant an image of FGA (this app) not FGO

**Comment by MathewSachin** [comment]
FGO is completely extending to the notch, right? So, the `Ignore Notch` option should be ON.

**Comment by joshualxw** [comment]
[https://imgur.com/a/YsZwhl1](url)
My bad, here you go.

**Comment by MathewSachin** [comment]
I think the Back/Home buttons remaining always visible over FGA could be the problem 🤔 
Can you see if there's any way to make FGA fullscreen too?

**Comment by joshualxw** [comment]
I've changed FGA to full screen and it started scrolling properly. I'll let you know if there any other issues after this. Thanks a lot for your help!
