### ISSUE TITLE
Notification sound when the app gets stuck or exits

### ISSUE THREAD

**Issue by tchofy** [MathewSachin/Fate-Grand-Automata#263]
Currently as it stands, the app gets stuck in some screens like Bond 10 (#262), when new nodes appear but aren't automatically selected by the game (#211), and those are conditions that are really hard to test and handle, so my proposal is the following:

If either the app automatically stops because of an error, or if it hasn't done any clicking for a period of 1~2 mintues (depending on the device, maybe more), it should notify the player using audio, so that if the player is near their phone they'll know something went wrong, and for those who go to sleep and leave their phone farming during the night (Gilfest is close) they won't wake up with the surprise their X servant reached max bond 10 minutes after they slept and lost the whole night's worth of farming.

**Comment by MathewSachin** [comment]
Hey, one thing to clarify, the app should accept the Bond 10 craft essence, it just won't stop at Bond CEs like #262 wants.
The code to accept CEs is in-place, the app currently doesn't know if it is a Bond CE or a CE given after quest completion.

#211 doesn't seem like something I could support. Now, that I even have the proper sprite, still the Next arrow is outside screen bounds in most cases.

There are also some problems which are more related to how Android works. If the app doesn't click for 2minutes or so depending on user's settings, the screen turns OFF and app can't continue running. There is a way to keep the screen awake but it's not a good idea for battery usage based on my discussions with people on Gamepress.

One more thing, there are 3 ways to play the audio, through the ringer volume (used for calls and notification), media (through which music and apps like FGO play audio), and alarms.
Most users would keep Media volume OFF so any of the other 2 should work I guess.

---
I'd still recommend that you check occasionally on the app between sleeping, cause you never know if a notification pops up or something and the app can't continue.

**Comment by tchofy** [comment]
>There are also some problems which are more related to how Android works. If the app doesn't click for 2minutes or so depending on user's settings, the screen turns OFF and app can't continue running. There is a way to keep the screen awake but it's not a good idea for battery usage based on my discussions with people on Gamepress.

Very good point, default screen timeouts are from 30s to 1 minute, I keep forgetting about that since I leave mine at 5min. At least with the new Unity engine the game loads much faster even on low end devices, but I could see some of them taking more than 30s to load a map if you're on a fresh install and the game has to download all assets first.


> I'd still recommend that you check occasionally on the app between sleeping, cause you never know if a notification pops up or something and the app can't continue.

<details>
<summary>Going outside the issue post so I'll just collapse this bit</summary>
I'm way too scared to actually leave the phone running all night, I'm afraid the phone would get too hot and that wouldn't be healthy for the battery. I know it'll throttle down to protect itself but it'll still be running at dangerous temps. I usually just go do other stuff and leave the app farming for an hour or two, at best, then I give my phone and my apples some time to rest, specially if there's no need to rush an event.
</details>
