### ISSUE TITLE
About brave chain function

### ISSUE THREAD

**Issue by Andybui1012** [MathewSachin/Fate-Grand-Automata#266]
So i want to ask about this function when used after np: Does it just match servant using only standard cards or does it match with servant in NP card? because if it is the former then the script can pick cards from another servants with 3 standard cards instead of 2 cards from the servant using np which won't result in brave chain and might not have class advantage like the np card.

**Comment by MathewSachin** [comment]
The former would be useless like you said. The script does the latter.
