### ISSUE TITLE
[Feature request] Support for Korean server

### ISSUE THREAD

**Issue by sleeping-player** [MathewSachin/Fate-Grand-Automata#267]
I'm sorry I don't have language skills,
I think all I can do is take a screenshot from the list...

And does this app use the same cut screenshots used in 29988122/Fate-Grand-Order_Lua?

**Comment by sleeping-player** [comment]
checking previous lists
#109 #244

**Comment by MathewSachin** [comment]
We need all the screenshots needed for FGO-lua and a few more.
Yeah, I was going to link the CN issue too.

**Comment by reconman** [comment]
First of all, are there still a lot of Korean FGO players? Last thing I heard is that the company angered a lot of players near the end of 2018.

Second, all the needed images can be found in https://github.com/MathewSachin/Fate-Grand-Automata/tree/master/app/src/main/assets/Jp.

Third, we will need the package name of the APK. The package name shows up in the play store URL. For example, for FGO US it is https://play.google.com/store/apps/details?id=com.aniplex.fategrandorder.en

**Comment by MathewSachin** [comment]
The package name is `com.netmarble.fgok`

https://community.gamepress.gg/t/automatic-farming-app-fate-grand-automata/72155/714?u=mathewsachin

**Comment by sleeping-player** [comment]
![kr-orig-questreward](https://user-images.githubusercontent.com/69798206/90403772-65965780-e0dc-11ea-93b5-9196cf3ecea3.png)
![kr-orig-resist](https://user-images.githubusercontent.com/69798206/90403777-67601b00-e0dc-11ea-8e67-9ec8063de22f.png)
![kr-orig-result](https://user-images.githubusercontent.com/69798206/90403779-68914800-e0dc-11ea-8cb0-35fb049828a2.png)
![kr-orig-retry](https://user-images.githubusercontent.com/69798206/90403782-6929de80-e0dc-11ea-83f8-813ed63e66b5.png)
![kr-orig-support_region_tool](https://user-images.githubusercontent.com/69798206/90403785-6929de80-e0dc-11ea-88a3-006277d9fb52.png)
![kr-orig-weak](https://user-images.githubusercontent.com/69798206/90403786-6a5b0b80-e0dc-11ea-8b7c-4b55797cebd0.png)
![kr-orig-withdraw](https://user-images.githubusercontent.com/69798206/90403788-6af3a200-e0dc-11ea-9cba-3e908370d1e3.png)
![kr-orig-master_exp](https://user-images.githubusercontent.com/69798206/90403789-6b8c3880-e0dc-11ea-943a-6e5a3cd536a1.png)
![kr-orig-mat_rewards](https://user-images.githubusercontent.com/69798206/90403790-6c24cf00-e0dc-11ea-92dc-2b413ab007a5.png)
![kr-orig-others](https://user-images.githubusercontent.com/69798206/90403792-6cbd6580-e0dc-11ea-87de-f32e1f9d7e32.png)
![kr-orig-others2](https://user-images.githubusercontent.com/69798206/90403796-6dee9280-e0dc-11ea-88f0-5b16c8830f88.png)

**Comment by sleeping-player** [comment]
#244
![ko-orig-support_not_found.png](https://user-images.githubusercontent.com/69798206/90407321-58c83280-e0e1-11ea-8cf0-0577f4c0e53f.png)

**Comment by sleeping-player** [comment]
Now I am not sure where to take more screenshots...
- lottery.png, StopGifts.png (waiting for lottery event)
- master_lvl_up.png (waiting for lvl up)

- inven_full.png (when it's done...)
- confirm.png
- fp_continue.png

**Comment by sleeping-player** [comment]
> First of all, are there still a lot of Korean FGO players? Last thing I heard is that the company angered a lot of players near the end of 2018.

In short, I don't know.
People here also call this a pseudo-game, but they play this as well.
In the last Skadi summon, Korean masters blew up the FGO server and put Fate-related bulletin boards in the traffic rankings.
It is possible that these Netmarble guys have reduced the size of their servers, but at least they still have players.

**Comment by MathewSachin** [comment]
> Now I am not sure where to take more screenshots...

I think these many screenshots should be enough to get it working. It might take me a few days to crop out all the images and add support for a new server.

> confirm.png

This is for the free quest repeat screen which recently came to NA. Not sure if KR has this yet.

> fp_continue.png

Just post a screenshot of Friend Point summon result screen.

**Comment by sleeping-player** [comment]
> > Now I am not sure where to take more screenshots...
> 
> I think these many screenshots should be enough to get it working. It might take me a few days to crop out all the images and add support for a new server.

Thank you for your efforts.

> > confirm.png
> 
> This is for the free quest repeat screen which recently came to NA. Not sure if KR has this yet.

The KR event schedule is almost similar to that of NA, but the addition of functions is bad than NA.

> 
> > fp_continue.png
> 
> Just post a screenshot of Friend Point summon result screen.

![ko-orig-fp_continue.png](https://user-images.githubusercontent.com/69798206/90416737-d134f080-e0ed-11ea-8584-76252df8c16b.png)

**Comment by sleeping-player** [comment]
Oh level up
![ko-orig-master_lvl_up.png](https://user-images.githubusercontent.com/69798206/90453048-8c7b7a80-e12a-11ea-9665-0dbc15046428.png)

**Comment by MathewSachin** [comment]
Can you test by downloading the APK from this page: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/212453856

I think it should work but I don't have any way of testing it.
I've only added the images for the Battle script.

Friend point summon script won't work right now because KR seems to be still on an older Friend Point UI. It only works for NA and JP right now anyway.

**Comment by sleeping-player** [comment]
It works at least in 40ap quest.
This completes the quest normally as specified in json, and can eat apples.
again thank you very much.
but how can I proof this?

**Comment by MathewSachin** [comment]
> but how can I proof this?

Do you mean how to show us that it works? Maybe upload a video on YouTube. But it's not super important.
Just keep using and let us know if it's not working in any case.

**Comment by sleeping-player** [comment]
> > but how can I proof this?
> 
> Do you mean how to show us that it works? Maybe upload a video on YouTube. But it's not super important.
> Just keep using and let us know if it's not working in any case.

OK I'll wait
