### ISSUE TITLE
Ability to edit certain parts/ wave of skill command

### ISSUE THREAD

**Issue by AlfredPaguio** [MathewSachin/Fate-Grand-Automata#271]
For fixing mistakes

**Comment by AlfredPaguio** [comment]
For example:
![IMG_20200819_030843](https://user-images.githubusercontent.com/25319699/90555172-88eb0080-e1c9-11ea-8397-f82562b0a14a.jpg)

When you click/press the circled ahmm label? (,#,)

You will return to that part to redo only that part

Or


![IMG_20200819_031407](https://user-images.githubusercontent.com/25319699/90555550-1dedf980-e1ca-11ea-9139-303cfca5b2ec.jpg)

If you press that label , you can press any command to overwrite it like changing F to E

**Comment by MathewSachin** [comment]
AutoSkill Maker wasn't even designed to allow edits, it was made as an easy entry-point for people new to writing AutoSkill commands. You're expected to learn to write AutoSkill commands for making edits even now.

Now, before even getting into the programming aspect, I think there are logical flaws in the suggestion.

> When you click/press the circled ahmm label? (,#,)
You will return to that part to redo only that part

When you click on `,#,` or `,`, would you go to the turn before or after that?
Depending on that answer, how would you go to the first or last turn?
After someone edits that turn, do they keep adding turns in between or go to the last turn?

> If you press that label, you can press **any** command to overwrite it like changing F to E

Then someone can click on Attack button and use NPs in place of that skill?
Should Undo be allowed there?

If someone presses on an NP and replace it with a skill, it can lead to skill after NP, which is an invalid state.

There's so many flaws with this, I don't even feel like thinking about all of them.
I personally won't be doing this. AutoSkill maker isn't designed for this sadly.
