### ISSUE TITLE
After I updated to Android 10 the app no longer works

### ISSUE THREAD

**Issue by duradara** [MathewSachin/Fate-Grand-Automata#278]
**MAKE SURE YOU TESTED THE LATEST RELEASE.**
I am using the latest release

**Describe the bug**
Yesterday I updated to Android 10 and after I reinstalled everything the app doesn't work

**Screenshots**
An image of my settings. I also tried with the notch option on and it still doesn't work
https://imgur.com/a/EWlky9g
Image of the script I was using:
https://imgur.com/a/qZVIV1G

**Video**
The debug mode is on.
https://www.youtube.com/watch?v=K9jxIyaaWfs

**Device Info (please fill atleast 'Device model'):**
 - Device model: Samsung galaxy J6
 - Screen size: 720 x 1480
 - Android Version: Android 10
 - RAM: 2 GB

**Comment by MathewSachin** [comment]
When you opened the issue, there was a Samsung link, did you see the instructions there?

**Comment by MathewSachin** [comment]
Make FGA a full screen app like you might've done for FGO and it should work.

**Comment by duradara** [comment]
Yes I saw it and fgo its already a full screen app

**Comment by MathewSachin** [comment]
Can you check again if FGA is full-screen?
I'm not really sure about that. Should the navigations buttons show on a full-screen app?
Then again, the regions in the video are correct.

This seems similar to #259.

**Comment by duradara** [comment]
It says that FGA its already optimized for Full Screen and doesn't let make make it FS 
https://i.imgur.com/n38gmWu.jpg

**Comment by MathewSachin** [comment]
#259 was for Huawei phones though. We have quite a few Samsung users who just had to make FGO full screen after Android 10 update.

Can you try if the things suggested in #259 work?

**Comment by duradara** [comment]
Apparently I just needed to restar the phone and it works now. I don't know why I didn't tried that before posting this. Sorry
