### ISSUE TITLE
Android 6 compatibility

### ISSUE THREAD

**Issue by caoli5288** [MathewSachin/Fate-Grand-Automata#28]
Some popular emulators still use older versions of android. :(

**Comment by MathewSachin** [comment]
I'd actually checked a few emulators before deciding the minimum Android version:

Bluestacks: 7.1.2
Nox: 7
MEmu Play: 7.1.2
LDPlayer: 7.1.2
Remix OS Player: 6 (no longer in development)
Genymotion: 10

Which emulator are you using? Try using any of the above (except Remix OS Player).

It would be pretty difficult to downgrade the Android version now.
