### ISSUE TITLE
App only works once per restart

### ISSUE THREAD

**Issue by Tom3kk** [MathewSachin/Fate-Grand-Automata#289]
The app works only once per device restart: 
Start app, enable accessibility, app works, close app, open app, asked to enable accessibility even if it is enabled, re-enabling does nothing - the only fix is to restart my phone - Xiaomi Redmi Nore 8 Pro.

**Comment by reconman** [comment]
see #213

**Comment by Tom3kk** [comment]
Did that, issue persists

**Comment by reconman** [comment]
What is the behavior after re-enabling accessibility? What does the app do when you try to start auto-battle?

**Comment by Tom3kk** [comment]
I can't try starting auto-battle, it tells me to enable accessibility

**Comment by MathewSachin** [comment]
I myself used a Xiaomi phone without any problems.
Are you sure you followed everything on https://dontkillmyapp.com/xiaomi?
i.e. AutoStart should be ON, Battery optimization should be OFF, app should be pinned

Also, try restarting your phone once more after that.

**Comment by MathewSachin** [comment]
Any luck? If all that doesn't work, you should be able to avoid phone restart by clearing cache for the app.

**Comment by MathewSachin** [comment]
I'm closing this since no response.
It's an MIUI specific thing for which nothing can be done in the app.
I've confirmed on my own old Xiaomi phone and with a few users on Gamepress having Xiaomi phones that following the steps on the website I linked are sufficient to remove the need for a restart.
If that doesn't work, you'll have to resort to clearing the cache for the app.

**Comment by Tom3kk** [comment]
Followed the guide as much as I could - I don't know how to access the settings in the 2nd and 3rd screenshot on the site.    
I cannot access battery manager and there is no autostart button within my security app...

**Comment by MathewSachin** [comment]
Post screenshots of the screen where you turned ON AutoStart for FGA (not Security app). Maybe there are more settings available.
Also, a screenshot of the Background Settings screen for FGA.

**Comment by sleeping-player** [comment]
> Followed the guide as much as I could - I don't know how to access the settings in the 2nd and 3rd screenshot on the site.    
> I cannot access battery manager and there is no autostart button within my security app...

Go per app setting. You can go here long-pressing FGA app icon. (App info)
There will be battery related setting. Go there.
And there will be four settings, enabled (MIUI) battery optimization.
Select no restriction. This will stop continuous asking accessabililty right.

As I am not using English set phone, noun will not match correctly. Please find your correct setting.

**Comment by Tom3kk** [comment]
> Go per app setting. You can go here long-pressing FGA app icon. (App info)
> There will be battery related setting. Go there.
> And there will be four settings, enabled (MIUI) battery optimization.
> Select no restriction. This will stop continuous asking accessabililty right.
Its already got no restriction selected, I enabled optimizations and disabled them just to make sure and the issue persists.

**Comment by Tom3kk** [comment]
> Post screenshots of the screen where you turned ON AutoStart for FGA (not Security app). Maybe there are more settings available.
> Also, a screenshot of the Background Settings screen for FGA.
My phone's not in english so I doubt it will be much help

**Comment by MathewSachin** [comment]
I know how to use Google Lens Translator

**Comment by MathewSachin** [comment]
These settings seem fine. Just posting here for anyone who looks at this issue later.

<img src="https://cdn.discordapp.com/attachments/744278573631799396/751400687589523486/Screenshot_2020-09-04-13-17-47-957_com.miui.securitycenter.jpg" width="300">
