### ISSUE TITLE
OpenCV Assertion Failed

### ISSUE THREAD

**Issue by Flynn1111** [MathewSachin/Fate-Grand-Automata#29]
I'm on an s10 plus, and I'm getting the attached error when trying to activate the script from within the FGO app itself when I hit play. I can hit play in other apps but when switching to FGO it does nothing.

Other info:
using auto AP, skill, preferred support (mona lisa), EN server. 
![Screenshot_20200419-225023_One UI Home](https://user-images.githubusercontent.com/63996363/79718502-0ee55200-8291-11ea-80a8-fe71bbe7dc30.jpg)

**Comment by MathewSachin** [comment]
Can you give me a screenshot of FGO running on your phone.
I need to know what part of the screen the game is using on your phone.

There's a known problem with Samsung phones discussed in #20.

**Comment by Flynn1111** [comment]
Sure, this was occurring with and without the fullscreen apps feature on.
![20200419_231043](https://user-images.githubusercontent.com/63996363/79719308-2291b800-8293-11ea-8a81-2f056602c2b3.jpg)

**Comment by MathewSachin** [comment]
Ok. I need to check this a bit. I'll get back to you ASAP.

**Comment by MathewSachin** [comment]
Portrait screenshot size is 1440x3040
Landscape screenshot size is 3021x1431
There is a difference in screenshot sizes, the width of the portrait one doesn't match the height of the landscape one.

Can you provide me screenshots of the game both when Fullscreen mode is ON and OFF?

**Comment by Flynn1111** [comment]
![Screenshot_20200420-004046_Fate_GO](https://user-images.githubusercontent.com/63996363/79726470-b5d0ea80-829f-11ea-8a90-51a623ef38fe.jpg)
![Screenshot_20200420-003936_Fate_GO](https://user-images.githubusercontent.com/63996363/79726477-b8cbdb00-829f-11ea-8b8e-21f6b5ad4541.jpg)


see attached, at time of upload they're both the 1440 ratio in each screenshot's details. not sure why the other one wasnt.

**Comment by reconman** [comment]
Do you have a hidden black notch bar on the left of the first screenshot?

**Comment by Flynn1111** [comment]
I have not hidden the notch in any screenshot, also I just learned thats called a notch.

**Comment by MathewSachin** [comment]
I've almost understood what the problem is. It seems to be exactly what is mentioned in #20.
I'll implement the option suggested in that issue and give you a build to test once I'm done.

**Comment by MathewSachin** [comment]
The mode to use will be the one in the first screenshot out of the two, the one with blue bars on sides.

**Comment by Flynn1111** [comment]
Okay that did it, I've got it working but only when the notch is hidden, it stops on the support selection when the notch is visible. (its set to select the first support)

**Comment by MathewSachin** [comment]
Are you able to download APK from this page: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/82668605

In that APK, go to `More settings` and turn ON `Ignore Notch calculations`.
Run the script in the mode of the first image again.

If you're not getting permission to download from that link, I'll give you a direct link.

**Comment by Flynn1111** [comment]
Something I've noted while running the script: it seems to be tapping the right side of skill buttons and things, and actually misses the np in the 4 slot.

my autoskill is:
abh4,#,gi6,#,df5

abh all work correctly, 4 is missed, then a 3rd card is tapped. after 2-3 turns it clears the first wave. gi works and 6 is fired off. df5 all do not ever trigger.

could this be related to the notch being hidden?

**Comment by Flynn1111** [comment]
That setting works, it now no longer misses NP4 when the notch is hidden and full-screen is on, it still seems to be ignoring the fact battle 3 begins and skipping ,#,df5 of abh4,#,gi6,#,df5 but that may be unrelated.

**Comment by MathewSachin** [comment]
That's auto-targetting feature which clicks on danger and servant enemies.
Try disabling it in `More options`.

**Comment by Flynn1111** [comment]
I changed the following settings:
Cast Noble Phantasm: Spam -> None
Auto Targeting Slider: On -> Off

it stopped the aforementioned taps but still no dice on the commands. I'll attempt a run with Cast NP set to Danger next.

**Comment by MathewSachin** [comment]
> ![Screenshot_20200420-004046_Fate_GO](https://user-images.githubusercontent.com/63996363/79726470-b5d0ea80-829f-11ea-8a90-51a623ef38fe.jpg)

That's pretty weird behaviour.
You were running in this mode, right?

**Comment by Flynn1111** [comment]
Yeah, I was running that mode. It was the 40ap QP node if thats useful info. Its late now, but in the morning I'm going to see if the unstable skip death mode helps at all, ill also see about getting a screen capture if possible.

**Comment by MathewSachin** [comment]
I don't think the unstable skip death mode will help here.
I'll need to think about what is causing the problem.

**Comment by MathewSachin** [comment]
When you try it tomorrow, try using this build: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/82771309
I've tweaked the image matching parameters a bit.

Also, please provide screenshots of the 3 battles, so that I can check them with the code.

**Comment by Flynn1111** [comment]
Everything appears to be working like a charm with the new apk.
![Screenshot_20200420-083509_Fate_GO](https://user-images.githubusercontent.com/63996363/79770582-78418100-82e2-11ea-8d66-51c7e13840cf.jpg)
![Screenshot_20200420-083609_Fate_GO](https://user-images.githubusercontent.com/63996363/79770586-7a0b4480-82e2-11ea-9bc9-e9abf57e8cc1.jpg)
![Screenshot_20200420-083655_Fate_GO](https://user-images.githubusercontent.com/63996363/79770589-7aa3db00-82e2-11ea-8896-aa71f887009a.jpg)

**Comment by MathewSachin** [comment]
That's great! Do let us know if you have any other issue.
