### ISSUE TITLE
Server auto change problem

### ISSUE THREAD

**Issue by kohcheeyit** [MathewSachin/Fate-Grand-Automata#291]
Every time click on the "play" button will auto change to JP server.
I tried at my emulator and phone, both also have this problem
[Video.zip](https://github.com/MathewSachin/Fate-Grand-Automata/files/5116676/Video.zip)

**Comment by reconman** [comment]
Which FGO versions do you have installed?

**Comment by kohcheeyit** [comment]
I think should be the latest one.

**Comment by kohcheeyit** [comment]
v0.20.0

**Comment by MathewSachin** [comment]
both JP and CN?

**Comment by kohcheeyit** [comment]
JP no problem since it change to JP , but others type cannot work

**Comment by reconman** [comment]
I said:
> Which FGO versions do you have installed?

FGO, not Fate Grand Automata.

**Comment by kohcheeyit** [comment]
> both JP and CN?

i mean i the version of this auto app

**Comment by kohcheeyit** [comment]
> I said:
> 
> > Which FGO versions do you have installed?
> 
> FGO, not Fate Grand Automata.

The latest version of JP and CN

**Comment by MathewSachin** [comment]
Ehh, it should automatically change to CN if you start it after launching FGO CN.

**Comment by kohcheeyit** [comment]
> Ehh, it should automatically change to CN if you start it after launching FGO CN.

when I run at CN will auto change to JP , so i need to jump out and change to CN during the running process

**Comment by reconman** [comment]
Is JP closed when you start CN?

**Comment by kohcheeyit** [comment]
yes, i separate JP in and CN in emulator and phone

**Comment by kohcheeyit** [comment]
I think is because it can't detect I kill the JP ,so after i kill the JP fgo and open CN will have this problem, 
Just now i reinstall the FGO automata ,try on CN not this issues, but after i open Jp and close it again the issues came back

**Comment by MathewSachin** [comment]
I think I kind of get the problem. Auto server detection might not have been working even in earlier releases for CN. But, in the latest release, I changed it to listen only for events from FGO packages. That's why JP stays cached.

For now, you can clear cache for the app from Android settings instead of reinstalling. I'll have to look more into the problem.

**Comment by MathewSachin** [comment]
@kohcheeyit can you confirm the package name of FGO CN you have installed?

Is it: `com.bilibili.fatego.sharejoy`

**Comment by kohcheeyit** [comment]
do u mean the apk name? apk name: FGO_v2.6.0_bili_290255.apk

**Comment by reconman** [comment]
The package name is hidden inside the apk file.

@MathewSachin it's com.bilibili.fatego

**Comment by MathewSachin** [comment]
oh, everywhere I checked, there was that sharejoy part at the end, which I thought was super weird. 😆

**Comment by MathewSachin** [comment]
@kohcheeyit check the APK from this page: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/221876457

**Comment by kohcheeyit** [comment]
> @kohcheeyit check the APK from this page: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/221876457

No problem problem ady
