### ISSUE TITLE
Swipe is not working on my phone

### ISSUE THREAD

**Issue by machina2020** [MathewSachin/Fate-Grand-Automata#294]
> MAKE SURE YOU TESTED THE LATEST RELEASE.

> Samsung user? See https://mathewsachin.github.io/Fate-Grand-Automata/SAMSUNG.html

**Describe the bug**
Include steps to reproduce the error if required

**Screenshots**
If an error occurred, you can find the message by expanding the app's notification.
It is recommended that you atleast add one screenshot of FGO running on your device.

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON (recording functionality is available within the app in `More options`).

**Device Info (please fill atleast 'Device model'):**
 - Device model: Samsung S7 Edge
 - Screen size: 1280x720
 - Android Version: Android 8.0
 - RAM: 4GB

My game is already on full screen but only swipe is not working when selecting the support servant. (works fine on emulator)

It stays there for a while till it press on refresh button and till a skadi shows up since i have her as preferred servant.

**Comment by reconman** [comment]
Next time, please replace the placeholders with actual content. For example, provide a video.

Try setting Fate/Grand Automata to fullscreen too.

**Comment by MathewSachin** [comment]
We ask those things in the bug template just to help you out faster.

Provide a video with debug mode ON.

**Comment by MathewSachin** [comment]
Closing since sufficient info wasn't provided and there wasn't a response. Reopen with proper info if the issue still happens.
