### ISSUE TITLE
Skill Misclicks on BlueStacks

### ISSUE THREAD

**Issue by SiftingSands** [MathewSachin/Fate-Grand-Automata#296]
Observed clicks were too far to the right on targetable skills. This includes both Mystic Code (Master Skills) and servant skills.

See the video below for illustration with DSS farming. All targetable skills on the first servant were mislocated.
[https://imgur.com/a/alUEvBs](https://imgur.com/a/alUEvBs)

Issue occurs on various 16:9 resolutions from 720p to 1440p. I have not tried portrait mode. Graphics engine is set to "Capability", and OpenGL is the renderer.

Let me know if you need more details from me, or if I can try something for further debugging.

**Comment by MathewSachin** [comment]
There is a skill confirmation setting in the app.
Since you have it turned ON for FGO, turn it ON in FGA too.

**Comment by SiftingSands** [comment]
That resolved the issue. I completely forgot about that setting. Thanks for the fast response and the app!
