### ISSUE TITLE
Not Working At All After 0.20.0 Update

### ISSUE THREAD

**Issue by MHXA** [MathewSachin/Fate-Grand-Automata#298]
**Describe the bug**
Not working both in NA and JP, no taping or swipe performed, already turn off notch calculation, fullscreen is activated and still not working, after 0.20.0 update

**Screenshots**
![Screenshot_20200825-200406_FateGO.jpg](https://user-images.githubusercontent.com/68960050/91177899-9abf2d00-e70e-11ea-8db4-7a923afe5cc9.jpg)

**Device Info (please fill atleast 'Device model'):**
 - Device model: SAMSUNG A20s (SM-A207F)
 - Screen size: 1506x720
 - Android Version: 10
 - RAM: 3GB

**Comment by MathewSachin** [comment]
Ok. Which version worked for you before?

Post a video with Debug mode ON,

**Comment by kaiyihuang** [comment]
https://youtu.be/6EGiokVz7bk

Not the OP, but here is one from a Samsung S9+. Looks like it's not scaling to the screen size

**Comment by MathewSachin** [comment]
@kaiyihuang read the docs.
https://mathewsachin.github.io/Fate-Grand-Automata/SAMSUNG.html

**Comment by MHXA** [comment]
@MathewSachin in 0.19.0 version

**Comment by MathewSachin** [comment]
Post a video with debug mode ON like @kaiyihuang did

**Comment by MathewSachin** [comment]
A user had to restart his phone after updating his Samsung phone to Android 10 (#278).

**Comment by MHXA** [comment]
@MathewSachin idk why but, it is worked now
