### ISSUE TITLE
Sub-folder structure for AutoSkill List

### ISSUE THREAD

**Issue by mingchungtsai** [MathewSachin/Fate-Grand-Automata#299]
As a user who saves many comps (and many raid ones for re-runs), the list for AutoSkill gets long quite fast.
I would like the option to group/subfolder list entries so as to:

- avoid scrolling and
- avoid unnecessarily long names due to prefixing/suffixing the entries (with purpose, comp, node name etc.) to make them unique

Not everyone can run generic DSS comps for everything after all :)

**Comment by MathewSachin** [comment]
The way settings are stored right now, sub-folders won't be possible.
Adding subfolders now would break existing configs which would be terrible.

If you're saving setups for reruns, why not Export and save them to folders on your device and delete them from the list.
You can have only 10 Parties at a time in FGO anyway.
And when the event comes back, import the setups back.

**Comment by mingchungtsai** [comment]
Ah that sounds good. I overlooked the export/import functionality. Thanks!
