### ISSUE TITLE
Run AccessibilityService in different process

### ISSUE THREAD

**Issue by MathewSachin** [MathewSachin/Fate-Grand-Automata#3]
Right now, if you kill the `MainActivity` by swiping the app from task list, then the process is killed.
The `AccessibilityService` running in the same process also gets killed.
But, the switch in the `Accessibility settings` still shows it as `ON`.
Next time you launch the app, you have to go to `Accessibility settings`, turn `OFF` the service and then turn it `ON` again.

The tradeoff with this bad experience is that it is simple to implement.
A `static` instance of the `AccessibilityService` can be used for communication.

This problem can be solved if we run the `AccessibilityService` in a different process.
But, communication with it will be a challenging task here. `Messenger IPC` looks the most promising here. There is also the problem with `SharedPreferences` not working across processes.

---

## I tried implementing this, but multiple processes were not working well. 
I'm dropping this for now.

**Comment by MathewSachin** [comment]
I've seen that AnkuLua occasionally asks for permission to modify system settings.
We might be able to do the same and restart the Accessibility service programmatically.
Not sure about it but it is something I need to investigate.

**Comment by reconman** [comment]
Ankulua most often uses its system setting permission to change the Screen Rotation Lock to off, which they need for some click operations, if I remember correctly.

**Comment by MathewSachin** [comment]
I always keep Screen Rotation Lock ON. But, I've never seen AnkuLua disable it though.

**Comment by reconman** [comment]
https://ankulua.boards.net/thread/1046/dragdrop-enables-screen-rotation
