### ISSUE TITLE
Build/developing "get started" guide?

### ISSUE THREAD

**Issue by the3dsandwich** [MathewSachin/Fate-Grand-Automata#300]
Hi, it's me again.

I'm wondering if we can make a "get started" guide for developing FGA since I don't see one anywhere. I think this may help if other people want to help develop but don't know where to start after forking this repository (like me).

I can help if you're interested.

Thanks for this app as always!

**Comment by MathewSachin** [comment]
To build the project, the latest version of [Android Studio](https://developer.android.com/studio) alone is sufficient.
I started making the project when I didn't know much about Android, so it isn't architected well.
Even right now I'm slowly improving the code-base.

Let me still give you a general idea.

There are 4 modules in the app right now:
1. libautomata
    The heart of the app, which is independent of Android and has all the methods we need to write scripts.
    Android implementation is dependency injected here.
2. scripts
    The FGO scripts. You don't really need to know about Android to write scripts here.
3. prefs
    This is Android-specific and implements preferences (storing/retrieving settings).
4. app
    The Android part of the app which includes the UI, MediaProjection (used for screenshots), AccessibilityService (used for swipes and clicks).

Overall, it is quite complex. The best point to start will be from `scripts` module where you don't need to learn anything about Android.

For learning Kotlin, I found [Kotlin Koans](https://play.kotlinlang.org/koans/overview) really interesting.

**Comment by the3dsandwich** [comment]
Ah, thanks! I'll... look over there then.
