### ISSUE TITLE
Auto Gift Box for lottery

### ISSUE THREAD

**Issue by DottedGlass** [MathewSachin/Fate-Grand-Automata#302]
With Gilfest coming up and other lottos in near future, it would be great if we could implement this feature from fgo_lua

https://github.com/29988122/Fate-Grand-Order_Lua/pull/293

**Comment by MathewSachin** [comment]
Duplicate of #6 
We don't have text recognition implemented in the app. And my present box is empty so I won't be able to test it even if I do implement it right now.
