### ISSUE TITLE
Not Working Again

### ISSUE THREAD

**Issue by MHXA** [MathewSachin/Fate-Grand-Automata#305]
BUG
The problem is no action performed when i play the script.

Video
https://youtu.be/NEd-cdG2muQ

My Device
 - Device model: SAMSUNG A20s (SM-A207F)
 - Screen size: 1506x720
 - Android Version: 10
 - RAM: 3GB

**Comment by MathewSachin** [comment]
The regions detected are also wrong. First, turn OFF `Ignore notch calculation`.
Then clear cache for the app from Android app settings and try again.

**Comment by MathewSachin** [comment]
Also, look at this: https://dontkillmyapp.com/samsung
To prevent app from being killed by Samsung's battery saver, follow the steps in that link.

**Comment by MHXA** [comment]
I'll try

**Comment by MHXA** [comment]
Still not working

**Comment by MHXA** [comment]
@MathewSachin Hey!, are you there?

**Comment by MathewSachin** [comment]
I'm here. I can't think of any more things you can try. We have a lot of Samsung users but none had the same problem.
