### ISSUE TITLE
Option to start service on app load

### ISSUE THREAD

**Issue by buitim** [MathewSachin/Fate-Grand-Automata#306]
Hi again! Loving all the new features being added. Would it be possible to have an option to start the FGA service upon starting up the app? I was thinking of something similar to how Ankulua handles their `Automatically Start Service` function in their settings where it would be an opt-in opposed to being enabled by default.

**Comment by MathewSachin** [comment]
I don't know why I didn't add this option before.

If you want to check it, test APK is available on this page: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/227422705

**Comment by buitim** [comment]
Damn that was fast. Works well for me! Thanks a ton for the quick addition! 🙏

I dig the new floating button as well. Much better from a usability perspective
