### ISSUE TITLE
AutoSupport scrolls too far

### ISSUE THREAD

**Issue by reconman** [MathewSachin/Fate-Grand-Automata#31]
On my device, the AutoSupport script scrolls too far when no Event Bonus filters are set.

The script will scroll 2 1/2 entries, so it goes from this:
![](https://dl3.pushbulletusercontent.com/FP5xj73mSEBpFzwWa7mtAoFIcn34eWKD/Screenshot_20200420-131034.jpg)

To this:
![](https://dl3.pushbulletusercontent.com/Y09Z8w3sWFEXv9TYSLMFeS42r4Mae9Jx/Screenshot_20200420-131042.jpg)

The amount of scrolling should be reduced, so the 3rd entry is fully shown once.

**Comment by MathewSachin** [comment]
https://github.com/MathewSachin/Fate-Grand-Automata/blob/9f0f62a4bb849a9b753bd73ab857104075c6f0ab/FateGrandAutomata/AndroidImpl.cs#L38

I think we don't have to change the amount of scrolling. We can keep it same as FGO-Lua.
What we need to do is increase the `duration` value in the above code.

**Comment by reconman** [comment]
Could be, yeah

**Comment by MathewSachin** [comment]
On some investigation, it seems that I'd have to change the gesture to swipe and hold for precision.
