### ISSUE TITLE
After few hours accessibility is disabled even though it was on

### ISSUE THREAD

**Issue by dyan458** [MathewSachin/Fate-Grand-Automata#311]
Hi at first the app was running perfectly. Then few hours later it stopped working telling me that android accessibility was been disabled even though i repeatedly turned it on and off.
Here are the sample screenshots since phone cannot upload video here

 Thanks

 - Device model: Xiaomi Redmi Note 8 Pro
 - Screen size: 1080x2340
- MIUI12
 - Android Version: Android 10
 - RAM: 6GB

|   |   |   |
|--|--|--|
| <img width="200" src="https://user-images.githubusercontent.com/70352471/91505300-da9a3600-e901-11ea-8fb7-9a5734163b7d.jpg"> | <img width="200" src="https://user-images.githubusercontent.com/70352471/91505516-598f6e80-e902-11ea-96a4-a1eae42492cd.jpg"> | <img width="200" src="https://user-images.githubusercontent.com/70352471/91505521-5b593200-e902-11ea-8be1-9ffdaf1b375f.jpg"> |
| <img width="200" src="https://user-images.githubusercontent.com/70352471/91505522-5bf1c880-e902-11ea-8fde-2737c87148d3.jpg"> | <img width="200" src="https://user-images.githubusercontent.com/70352471/91505525-5d22f580-e902-11ea-9a7d-39633d5ee8c8.jpg">|<img width="200" src="https://user-images.githubusercontent.com/70352471/91505557-73c94c80-e902-11ea-8cce-758c61a7716d.jpg"> |

**Comment by MathewSachin** [comment]
It's just the app getting killed by MIUI's battery optimization stuff. See https://dontkillmyapp.com/xiaomi for workarounds.

**Comment by MathewSachin** [comment]
Closing in favour of #314
