### ISSUE TITLE
FAQ: Keeps asking for Accessibility

### ISSUE THREAD

**Issue by MathewSachin** [MathewSachin/Fate-Grand-Automata#314]
Don't blame me for this. Blame the shitty battery optimizations added by phone manufacturers which kill Accessibility Services. This problem happens with every app that uses Accessibility in some way or another. You can check reviews for popular apps on Play Store that use Accessibility and see the same issues.

I'll collect all the info I have about the problem here, please don't open multiple issues and bother me.
I'd rather work on features and bugs which are related to the app.

See if your phone manufacturer is listed on this website: https://dontkillmyapp.com/
Follow the steps for your phone correctly. I've had cases of people complaining after not properly following those instructions.
Especially the Xaomi and Samsung users, I have personally confirmed on my phone and a few folks from Gamepress.

After you've done that clear the cache for FGA.
If it still doesn't work, you might have to restart your phone once.

**Comment by Unumbium** [comment]
For xiaomi users having that problem, just lock the app so you don't close it by accident.

**Comment by Soulsuke** [comment]
Xiaomi fix for accessibility service stopping when closing the app: also enable permissions for FGA in settings -> apps permissions -> background autostart.

**Comment by squall835** [comment]
> Xiaomi fix for accessibility service stopping when closing the app: also enable permissions for FGA in settings -> apps permissions -> background autostart.

Did all of that and still doesnt work, Android 15 Xiaomi Redmi 14C

**Comment by mooncellarchbury** [comment]
我在mumu模拟器里面使用的时候，在设置中开启了后台挂机时保活运行后就无法使用。关闭后就行了。原因是这个功能会阻碍悬浮球类的脚本运行，有看到的兄弟可以注意一下这个点
