### ISSUE TITLE
Tends to Stop in Subsequent Repetitions

### ISSUE THREAD

**Issue by Flynn1111** [MathewSachin/Fate-Grand-Automata#33]
Hello again!

When running the script, still farming the 40ap QP node it runs the first full quest flawlessly. It'll refill, pick the node again, pick support again and start the quest without fail. It then will fail any time after the first skill activates. I've had it fail as early as the first repetition (so 2nd quest) after activating the first skill. I've also had it not fail for about 5 runs on the high end. Stopping the script by tapping play and restarting it in between runs doesn't seem to help.

When "failing" the application will stop executing commands, the play button will disappear and the app will say the "Accessibility Service Running" message like on first start up. I then have to tab over to the automata app and toggle the application off and on again, then it functions as above before failing again.

**Comment by MathewSachin** [comment]
I'm not sure, maybe the app being killed by Samsung's battery optimization. I'd a similar problem with my Xiaomi phone and solved it by setting unrestricted in battery saver.

For Samsung, the steps to follow can be checked here: https://dontkillmyapp.com/samsung

**Comment by Flynn1111** [comment]
I'll give that a try. There was some kind of prompt when first configuring the app to turn off those battery settings which I did but I've now turned that feature off system wide.

**Comment by Flynn1111** [comment]
I've followed the instructions and disabled the system wide setting. This did not fix the issue. I am unable to add the automata app to the "Apps that won't be put to sleep" list since it doesn't appear in the list.

**Comment by reconman** [comment]
After it crashes, do you see anything like this in the list of accessibility services?

<img src="https://www.xda-developers.com/files/2018/06/Android_P_Accessibility_Services_Not_Working_1.jpg" height="700px" />

**Comment by Flynn1111** [comment]
Accessibility on the S10 looks different but nothing would suggest a feature isn't working within those menus. Its more like the service gets toggled off while I'm in FGO as opposed to the whole automata app crashing.
![Screenshot_20200420-141709_Settings](https://user-images.githubusercontent.com/63996363/79800776-b5713780-8311-11ea-9d5c-f9f6834a638a.jpg)
![Screenshot_20200420-141714_Settings](https://user-images.githubusercontent.com/63996363/79800787-b86c2800-8311-11ea-95f4-d8889023149a.jpg)

**Comment by reconman** [comment]
"Apps that won't be put to sleep" doesn't exist in the screenshots on dontkillmyapp.com. Do you mean "Sleeping apps"? Those are the apps where you're not allowing it to run in the background.

I have one last idea, can you try "locking" the automata app in the task manager?

**Comment by Flynn1111** [comment]
The whole Device Health screen is different from the link provided earlier. Attached is what I'm looking at, Automata doesn't show up in the list of app for any of the sleep or don't sleep sections. I'll try locking it now.

!
![Screenshot_20200420-143443_Device care](https://user-images.githubusercontent.com/63996363/79802267-801a1900-8314-11ea-95d3-cec15cdf4239.jpg)
[Screenshot_20200420-143539_Device care](https://user-images.githubusercontent.com/63996363/79802254-7db7bf00-8314-11ea-8fd5-915210cf3557.jpg)
![Screenshot_20200420-143533_Device care](https://user-images.githubusercontent.com/63996363/79802258-7e505580-8314-11ea-9bcc-3a3f0e8c4a87.jpg)
![Screenshot_20200420-143524_Device care](https://user-images.githubusercontent.com/63996363/79802262-7ee8ec00-8314-11ea-8e58-eaf91efcaf25.jpg)
![Screenshot_20200420-143518_Device care](https://user-images.githubusercontent.com/63996363/79802264-7f818280-8314-11ea-8570-c6c0d8c28804.jpg)

**Comment by Flynn1111** [comment]
Last screenshot didn't upload 
![Screenshot_20200420-143539_Device care](https://user-images.githubusercontent.com/63996363/79802482-dedf9280-8314-11ea-9e83-79ac1fc5f90e.jpg)

**Comment by reconman** [comment]
So the + in the last screenshot doesn't show automata? Also if you don't mind I'll scale down your images.

**Comment by Flynn1111** [comment]
Correct, it shows an alphabetized list of apps but Automata isn't on that list anywhere.

**Comment by reconman** [comment]
One more option, if you go to the details of the app and then click on the energy settings, what does it say?

For example, on my phone this app is currently set to have a battery optimization of "Intelligent". I haven't noticed any bad effects of that setting.

**Comment by Flynn1111** [comment]
I'll give that a go, it looks like Automata was set to "not optimized" which greys out the "allow background activity" slider. Optimizing says it'll restrict battery usage but it allows me to turn the "allow background activity" slider on so I'll see if it changes anything. 

Locking the automata app had no impact.

**Comment by Flynn1111** [comment]
It seems to be lasting marginally longer before toggling off while it's optimized and and set to "allow background activity" but it may be placebo effect.

**Comment by Flynn1111** [comment]
So after finishing up some QP farming I decided to test out the app auto attacking with buster servants. I turned off autoskill and turned on auto target, then I set it to farm for 2 refills on a 14ap node. With autoskill turned off and no other changes to battery settings it farmed the entire 3 ap bars worth without stopping.

**Comment by DLZRR** [comment]
I have the exact same problem as the original post. I have a Xiaomi A2, Android 10 and I have added both FGO and the Automata app to apps that are not optimized in the Battery settings (only thing I found I could change), but the play button disappears  after finishing one quest and starting the new one, right when it has chosen the first skill, just like Flyn1111. Only thing I have to add is that FGO seems to lag a lot after it just chose the first skill, and then Automata seems to disappear.

**Comment by MathewSachin** [comment]
We've done a few performance improvements and want to confirm with a few more users before releasing a new version.

You can download the APK from this page: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/84478986
It'll be in a zipped folder.

@Flynn1111 @DLZRR  Please, let me know if the app works fine now or not.

**Comment by DLZRR** [comment]
@MathewSachin it seems to work for me now! Three consecutive runs were done successfully. I do have to mention that I turned off skill confirmation for FGO (and for Automata), so maybe I will try testing if it still works if I turn it back on. Thanks!

**Comment by Flynn1111** [comment]
yeah I let it run for ~1hr of qp farming and no more stopping.

**Comment by MathewSachin** [comment]
So, this fixes the crashing issues for almost everyone who reported.
@reconman I'll do the release in about an hour.
