### ISSUE TITLE
Bottom right corner isn't detected

### ISSUE THREAD

**Issue by Somastro** [MathewSachin/Fate-Grand-Automata#337]
When using the app on a Google Pixel 4 XL, the detection regions seem to be off as it won't battle or select support. I have tried the app on my old phone (Pixel 2 XL) and it works fine on that. 
![Screenshot_20200830-021831](https://user-images.githubusercontent.com/70457070/91649081-9f197c00-ea67-11ea-8cff-d22f0dc5c817.png)

**Device Info **
 - Device model: Google Pixel 4 XL
 - Screen size: 1440 x 3040
 - Android Version: Android 10
 - RAM: 6GB

**Comment by tchofy** [comment]
Let's see if I'll get it right this time. This looks like what happened on #313, so changing the settings to make fgo run on full screen should fix it. Try the instructions on the link bellow, some steps might be a bit different:

https://github.com/MathewSachin/Fate-Grand-Automata/issues/313#issuecomment-682307387

**Comment by MathewSachin** [comment]
Can also be #250. The workaround was to turn off Android gestures.

**Comment by MathewSachin** [comment]
Closing since no response.
It's not really related to the app, but to the phone having those black borders around FGO.
You'll have to somehow get rid of them from your phone's settings.
