### ISSUE TITLE
Note 20 Ultra Screen detection

### ISSUE THREAD

**Issue by ScathachSkadi** [MathewSachin/Fate-Grand-Automata#342]
> MAKE SURE YOU TESTED THE LATEST RELEASE.

> Samsung user? See https://mathewsachin.github.io/Fate-Grand-Automata/SAMSUNG.html

**Describe the bug**
Skill command:
d1g1l14,#,f14,#,i1ehj1

On Note 20 Ultra it won't use the skill on the 2nd round and press the attack button. Toggled the notch settings a few times but no luck.

**Screenshots**
If an error occurred, you can find the message by expanding the app's notification.
It is recommended that you atleast add one screenshot of FGO running on your device.

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON (recording functionality is available within the app in `More options`).

**Device Info (please fill atleast 'Device model'):**
 - Device model: [e.g. Note20 Ultra]
 - Screen size: [FHD+]
 - Android Version: [e.g. Android 10]
 - RAM: [12GB]

**Comment by MathewSachin** [comment]
Edit this part in the issue:

```
Screenshots
If applicable, add screenshots to help explain your problem.
If an error occurred, you can find the message by expanding the app's notification.
It is recommended that you atleast add one screenshot of FGO running on your device.

Video
If relevant, include a video of the script running on your device with Debug mode ON (recording functionality is available within the app in More options).
```

**Comment by MathewSachin** [comment]
I need a video with debug mode ON, otherwise I can't see what's happening on your phone.

**Comment by ScathachSkadi** [comment]
This is actually a report from some users from the Korean community, all using Note 20s and I did ask them to post the video with the app running in debug mode. No one really took a video. However, I did think it's because the hole punch got smaller on the Note 20. Sorry to keep you waiting and I will give you an update if they post a video.

**Comment by ScathachSkadi** [comment]
Yes. They said it didn't really help.

**Comment by MathewSachin** [comment]
No point in keeping this issue without proper info. Reopen if you're able to get a video with debug mode ON.
