### ISSUE TITLE
Script doesn't continue after one run.

### ISSUE THREAD

**Issue by Haxedftw** [MathewSachin/Fate-Grand-Automata#346]
I'm a new user who recently discovered this app and decided to try it out. After one successful run, the app takes me back to the support menu where it will just sit there not picking a support. If I click on a support myself then the script picks back up as is if nothing was wrong.

Here's a screenshot of my settings http://imgur.com/a/yurQYvr

 - Device model: Huawei + Harman Kardon MediaPad M3 8.0 Octa Core 8.4
 - Screen size: 2560 x 1600
 - Android Version: 7.0
 - RAM: 4.0 GB

**Comment by reconman** [comment]
Please provide a video in debug mode using the app's recorder function as indicated by the bug template.

**Comment by Haxedftw** [comment]
https://youtu.be/U-kvjm0mSCA
Took forever to upload and sorry for the sideways video. I recorded it horizontal.

**Comment by MathewSachin** [comment]
The script checks the top-left corner of the screen to detect support screen.
In your case, there's definitely some other overlay there, even other than the recorder.
Get rid of that and it'll work.

<img src="https://user-images.githubusercontent.com/10654537/91797390-0f7af580-ec40-11ea-837c-424f9be2aeeb.jpg" width="300">

**Comment by MathewSachin** [comment]
Closing this issue since this was not a problem with the script/app itself but an overlay the user had.
