### ISSUE TITLE
Failed to determine card type region

### ISSUE THREAD

**Issue by ScathachSkadi** [MathewSachin/Fate-Grand-Automata#347]
> MAKE SURE YOU TESTED THE LATEST RELEASE.

> Samsung user? See https://mathewsachin.github.io/Fate-Grand-Automata/SAMSUNG.html

**Describe the bug**
The app doesn't recognize the attack button it seems? It won't tap anything and it will say "failed to determine card type region"

**Screenshots**
One of them is a gif instead of a video. Debug mode on.

https://ibb.co/xqPTG9b
https://ibb.co/X79fxkv
https://ibb.co/DY4Wr0y
https://ibb.co/nwQgDmW

**Video**

**Device Info (please fill atleast 'Device model'):**
 - Device model: [e.g. Galaxy S10]
 - Screen size: [e.g. WQHD+]
 - Android Version: [e.g. Android 7.1]
 - RAM: [e.g. 3GB]

Don't think there was any other overlay. And this guy tried both the notch settings on and off with the full screen setting on.

**Comment by MathewSachin** [comment]
The regions detected are wrong.
IIRC, for S10 you only need to make FGO full screen and turn ON `Ignore notch calculation`.

Can you ask them to try making FGA full screen too to get rid of those Android Navigation buttons below FGA.
And, I'm pretty sure it should be Android 9/10 and not 7.1.

**Comment by ScathachSkadi** [comment]
Oops sorry for the Android version and the RAM didn't really know what he was using though. Should have made that blank. Will talk to the guy and I'll comment again when I get a reply.

**Comment by ScathachSkadi** [comment]
He turned the full screen settings on for both the FGO and FGA app and he had the ignore notch calculation setting on. It didn't work. 🤔

**Comment by MathewSachin** [comment]
Hey, would you mind asking people who use FGA on S10 on the [thread on Gamepress](https://community.gamepress.gg/t/automatic-farming-app-fate-grand-automata/72155)?
I think there were some S10 users there.

They might be able to help. I personally don't use a Samsung phone.

**Comment by ScathachSkadi** [comment]
Ok thanks

**Comment by MathewSachin** [comment]
I had a few similar cases with Huawei users. The similarity is the app is able yo detect things, but not able to click. They solved it by turning off battery optimization and stuff for the app.
So, can you tell them to try the things on https://dontkillmyapp.com/samsung for FGA. But, I think that page isn't available in Korean

**Comment by ScathachSkadi** [comment]
It seems like S20 users have to turn on the notch settings to make the script run properly while S10 and Note 20 users have to have the settings off. I don't remember for Note 10 users. I am not sure what is wrong but most of the time it seems like the problem gets solved after toggling the notch settings on and off if one of them doesn't work. The "useful for Samsung phones" is making things confusing. You might want to consider changing it to "might be useful for Samsung phones".

**Comment by ScathachSkadi** [comment]
And also, yes some of them reporter that it works after a reboot for some reason.

**Comment by MathewSachin** [comment]
Everything can't be documented in the app. That's why we have a page for Samsung instructions: https://mathewsachin.github.io/Fate-Grand-Automata/SAMSUNG.html 

I mean if it already works, why turn ON another setting and then say it doesn't work 🤣 

The need to restart is due to FGA being killed by the battery optimization.

I think we need a general troubleshooting guide but I'm too lazy to write documentation.

**Comment by ScathachSkadi** [comment]
Might as well translate the whole page to other languages XD

But nowadays people are helping each other out so there's less work for me. Will tell them about the battery optimization.

**Comment by minhducsun2002** [comment]
Having the same issue here.
However
- it only occurs once in a while, kinda hard to capture
- it says `Failed to determine card type {1, 2, 3, 4, 5}` instead

For reference, my device is Redmi 6, 1440x720 screen, 3GB of RAM, and running on Android 10. No, I do not use MIUI.

**Comment by MathewSachin** [comment]
@minhducsun2002 lul. It's different. According to this issue the app doesn't work at all. The title is a bit misleading. But in your case, IIRC, it should just be due to lags.

**Comment by MathewSachin** [comment]
This was solved, right? @ScathachSkadi 
Since this is pretty much the same Samsung issue

**Comment by ScathachSkadi** [comment]
Yup didnt hear anything after this. Closing issue.
