### ISSUE TITLE
The first support is not captured (Support Image Maker)

### ISSUE THREAD

**Issue by AlfredPaguio** [MathewSachin/Fate-Grand-Automata#351]
> MAKE SURE YOU TESTED THE LATEST RELEASE.

Always has been 🔫

**Describe the bug**
[NA] You can see that the second one is selected and the first one is not
Kinda similar to my jp one #124 but it's support image maker now not battle mode (the battle mode is fixed both na and jp , I tested it over and over)

**Screenshots**
![Screenshot_2020-09-03-23-31-45-741_com aniplex fategrandorder en](https://user-images.githubusercontent.com/25319699/92140185-5d138000-ee43-11ea-9445-5b1ae6859e87.jpg)

**Device Info:**
 - Device model: Xiaomi Redmi Note 7
 - Screen size: 1080 x 2340

**Comment by MathewSachin** [comment]
You're right. Support Image Maker is indeed acting weird.

It's detecting the first support but ignoring the second one for me.

![Screenshot_2020-09-0](https://user-images.githubusercontent.com/10654537/92142158-0b61fa00-ee31-11ea-9ab8-2a5b4ccbd5ac.jpg)

It isn't consistent either. Sometimes it detects both, sometimes detects only one.

![Screenshot_2020-09-03-21-57-46-82_577bcc70c040536a6d306ef99c704547](https://user-images.githubusercontent.com/10654537/92142228-22a0e780-ee31-11ea-8a3c-0854350326b9.jpg)
![Screenshot_2020-09-03-21-57-51-57_577bcc70c040536a6d306ef99c704547](https://user-images.githubusercontent.com/10654537/92142236-25034180-ee31-11ea-851a-60d7b757da3d.jpg)

I'll take a look.

**Comment by MathewSachin** [comment]
Found the bug and fixed. Thank you for reporting!

@reconman remember changing that `for` loop which terminated after `2` selected supports to `take(2)`.
We should have done the bounds check before that.
The third support was getting more similarity than the above one but left out by the bounds check.

**Comment by reconman** [comment]
Got it.
