### ISSUE TITLE
Worked fine on first attempt, rest keep failing

### ISSUE THREAD

**Issue by runelt99** [MathewSachin/Fate-Grand-Automata#354]
![Screenshot_20200904_144624_com android settings](https://user-images.githubusercontent.com/48949150/92236430-131bb000-eebe-11ea-9596-ae9ee14dca79.jpg)
![Screenshot_20200904_144645_com android settings](https://user-images.githubusercontent.com/48949150/92236436-144cdd00-eebe-11ea-9298-1443b95d957d.jpg)

I hope these screenshots are enough for my phone specs. The other picture shows the display->more screen options->show full screen (its in Lithuanian so i hope language isn't going to be an issue).

As i looked at other people in youtube comment section i tried to use the full screen method but was unable. Googling about it shows that nobody else has this problem as they have the apps in the list.

**Comment by reconman** [comment]
Please create a bug report instead and fill in the template that will appear.

**Comment by MathewSachin** [comment]
It's not clear when/what it is failing?
The accessibility service or the second battle?
Include that too in the new issue.

**Comment by MathewSachin** [comment]
Also take a look at #346

**Comment by runelt99** [comment]
The problem is that this is not exactly a bug, but that i have no idea how to force it to be full screen. No the problem is not second battle, it gets stuck the moment it is run in the support list. I tried looking at Settings -> Apps on fgo but it doesn't have any option to force it to be full screen...

**Comment by MathewSachin** [comment]
Why not post an image of where it stops then?
Or a video with debug mode ON?

**Comment by sleeping-player** [comment]
> The problem is that this is not exactly a bug, but that i have no idea how to force it to be full screen. No the problem is not second battle, it gets stuck the moment it is run in the support list. I tried looking at Settings -> Apps on fgo but it doesn't have any option to force it to be full screen...

For Samsung, full screen option is not in per app setting. It is in display setting on phone setting.
Huawei setting tree will be different, but it could be in phone setting.

**Comment by sleeping-player** [comment]
> > The problem is that this is not exactly a bug, but that i have no idea how to force it to be full screen. No the problem is not second battle, it gets stuck the moment it is run in the support list. I tried looking at Settings -> Apps on fgo but it doesn't have any option to force it to be full screen...
> 
> For Samsung, full screen option is not in per app setting. It is in display setting on phone setting.
> Huawei setting tree will be different, but it could be in phone setting.

Oh that setting does not have FGO app.. sorry.
Maybe game controlling app from phone manufacturers can handle this option.

**Comment by runelt99** [comment]
> Why not post an image of where it stops then?
> Or a video with debug mode ON?

How do I upload video here? Last time I used discord to transfer photos to pc and upload it. Logged in here via phone yet still don't see how to upload it... 

Just shows the file here but after a sec it disappears

**Comment by MathewSachin** [comment]
Upload to YouTube and post the link here

**Comment by reconman** [comment]
or streamable.com

**Comment by runelt99** [comment]
https://youtu.be/HRlMrPBAZ4w

**Comment by MathewSachin** [comment]
It's already full-screen.
I'll guess it's just Huawei's battery saver messing up the app.

Try https://dontkillmyapp.com/huawei. Restart your phone after you do these.

One of the users on Gamepress says clearing the cache for the app solves the problem.

But, there's #259 which we weren't able to solve. They had to delete FGA's data every time.

**Comment by runelt99** [comment]
I FOUND IT! Looked thru Settings -> Battery -> found fgo and this app, made it manual instead of automatic, and i don't know if it helped, but i also noticed your app was still on - so i forced it to stop.

**Comment by MathewSachin** [comment]
I'm not sure, was your issue solved?

**Comment by runelt99** [comment]
Yes it was solved. Just burned through a bunch of silver apples. Thanks alot.
