### ISSUE TITLE
Hei! It's Me Again MHXA

### ISSUE THREAD

**Issue by MHXA** [MathewSachin/Fate-Grand-Automata#355]
The scripts stop in support screen.
My support:
![Screenshot_20200904-192721_FateGrand Automata.jpg](https://user-images.githubusercontent.com/68960050/92239148-b7185200-eee4-11ea-8f1f-d40e46b9a98f.jpg)

**Comment by MathewSachin** [comment]
I thought it already didn't work for you (#305) 🤔

**Comment by MHXA** [comment]
I don't know, but went i turn off the camera cutout it work very well, still sometime i need to restart my phone to make it working, but now the script is stoped working in support screen

**Comment by MathewSachin** [comment]
Why didn't you close that issue then?

**Comment by MathewSachin** [comment]
Also, post a video with Debug Mode ON of the script stopping. Just that screenshot doesn't tell me much.

**Comment by MathewSachin** [comment]
Also, when you open an issue, put a relevant title, fill in proper details, or the bot will close your issues again and we might not even notice,

**Comment by MHXA** [comment]
Sory, i forgot it, cause im thinking why the app not working properly after update, so i try to change my phone settings to make the app working again, then i tried to turn off the camera cutout and it work, but i dont know why, the script is stopped at the support screen

**Comment by MHXA** [comment]
Here's the video
https://youtu.be/wJSXcDeTFug

**Comment by MathewSachin** [comment]
Looks like your phone is lagging really bad when selecting the support class. That causes the first servant click to miss.
It'll try again in 10s in such cases after still. Can you post a video of it after waiting for around 15s after Support Class is selected to see if that happens?
I'll tweak some delays according to the video you post next.

**Comment by MHXA** [comment]
There's no problem with the lag before, but now the script always change the support to caster and waver

**Comment by MathewSachin** [comment]
Yeah, you've set it to Caster and First. So, what's the problem if it selects Waver?

**Comment by MHXA** [comment]
But i set it to saber before

**Comment by MHXA** [comment]
I think i will findout the problem by myself, and i will ask you again when i have serious problem
