### ISSUE TITLE
Free 10x FP Summon isn't detected

### ISSUE THREAD

**Issue by the3dsandwich** [MathewSachin/Fate-Grand-Automata#358]
**Describe the bug**
Friend point summon won't detect the free daily 10 summon and will keep swiping right to switch banners instead of trigging `first10SummonClick.click()`. I believe it's the checks in `scripts/entrypoints/AutoFriendGacha.kt` `isInFriendPtsSummon()` where`friend_summon.png` <img width="13" alt="friend_summon" src="https://user-images.githubusercontent.com/32169552/92318645-d7115800-f041-11ea-9568-070fe2fa9c33.png">
 isn't present in the first free 10 summon screen.

**Screenshots**
(borrowed from the official website, but they should look the same across servers. There is no friend support handshake icon below the summon button)
![](https://fate-go.us/manga_fgo/images/comic04/lecture04.png)

**Comment by MathewSachin** [comment]
See #280 for more info on this

**Comment by the3dsandwich** [comment]
Ah, I see. Thanks!

**Comment by MathewSachin** [comment]
Right now I can't think of a way to detect the free summon other than including images from all servers which I'd rather avoid.
