### ISSUE TITLE
App says no preferred servant or CE is configured when no Autoskill configurations are set

### ISSUE THREAD

**Issue by ARFearKubrick** [MathewSachin/Fate-Grand-Automata#36]
Even if i put the app to choose the first servant it doesn't choose it so i can't start battles automaticly. Also, even if I choose the servant I have to tap the start button because the app doesn't do it.
phone’s model number: SM-A520F
Android version: 7.0
NA 
Support Setings:
Ascension settings: ON
Spiritron Costume settings: OFF
Message Display: ON
No blacklisted users

![](https://cdn.discordapp.com/attachments/417407749450629120/702047208463401030/Screenshot_20200421-084352.png)

**Comment by MathewSachin** [comment]
Oh, actually the place where you've placed the play button is where the script checks the screenshot for recognizing support screen. Move it to somewhere else by dragging, I usually put it at bottom-left.

**Comment by reconman** [comment]
I didn't even notice that the play button is usually included in the screenshot.

**Comment by josumakina** [comment]
Well, now it sends an error message saying "Script Exited: When using preferred suport selection mode, specify at least one servant  or craft essence." but I have put in preferred Waver and Chaldean Lunchtime.

**Comment by josumakina** [comment]
![](https://cdn.discordapp.com/attachments/417407749450629120/702050886154977380/Screenshot_20200421-085905.jpg)

**Comment by MathewSachin** [comment]
Are you using Autoskill too?
Right now if you're using autoskill, support selection doesn't fallback to the ones set in Support menu but only uses the ones set in Autoskill configuration.
This is a bug and I'll push a fix for this soon.

Unrelated, but, don't use the same mode for Fallback, set it to either Manual or First.

**Comment by josumakina** [comment]
Thanks, now it works perfectly.

**Comment by josumakina** [comment]
Actually, I thinks the app guides more by the craft essence than by the servant, because it actually picked merlin instead of Waver a couple of times.

**Comment by reconman** [comment]
@josumakina can you share your autoskill configuration entry? I'm talking about the screen with Name, Skill Command and other things on it.

**Comment by josumakina** [comment]
![](https://cdn.discordapp.com/attachments/417407749450629120/702085401589841980/Screenshot_20200421-111615.jpg)

**Comment by reconman** [comment]
And what are your settings in the "Support" settings screen?

**Comment by josumakina** [comment]
The same that I putted above, I only changed the fallback to "first", the swipes to 4 and the maximun updates to 30.

**Comment by reconman** [comment]
Hmm, strange. normally the script should ONLY select Waver, but it currently treats your settings like the preferred servant is not set.

**Comment by josumakina** [comment]
Usually misses Merin but there is certain times (not a lot) that chooses it with chaldea lunchtime. Not happened whith any other servant.

**Comment by reconman** [comment]
@josumakina I just noticed, you're using a Samsung device, right? We'll have a bugfix for that soon with some general info about how to get the app working on Samsung devices.

**Comment by ARFearKubrick** [comment]
It choosed Merlin again, and this time I think the app was going to choose the right waver, it missed and choosed Merlin instead, and with 2030.

**Comment by ARFearKubrick** [comment]
Yeah, it misses, it almost starts the battle with tamamo now.

**Comment by MathewSachin** [comment]
We'll be putting up a new build really soon. We've improved the precision of the scrolling code.
Please wait until then.

**Comment by ARFearKubrick** [comment]
Can I give you guys a recomendation(an idea) for the scroling? You work is amazing and it will be nice to improve it.

**Comment by MathewSachin** [comment]
Sure! we'll be happy to know your idea regarding scrolling.
BTW, v0.9.0 is up! Give it a try!

For Android 7, we've reduced the scroll length to half.
For Android 8 and above, we do a scroll and hold gesture.

**Comment by ARFearKubrick** [comment]
Ok, this is the idea:

![Dibujo sin título](https://user-images.githubusercontent.com/19924044/79859780-d39e6c80-83d1-11ea-992d-508dc12117b0.jpg)


The app istead of touching that space on the bottom left, touches the scroll bar and drags it down scanning the support servants until it reaches the end, when succesfuly finds the servant you want it stops draggind the scroll bar and selects that servant, else, it updates the list. You could input the scrolling velocity on settings.

I think this will be more efective because in the actual mode it touches the servant first for a small moment and then swipes very hard so it ends skipping some servants or missing them when it try to selec them, so when you tap the scroll bar, it doesn't tap any servant at all and the movement of the scroll bar is fixed to the lenght of the support servant list. The scanning metod will be more efective because it won't miss any servant.

**Comment by MathewSachin** [comment]
I can think of a potential problem with this method.
If you have event filters enabled, the number of servants will be lesser. So, the scroll bar size would change, right? Will it work if we scroll at the same velocity?

Did you give v0.9.0 a try? Does it improve the situation?
Actually, we can do precise scrolls (like your method requires) only on Android 8 and above with the method we're using. On Android 7, it is just a quick swipe.
So, on Android 7 (my phone's also Android 7), we just reduced the amount to scroll by half. This is not the most efficient way to do it, but it seems to work.

**Comment by reconman** [comment]
I agree with @MathewSachin here, different sizes of the scroll bar would result in different scroll amounts, whereas drag- and dropping has a constant scrolling behavior.

**Comment by ARFearKubrick** [comment]
Well, that just a shame for us android 7 users. Also, the problem will be if the scroll bar was smaller, becouse smaller it is, faster it goes, so in events it would be even more precise.

v0.9.0 I think it's a great improvement, I tested it with 5 silver apples and when I came back the job was completed. I'll keep testing and if I see something I'll tell you.

**Comment by ARFearKubrick** [comment]
Also, am I or in the past update floating text appeared telling you when it's going to update the support list and the ammount of apples that it have been consumed? Now they are gone, is that intentional?

**Comment by ARFearKubrick** [comment]
Seeing it in action the app sometimes fails choosing the noble phantasm card, I think that is because my device is a bit laggy with the game so the app taps the noble phantams card when it is not ready for tapping it. I think that can be fixed with a togleable option called "laggy device" or something like that and what it does is that it extends the timer between tapping the attack button and choosing the cards so the app doesn't pick the card when the game is loading it.

**Comment by ARFearKubrick** [comment]
Ok forget what I said above, I have seen the issue in action again, the laggy point is not the command card, is the attack button itself. There is a point that when you use a skill in the game, the game does not let you tap the atack button, so the app taps the untappable attack button and it tryes tapping the cards, and what the app does is open the status info of the servants. If you whant the game to farm alone, thats does nothing because the app completes the quest like always, but if you what a 3 turn farm it the battle extends to 8, 9 turns, so is a big issue.

**Comment by reconman** [comment]
Regarding "laggy devices", see #27

**Comment by ARFearKubrick** [comment]
App avoid the first servant in preferred option, so if the first servant is in the preferred list, the app won't pick it.

**Comment by MathewSachin** [comment]
@ARFearKubrick Can you test with the latest release, @reconman did some fixes which solved performance issues for most users.
The problem happened on non-720p phones. Your's seems to be 1080p so the fix should improve performance on it.

**Comment by ARFearKubrick** [comment]
I tested the lastest release and it's been working well, it picks the noble phantasm card right, I will be seeing the app in action and I will tell you if something odd happens.

Also, you asked for icons in the release of 0.9.0, so I did some. I hope you like it.
![FateGA big Icon](https://user-images.githubusercontent.com/19924044/80072509-9f988800-8546-11ea-94c8-b0e23e073420.png)
![FateGA small Icon](https://user-images.githubusercontent.com/19924044/80072516-a32c0f00-8546-11ea-9e6d-4d3ff0182d77.png)

**Comment by MathewSachin** [comment]
We appreacte your designing the icons, but, making icons for Android is not that easy.
For starters, see https://material.io/design/iconography/product-icons.html#design-principles
These things are beyond us and would probably need the help of professional designers.

Also, not to sound rude or anything, but, I'm not a fan of summer Helena's design. Not anything against original Helena though, she's already 10/10/10 Bond 10.
