### ISSUE TITLE
Failed to installed on Bluestacks

### ISSUE THREAD

**Issue by machina2020** [MathewSachin/Fate-Grand-Automata#361]
I am trying to install on bluestacks but keep saying failed to install.

I even changed to cmpatibility mode but think that have nothing to do it.

Does it hava someone to do with new version of bluestacks or need to use an old one? 

I never tried it on emulator before and sorry if this was already asked before.

![unknown](https://user-images.githubusercontent.com/70169131/92339456-18d7e800-f0ae-11ea-84e6-f8153785a2f2.PNG)

**Comment by MathewSachin** [comment]
Android 7?
