### ISSUE TITLE
Not working on Huawei 

### ISSUE THREAD

**Issue by Sinkingstyle** [MathewSachin/Fate-Grand-Automata#363]
> downloaded the latest release 

**Describe the bug**
I installed the app earlier today, it worked fine on NA. Later, I messed with the max update, clicks, swipe and wait settings. I then later played JP (I also changed the settings to JP) to test it out and it doesn't work anymore. I then went to NA and it also doesn't work anymore. 
I reinstalled to reset the settings and it still doesn't work. 

**Device Info (please fill atleast 'Device model'):**
 - Device model: MRD-LX2
 - Screen size: 1560x720
 - Android Version: 9
 - RAM:3GB

**Comment by MathewSachin** [comment]
That's a problem with Huawei phones. See #354.
Nothing can be done about it in the app.

**Comment by Sinkingstyle** [comment]
The battery thingy worked.. Just need to restart the device

**Comment by MathewSachin** [comment]
Instead of restarting the device, you can also just Force Stop the app or Clear cache like said in that issue.
