### ISSUE TITLE
auto reapply skills?

### ISSUE THREAD

**Issue by thunderkai** [MathewSachin/Fate-Grand-Automata#365]
so after the typical 3 wave maps and skills can be used again, is there a way to have the AI apply the skills again?

**Comment by MathewSachin** [comment]
All skills have different cooldowns and servants die when they are killed.
So, it's outside the scope of this app to use skills by itself.
And it's not an AI, just uses image matching to do things.
You'll have to explicitly tell it which skill to use on which wave/turn.

**Comment by reconman** [comment]
> servants die when they are killed

![image](https://user-images.githubusercontent.com/12360257/92514283-ecd57780-f211-11ea-98ba-3755f062577b.png)
