### ISSUE TITLE
Support for Unlimited Refreshes

### ISSUE THREAD

**Issue by the3dsandwich** [MathewSachin/Fate-Grand-Automata#371]
Hi,

I saw this in the Work project, and I think I have an idea of how to set this:

Instead of having the scales (0-50) for prefs.support.maxUpdates reflect the exact number of updates, we can dedicate one value (0 or 50) as the option for "unlimited" and notify users via the description text. Then we can check for that specific value so that it has a different behavior (refreshing without increasing numOfUpdates)

<img src="https://user-images.githubusercontent.com/32169552/92732506-255b8980-f3a9-11ea-940f-b5251e7d196c.png" width="50%" />
<img src="https://user-images.githubusercontent.com/32169552/92733572-5daf9780-f3aa-11ea-9991-ac84c01bfa56.png" width="70%" />

If this sounds good then I can go ahead and contribute a PR.

I just need to know if setting the "unlimited" preference to 0 is better or if 50 is better (or if a new max value is preferred)

**Comment by bergerst** [comment]
@MathewSachin and I already discussed this a lot.

Nobody *needs* truly unlimited updates. A value of 360 means to look for the support for 1 hour. If you can't find a support after 1 hour, you'll never find it.

And I'd rather let the phone go to sleep than letting it search for a support for 8 hours.

Increasing the upper limit to 360 or even higher would make the lower values hard to "hit".

There are 2 additional options we could do:

1. 0 means stop searching after 360 tries - which is not really intuitive for users
2. Make the update config bar so it starts jumping in bigger increment the higher the number is, similar to a logarithmic scale. That's probably not easy to implement.

**Comment by reconman** [comment]
@MathewSachin and I already discussed this a lot.

Nobody needs truly unlimited updates. A value of 360 means to look for the support for 1 hour. If you can't find a support after 1 hour, you'll never find it.

And I'd rather let the phone go to sleep than letting it search for a support for 8 hours.

Increasing the upper limit to 360 or even higher would make the lower values hard to "hit".

There are 2 additional options we could do:

0 means stop searching after 360 tries - which is not really intuitive for users
Make the update config bar so it starts jumping in bigger increment the higher the number is, similar to a logarithmic scale. That's probably not easy to implement.

**Comment by the3dsandwich** [comment]
I suppose that makes sense. Through personally I would sleep much better knowing that my phone will be doing something without exiting too early because I set the value too small. To be honest I usually set it to 3-5 and there's typically no problem of it getting stuck.
