### ISSUE TITLE
Support selection sometimes ignores CE setting.

### ISSUE THREAD

**Issue by SleipnirTheRapid** [MathewSachin/Fate-Grand-Automata#372]
> MAKE SURE YOU TESTED THE LATEST RELEASE.
I am. 0.20.0
> Samsung user? See https://mathewsachin.github.io/Fate-Grand-Automata/SAMSUNG.html
I mean, the emu *reports* as a Samsung device, but it's Bluestacks, so no.

**Describe the bug**
Something I've been running into every now and then is that when I set both a preferred support and a preferred CE the script sometimes straight up ignores the CE requirement, tapping the first servant that meets the requirements, regardless of CE. I've tried finding the cause of this behavior and, while I can't be sure, I believe the answer may lie in the difference between standard CE images and user-created ones. 

I tested it with the preset Waver and Lunchtime images, as well as custom-made Angra Mainyu and Before Awakening (apparently I misremembered the name) ones.
The script has no issues when I set the requirements to a Waver with any CE/Lunchtime, Angra with any CE/Lunchtime, or any servant with HRP. but when I ask it to find a specific servant (custom or preset) with BA, it'll click the first eligible servant in the list, regardless of CE. It does still properly take other limitations into account, like friends only or max skill settings.

**Screenshots**
N.A.

**Video**
I don't think screenshots or videos are particularly relevant here, as the behaviour isn't different from what is expected, at least visually.

**Device Info (please fill atleast 'Device model'):**
 - Device model: [Bluestacks version 4.220.0.1109]
 - Screen size: [1600x900]
 - Android Version: [7.1.2]
 - RAM: [4 GB]

p.s. the built-in Lunchtime CE image seems to be misspelled as Luchtime. Not sure if that has ever been brought up but I figured I'd mention it anyway.

**Comment by reconman** [comment]
A video WOULD actually be helpful, we can track the behavior in slow motion.

**Comment by SleipnirTheRapid** [comment]
Alright. Here's a short demo of the bug https://streamable.com/5904t2

As you can tell, it detects Angra just fine at first, taps an Angra with the wrong CE once I set some preferred CEs, and will scroll to the right CE before tapping if no servant is set.

**Comment by SleipnirTheRapid** [comment]
As an addendum: I just tried and failed to get it to select a Waver with Lunchtime even though it succesfully did so before, so I'm back to square one as far as ideas to the cause of this go.

**Comment by reconman** [comment]
I watched your video and tried to reproduce the error with a recent build.

What I've noticed in your video is that the script clicks in the middle of the support entry. This only happens if the preferred CE is set to `Any`. Otherwise it would click on the CE image.

What I've also noticed is that you have a configuration called `Bug Test`, but you selected a configuration called `event`. I couldn't see the name of your edited configuration. Did you select the one you edited?

**Comment by SleipnirTheRapid** [comment]
Yeah, I can see how that's confusing. I had created the bug test setup to test some things a few days ago, but didn't use it for the video. Besides, on the third attempt (just the preferred CE) it did click on the CE itself, so the behavior did change with my edits.

**Comment by SleipnirTheRapid** [comment]
Okay...I think I narrowed it down. It's a little silly...but I think it's *specifically* Before Awakening that's causing the issue. Maybe it's too dark?

**Comment by MathewSachin** [comment]
Before Awakening seems to work fine though. Tested it both with and without Angra on my phone and works as expected.
Can you post the image of 'Before Awakening' you have here (even if it was generated by Support Image Maker)?

My bad about Luchtime. Didn't even notice that was wrong yet and I think no else did either 🤣 
I'll correct that. But, it'll only get corrected for new users, unless existing users extract support images again. They can rename the file though if they're sure none of their setups depend on that file name.

**Comment by SleipnirTheRapid** [comment]
Sure. I've made another video (this time showing the setup name) displaying why I think it's that specific CE too. 

![Before Awakening](https://user-images.githubusercontent.com/19993875/92903579-7b204800-f422-11ea-958d-28b6863b4a23.png)

https://streamable.com/y03ir1

**Comment by MathewSachin** [comment]
It happened right now for me 😱 
Earlier when I tried, Before Awakening was in view and was getting selected.
Now, when it is not, a random Angra Mainyu is getting selected and like @reconman pointed, it is clicking on a different position than expected.
This bug is super-weird, I think this might take some time to debug.

**Comment by MathewSachin** [comment]
> Okay...I think I narrowed it down. It's a little silly...but I think it's specifically Before Awakening that's causing the issue.
(Also, I'm sorry for being so scatterbrained about this, it's well past midnight.)

You were spot on. It's so dark that it matches with the empty area between NP's name and Skills and that's why it was clicking there.
But, I wonder why we're even searching for CEs there. I'll limit it to look for CEs only at the left corner (where servants and CEs are actually present), so that should solve this problem I think.

**Comment by SleipnirTheRapid** [comment]
So it *was* checking for the CE, but by pure coincidence it matched with the area where it normally taps when it doesn't check for CEs? No wonder it was such a confounding bug.

**Comment by MathewSachin** [comment]
You know what, even more than solving the bug, this will also slightly increase the performance of CE matching since we don't have to look for CEs in that large area. I really wasn't aware FGO-Lua looked for CE images in that whole region when porting the code.

**Comment by reconman** [comment]
> So it was checking for the CE, but by pure coincidence it matched with the area where it normally taps when it doesn't check for CEs?

I was wrong about my statement. When you set a Servant but no CE, it will click on the Servant image. When you set a Servant and a CE, it will click on the CE. When you've set support to `First`, it will click in the area from the video.

**Comment by SleipnirTheRapid** [comment]
Either way, it's solved, presumably fixed, and we get a slight performance boost just in time for Gilfest(?). Cheers all around!
