### ISSUE TITLE
Don't work in oukitel u18

### ISSUE THREAD

**Issue by IsaacZM** [MathewSachin/Fate-Grand-Automata#373]
**Describe the bug**
First of all it has this notch device but I followed the steps and it doesn't work when I activate the script it doesn't do anything.

**Video**
https://youtu.be/gbmwPTSymoo

**Device Info (please fill atleast 'Device model'):**
 - Device model: Oukitel u18
 - Screen size: 720x1512
 - Android Version: Android 7
 - RAM: 4GB

**Comment by MathewSachin** [comment]
Official Notch support in Android came only in Android 9.
So, FGA can detect notch only on Android 9 or above.

**Comment by IsaacZM** [comment]
What should I do to solve this problem?

**Comment by MathewSachin** [comment]
Either update to Android 9 or create a custom fork of FGA with the code customized for your phone.

**Comment by IsaacZM** [comment]
Upgrading to android 9 is not an option.

It will have to be the second one, how do I do that?

**Comment by MathewSachin** [comment]
The second one needs some programming knowledge.

But, is there any way you can make FGO extend into the notch area?
Like on Samsung phones, there is a Full-screen apps setting.
Maybe also check in your phone's Developer options.

Unfortunately, I can't find much info about your phone on the net.

**Comment by IsaacZM** [comment]
If the full screen option is activated but it doesn't take the whole screen, maybe if I reduce the screen width it would be solved?

**Comment by MathewSachin** [comment]
try making both FGO and FGA full-screen. Reduce the screen width won't likely help.
And post a new video so I can see if it gets any better.

Otherwise, I'll point you to the relevant part of code.

**Comment by IsaacZM** [comment]
![Screenshot_20200911-110904](https://user-images.githubusercontent.com/48893799/92900265-d3097f80-f41f-11ea-987d-b51687dc4604.png)

https://youtu.be/MyqQk07BmRs

**Comment by MathewSachin** [comment]
FGO doesn't extend into the notch are even after making it full-screen.
If you can somehow just find a way to just rid of that notch, FGA should work as it is.
I think video player apps should be extending into the notch area on your phone. If the same can happen for FGO and FGA, then it'll work.

**Comment by IsaacZM** [comment]
nothing

**Comment by IsaacZM** [comment]
i try all method in internet and no work

**Comment by MathewSachin** [comment]
I mean I already told. Notches weren't official in Android before Android 9, sadly.
