### ISSUE TITLE
Failing to Select Support Properly 

### ISSUE THREAD

**Issue by Lyleof** [MathewSachin/Fate-Grand-Automata#38]
On the support selection screen the app fails to scroll or even pick a given support when the preferred is on screen.  It just does nothing.  Phone info Samsung Galaxy s20 Ultra 5G.  FGO Running in full screen mode (aka blue bars on the side).

**Comment by reconman** [comment]
JP or EN? Can you provide a screenshot of the support screen with the app running? Is it maybe related to the initial problem of #37?

**Comment by Lyleof** [comment]
EN.
![Screenshot_20200421-050457_Fate_GO](https://user-images.githubusercontent.com/22329850/79847641-00309500-838e-11ea-8ab2-7ee5ea9a83e9.jpg)
![Screenshot_20200421-050547_FateGrand Automata](https://user-images.githubusercontent.com/22329850/79847662-045cb280-838e-11ea-91e2-bacb8122a313.jpg)

**Comment by MathewSachin** [comment]
Umm... In the screenshot, preferred Servant and/or CE are not set.

**Comment by reconman** [comment]
Can you show us the autoskill configuration?

**Comment by MathewSachin** [comment]
@reconman Seems to me like it's the `Ignore Notch calculation` problem here.
Both blue bars are same size but the images of the device on internet show a notch.

**Comment by reconman** [comment]
Ah yes, of course. When are you planning on doing an official release? Telling users to download random builds is not good in the long term.

**Comment by MathewSachin** [comment]
I was waiting to tackle a few more issues.
Sure, I'll do a release now.

**Comment by MathewSachin** [comment]
I've done the release. Forgot to update here.
@Lyleof can you try running [v0.9.0](https://github.com/MathewSachin/Fate-Grand-Automata/releases).

Before, running the script, go to `More options` and enable `Ignore Notch calculation` option.

**Comment by Lyleof** [comment]
The Ignore Notch Calculation works like a charm and now scrolls, selects supports, and correctly chooses skills & NP's (it was slightly off before).  The Only problem I can see is that when I get booted back to the node selection (Running 40ap doors with the node at the top right).  It fails to select the node again because its slightly lower.

**Comment by reconman** [comment]
> The Only problem I can see is that when I get booted back to the node selection (Running 40ap doors with the node at the top right). It fails to select the node again because its slightly lower.

I also had this issue today, it suddenly switched from 40 AP to 30 AP without me noticing.

**Comment by Lyleof** [comment]
This is really only an issue for auto looping through the same node and can hopefully be fixed by just having it look just a tad lower for it.  I haven't tested the looping on single nodes yet.  Hopefully things default back to the correct node during multi-node farming maps/events because it would be a pain to have to manually select the node every time.

**Comment by reconman** [comment]
I've created a new Issue for the switch from 40 AP to 30 AP, see #44
