### ISSUE TITLE
How to write friend's name?

### ISSUE THREAD

**Issue by runelt99** [MathewSachin/Fate-Grand-Automata#380]
When clicking friend names ANY, i only get a blank screen with 'Friend names', 'CLEAR' , 'CANCEL' and 'OK'. I have tried clicking everywhere but its not allowing me to insert new name.

On same note, how do i add more servants to 'preffered' support list? It only has the default ones from support, despite that i can select berserkers as the class.

**Comment by MathewSachin** [comment]
https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Support-Image-Maker
