### ISSUE TITLE
Upcoming KR Update

### ISSUE THREAD

**Issue by sleeping-player** [MathewSachin/Fate-Grand-Automata#381]
When : https://cafe.naver.com/fategokr/2259707
Sep 15th 10:30~15:00(or a few minutes before) GMT+9
What : https://cafe.naver.com/fategokr/2252992
very much pictures

First I am checking list of what screenshots are needed.
I think this update cannot be supported by all screenshots in JP assets list, and some of En assets should be included...

**Comment by MathewSachin** [comment]
@sleeping-player I think only 2 images would be needed:
1. Repeat Quest screen
2. Friend support result screen.

But, open a new issue as a Feature-request or the `github-actions` bot will close and lock it again and you won't be able to reply on it.
