### ISSUE TITLE
Upcoming KR Update

### ISSUE THREAD

**Issue by sleeping-player** [MathewSachin/Fate-Grand-Automata#382]
When : https://cafe.naver.com/fategokr/2259707
Sep 15th 10:30~15:00 GMT+9
(correction: this type maintenance are usually delayed)
What : https://cafe.naver.com/fategokr/2252992
very much pictures

Oh I forgot to check issue type...

**Comment by MathewSachin** [comment]
Copying my response from the previous issue:
I think only 2 images would be needed:

1. Repeat Quest screen
2. Friend support result screen.

**Comment by sleeping-player** [comment]
- [ ] StopGifts.png
- [ ] confirm.png
- [ ] inven_full.png
- [ ] menu.png
- [ ] lottery.png - not yet

- [x] fp_continue.png
- [x] master_exp.png
- [x] mat_rewards.png
- [x] questreward.png
- [x] resist.png
- [x] result.png,
- [x] retry.png
- [x] support_region_tool.png
- [x] weak.png
- [x] withdraw.png

**Comment by MathewSachin** [comment]
The images fall back to En/NA if not found, so the `menu.png` should be fine.
`fp_continue.png` will need to be updated since Friend Point Summon is changing for KR.`
`confirm.png` is for the Repeat quest screen.
`inven_full.png` is not much of a priority. It's just for automatically stopping the script when the inventory is full. It won't be easy to get your inventory to full outside of some specific events.

**Comment by sleeping-player** [comment]
I think the problem will get worse.
**Device Info :**
 - Device model: Galaxy S10+
 - Screen size: 3040×1440
 - Android Version: Android 10
 - RAM: not related
![Screenshot_20200915-134057_FateGO](https://user-images.githubusercontent.com/69798206/93166538-a7590300-f759-11ea-811b-9898f2b34912.png)

**Comment by sleeping-player** [comment]
OK pm 3:00 exact time opened

**Comment by ScathachSkadi** [comment]
As expected, the repeat quest doesn't work yet. Do you need screenshots on a certain resolution?

**Comment by sleeping-player** [comment]
@ScathachSkadi Just a second

**Comment by sleeping-player** [comment]
![confirm_orig_kr](https://user-images.githubusercontent.com/69798206/93172742-674c4d00-f766-11ea-8981-88c387d83208.png)
![fp_continue_orig_kr](https://user-images.githubusercontent.com/69798206/93172747-69161080-f766-11ea-9379-d178e4e12154.png)

**Comment by MathewSachin** [comment]
1280x720 would be the easiest for me. But, whatever resolution is fine. I'll just resize.

**Comment by ScathachSkadi** [comment]
Oh he just uploaded it. The black bars don't matter right? I have a phone without a notch but with the blue bars.

**Comment by MathewSachin** [comment]
Black bars are fine. Both blue and black bars have to be cropped out anyway.
