### ISSUE TITLE
FGA not working on OnePlus 7T

### ISSUE THREAD

**Issue by Me1zter** [MathewSachin/Fate-Grand-Automata#386]
Hi. The app isn't working on my device for some reason. It can detect and select support servants but it does not work during battle. I've downloaded the latest ver of this app from Play Store and tried setting both FGO and FGA in fullscreen mode but the problem still persists. Really need help with this one.

Device: OnePlus 7T
Model: HD1900
OS: Android 10
Resolution: 2400 x 1080
Ram: 8 GB

Screenshot:
<img src="https://user-images.githubusercontent.com/71225797/93023900-b6469500-f635-11ea-986d-ce1dbd66ed9d.jpg" width="250"> <img src="https://user-images.githubusercontent.com/71225797/93023898-b2b30e00-f635-11ea-9f4d-9e72665e89a6.jpg" width="250">
<img src="https://user-images.githubusercontent.com/71225797/93023905-bcd50c80-f635-11ea-99a4-51e03aa3ca41.jpg"> 
<img src="https://user-images.githubusercontent.com/71225797/93023916-c494b100-f635-11ea-9704-33fd644e33f6.jpg">

Screen recording:
[https://streamable.com/bt91qd](https://streamable.com/bt91qd)

**Comment by MathewSachin** [comment]
Ok, you didn't follow the bug template, but atleast info is there.

**Comment by Me1zter** [comment]
@MathewSachin

**Comment by Me1zter** [comment]
My apologies, forgot to mention the owner.

**Comment by MathewSachin** [comment]
Yeah, looking at it. Give me a few minutes.

**Comment by reconman** [comment]
@Me1zter Skill confirmation is turned ON in FGO but OFF in FGA. I would recommend turning off skill confirmation in FGO, it will make your runs faster. Otherwise, turn on Skill Confirmation in the `More options` settings.

**Comment by Me1zter** [comment]
I'll try that now. Give a couple of minutes.

**Comment by Me1zter** [comment]
*me

**Comment by Me1zter** [comment]
Thanks for the help!! It works like a charm now.
