### ISSUE TITLE
Prevent users from not selecting any autoskills

### ISSUE THREAD

**Issue by reconman** [MathewSachin/Fate-Grand-Automata#388]
Right now you can set up multiple autoskill setups and then click OK in the `Select Autoskill Config` window (ScriptManager.kt).

You can also have 0 autoskill configs, which will just display that you don't have any configs, but you can still click OK. This was done so people who don't want to use skill commands can still use the app. But since the global support configuration doesn't exist anymore, this cannot work.

In both cases, the app will continue to the Support screen and then exit with an error stating that a preferred servant or CE must be set.

To fix this, the OK button in the `Select Autoskill Config` should be disabled as long as no item is selected to prevent new and veteran FGA users from not selecting anything.

And to prevent people from starting FGA without any autoskill configs, there should be an error message telling them to create one. To reproduce the old behavior of having no Skill Command but being able to specify support selection preferences, users can just create an autoskill configuration with the Skill Command being empty.

**Comment by TryBane** [comment]
Alternatively, can't we also create a default configuration that can't be deleted that is an empty string that isn't even shown to the user and is automatically used when they don't have/use autoskill?

Also, if no servant or ce is selected, then just having it default to "first" would be optimal. This can be done through checking what settings they've selected.

**Comment by reconman** [comment]
> Alternatively, can't we also create a default configuration that can't be deleted that is an empty string that isn't even shown to the user and is automatically used when they don't have/use autoskill?

That's what's currently happening and then it doesn't know which support to select. There is no global support config anymore.

> Also, if no servant or ce is selected, then just having it default to "first" would be optimal. This can be done through checking what settings they've selected.

Almost nobody wants to use `First`.

**Comment by TryBane** [comment]
Assuming they haven't selected a support configuration, first is the only viable option. At some point, we have to assume the user wants what they've selected right?

**Comment by reconman** [comment]
No, users are forgetful and make mistakes. I only noticed the issue when it happened to me by accident.

**Comment by TryBane** [comment]
Yes, but they can also make mistakes in skill orders and the like. We can hold their hands, but it will never be perfect.

Also, I literally just helped someone on Discord with their script config, and they specifically wanted "first" since they didn't care about any servants/ces and just wanted it to farm for them. Baffles me, but they wanted it that way.

**Comment by MathewSachin** [comment]
Manual isn't unwanted. I use it during events sometimes, mostly the clear node X time mission ones, so I don't enter a fight accidentally with wrong CEs when I'm using a universal partly face-card comp.

I strongly think we need what @reconman is asking for.

Also, we should've used a name like `Teams` or `Parties` instead of `AutoSkill` which confuses users at first glance 🤔.
But, don't know if it'll be right to change that now.

**Comment by TryBane** [comment]
Autoskill was originally created early on in the script. Programmers can come up with really inventive names that we realize don't work well later on. Changing it wouldn't be a bad idea. In fact, the earlier the better, as long as the new name is one that doesn't need to be changed later on.

But Autoskill actually was implemented well before Support Selection came out, and Support Selection was implemented before someone had the idea to make Autoskill a list of skills to keep from having to have multiple skill lists that are just commented out (ah, the good ol' days)

**Comment by MathewSachin** [comment]
`AutoSkill` was a fine name for the Lua script I think since initially, the list contained only Skill commands.
I was saying more like when I started this app, I should've renamed it.
Let's see what @reconman has to say.
