### ISSUE TITLE
Pausing the script until the player has enough AP

### ISSUE THREAD

**Issue by ScathachSkadi** [MathewSachin/Fate-Grand-Automata#389]
The script will stop when it shows the apple page which means the player run out of ap. But when the script stops and the ap refills a few seconds later... It's a bit annoying. Will there be a way to keep checking the ap until the player has enough to do the quest?

For example, instead of stopping at the apple page, the app would go out of the apple page and repeatedly press the quest until it finally lets the player in. Maybe tapping the quest button every 15, 30 seconds?

**Comment by MathewSachin** [comment]
The app is already being bullshitted by Vietnamese people for draining battery. I don't know, FGO seems to use much more. But, this feature will also cause me to hold WakeLock which would definitely drain battery.

Other than that my final decision is that I'm not going to support things that could lead to potential bot accounts that need no user interaction like logging in at reset time, re-rolling, story. This feature feels like the same category to me.

I mean why is it annoying? The app is already doing that much. You just have to start it again after AP refill or just use apples.

**Comment by ScathachSkadi** [comment]
Bro... I feel ya. Sorry and thanks anyway.
