### ISSUE TITLE
Add autoskill copy functionality

### ISSUE THREAD

**Issue by reconman** [MathewSachin/Fate-Grand-Automata#392]
The only way to copy autoskill configs right now is to export it as JSON, then edit that file, and then reimport it. During that process, users can do mistakes, messing up the autoskill configuration.

I think the best course of action would be to offer a copy functionality in the ... when you've opened an autoskill configuration, which gives you a text field where you can specify the name of the new config.

**Comment by MathewSachin** [comment]
check again. it's already there

**Comment by reconman** [comment]
Ooooh, the copy icon.
