### ISSUE TITLE
Taps repeatedly to skip arash death animation ?

### ISSUE THREAD

**Issue by Eufras1a** [MathewSachin/Fate-Grand-Automata#393]
Poor arash has to die again and again for our farming. 
The least we can do is end his suffering earlier. 

So i propose a Dedicated button in the maker specifically for this unique scenario as Arash is the only person who dies when we farm in 3 turn till the chosen one comes in the next anniversary.

**Comment by MathewSachin** [comment]
Already told it's pretty much impossible for this app to detect servant death.

I've denied this so many times already.
Look at other issues before opening a new one.
#345, #185
