### ISSUE TITLE
Normal atk card help

### ISSUE THREAD

**Issue by akun90** [MathewSachin/Fate-Grand-Automata#394]
Just wondering if there is a way to make the fga choose a certain character card for auto attacks.
For example with double skadi+ dabtes i want dantes to be the one chose for atk after np. Is there a way to do that?

**Comment by MathewSachin** [comment]
In Card Priority, turn On experimental features, for brave chains set After NP.

**Comment by akun90** [comment]
Where is it? Im in card priority but cant see it.
![Screenshot_20200914-204233_FateGrand Automata](https://user-images.githubusercontent.com/68243506/93125156-015eb780-f6cb-11ea-9ece-0ee67d651413.jpg)

**Comment by MathewSachin** [comment]
You're not even on the Play Store version :huh:

**Comment by akun90** [comment]
So unistall and reinstall?

**Comment by reconman** [comment]
Please check which version is installed. You can see that by keeping a finger on the app icon, then select App Details, and then at the bottom somewhere should be the app version. If it isn't v0.21.1, then something is wrong.

Maybe you have a pre-play-store version?

**Comment by akun90** [comment]
I unistalled and instailed it again and now i see the experimental feature and all but the rearrange feature doesnt work, is it the third skill of mage assocation uniform?
![Screenshot_20200914-225636_FateGrand Automata](https://user-images.githubusercontent.com/68243506/93137328-92d72500-f6dd-11ea-9b24-08dcee92caaa.jpg)

**Comment by reconman** [comment]
`Rearrange cards` is not what you think and it's not documented well yet. It tries to pick the strongest card first and the second strongest 3rd. For example BAB instead of BBA.

**Comment by akun90** [comment]
ah ok...  i thought it was the usage of third skill of mage uniform, just in case you are unlucky.

**Comment by akun90** [comment]
And what abou avoid in the dropdown menu? Does it try to avoid brave chain?

**Comment by reconman** [comment]
> And what abou avoid in the dropdown menu? Does it try to avoid brave chain?

Yes, exactly.

**Comment by akun90** [comment]
Thx man for infos
