### ISSUE TITLE
Not selecting propper support

### ISSUE THREAD

**Issue by crestkat** [MathewSachin/Fate-Grand-Automata#395]
Extracted the image for CKT so i could auto farm the lotto. its completly ignoring wavers with it for some reason. works fine otherwise. 
https://youtu.be/bG5VaiypOR0

https://cdn.discordapp.com/attachments/634018469532139521/755118492960817232/Screenshot_20200914-133102_FateGrand_Automata.jpg

https://cdn.discordapp.com/attachments/634018469532139521/755118493200023623/Screenshot_20200914-133112_Gallery.jpg

**Comment by reconman** [comment]
You haven't specified your phone model, which is required by the template.

How did you create the CE image? It seems incorrect. There is some part on the right which shouldn't be there.

Also, you can set event CE filters in FGO itself and set the preferred CE in FGA to `Any` by clicking on Event Bonus Filter in the top right of the support selection, disable `No Event Bonus Available`, then scroll down and Hide everything but C.K.T.

**Comment by reconman** [comment]
Oh and your video also doesn't have `Debug Mode´ activated as specified in the bug template.

**Comment by MathewSachin** [comment]
@reconman I think this is just a case of not reading Troubleshooting Guide. They didn't make FGO full screen before taking image of CKT
