### ISSUE TITLE
App Skill Confirmation Targeting Inaccuracy

### ISSUE THREAD

**Issue by Kelliro** [MathewSachin/Fate-Grand-Automata#396]
While running an AutoSkill, my app would press the skill icon button pretty well but then would fail to hit the 'OK' button to confirm its use or, if the skill required, it would fail to select a target for the skill's use. I have tried turning on Ignore Notch Calculations since I'm on a Samsung Galaxy S6 Lite but it still didn't help. Are there any other setting I can use to adjust the skill use targeting or is the app just not compatible?

**Comment by reconman** [comment]
See https://github.com/MathewSachin/Fate-Grand-Automata/issues/386#issuecomment-691697380

**Comment by MathewSachin** [comment]
This again 🤦
