### ISSUE TITLE
Auto Retrieve Silver EXP from the Gift Box

### ISSUE THREAD

**Issue by gogito** [MathewSachin/Fate-Grand-Automata#397]
I saw that you said that you won't implement the Auto Gift Box feature from FGOLua due to missing Text Recognition but I was wondering if it's possible to make it automatically retrieve Silver EXP cards of any quantity since that is image recognition and not text. Great app either way!

**Comment by MathewSachin** [comment]
https://github.com/MathewSachin/Fate-Grand-Automata/tree/auto-gift-box should serve as a good starting point if anyone is intended. It is just a fake implementation right now

**Comment by TryBane** [comment]
Auto collection of the xps shouldn't be difficult to implement without the need for OCR. You can just use images of the x1, x2, x3, and x4 (assuming people generally want to keep their x5+s) and have it look for those and the XP designs on the far left. Shouldn't be too difficult to implement, though I haven't done it in the fgo_lua scripts myself yet.

**Comment by ScathachSkadi** [comment]
I was going to make this issue! Thanks for doing that.

**Comment by MathewSachin** [comment]
> You can just use images of the x1, x2, x3, and x4

I was thinking of doing the same but we need blank space to the right of these images or `x1` might also match with `x10` or `x100`.

**Comment by TryBane** [comment]
Yes, I don't think that should be an issue? Here we see that there is nothing to worry about in the space past the x1 and x2 (there are occasional x20's we gotta be mindful of as well)

https://cdn.discordapp.com/attachments/579639097388433448/755328343121068072/oie_18fx5LVDlNLU.png

We can even increase the space a bit just to be safe, and increase the similarity threshold (still haven't looked through the code to see how this works, but I assume this version of the script has a feature like this)

**Comment by MathewSachin** [comment]
> Yes, I don't think that should be an issue?

Not an issue. Just wrote because it was an important case to consider. Yeah, also `x20`.

Yes, different similarities can be used for different cases, but I think the default value might just work as it is if the empty space is wide enough.

**Comment by TryBane** [comment]
Agreed.

**Comment by MathewSachin** [comment]
Hey, can someone get me some images. My present box is empty right now and I'm out of apples.
Will start again with rapples maybe later this evening or tomorrow.
So, I'll get the NA ones atleast by then. Maybe not `x4` cuz that is rare.

I'm planning to do it a bit differently from the script in Lua. Instead of asking user for a ClickCount, we'll set it to 99, since I think that's the maximum we can accept at one time.
We'll track the scrollbar to know when we need to stop. Or if we hit 99 earlier.

Keep all images of full FGO screen. I added the ones I found. For some reason, I can't seem to find many images of these by Googling 🤔 
- Without scrolling (Scrollbar at top) (Doesn't matter if there are no embers)
![Screenshot_20181121-105115 1](https://user-images.githubusercontent.com/10654537/93180839-58a96a00-f755-11ea-82de-cbe0e9ea9873.jpg)

- Completely scrolled to bottom  (Doesn't matter if there are no embers)
- I need `x1`, `x2`, `x3`, `x4` . (preferably both Silver and Gold and if possible from multiple servers)
![EL09HmoWoAE3qB0](https://user-images.githubusercontent.com/10654537/93181206-cd7ca400-f755-11ea-8253-a070ececcb54.jpg)

- `x5`, `x10`, `x20`, `x100` would help in testing.

I'll try to get the script ready by 1-2 days so I can test it out when I actually have something in my present box.

**Comment by reconman** [comment]
![Screenshot_20200915-102334](https://user-images.githubusercontent.com/12360257/93185615-eb3e0f00-f73d-11ea-8192-dd29858a5203.jpg)
![Screenshot_20200915-102344](https://user-images.githubusercontent.com/12360257/93185621-ec6f3c00-f73d-11ea-95ff-f9c35cc9b7aa.jpg)
![Screenshot_20200915-102551](https://user-images.githubusercontent.com/12360257/93185625-eda06900-f73d-11ea-8d92-029cca993848.jpg)
![Screenshot_20200915-102557](https://user-images.githubusercontent.com/12360257/93185628-ee38ff80-f73d-11ea-8f25-722a4a42444d.jpg)

Here's 1 to 4, 10, 50 and 100.

**Comment by ScathachSkadi** [comment]
Gilfest didn't start yet in kr but I do have images of some exp cards.

**Comment by ScathachSkadi** [comment]
![Screenshot_20200915-180943.jpg](https://user-images.githubusercontent.com/70437676/93190798-c1590c80-f77e-11ea-93a2-ac541a758759.jpg)![Screenshot_20200915-180953.jpg](https://user-images.githubusercontent.com/70437676/93190812-c5852a00-f77e-11ea-8790-0e2f90568563.jpg)![Screenshot_20200915-180958.jpg](https://user-images.githubusercontent.com/70437676/93190826-c8801a80-f77e-11ea-9e7b-e769a5f48927.jpg)

**Comment by MathewSachin** [comment]
@ScathachSkadi the number font is different from NA. So, does the Max skill option work on KR?

**Comment by MathewSachin** [comment]
Nevermind, the skill level font is same

**Comment by ScathachSkadi** [comment]
![Screenshot_20200915-182244.jpg](https://user-images.githubusercontent.com/70437676/93192398-9b346c00-f780-11ea-914b-251ee489d6aa.jpg)
Font for that is the same.

**Comment by the3dsandwich** [comment]
I think TW has the same font as JP and NA? I got some images.

![Screenshot_1600162254](https://user-images.githubusercontent.com/32169552/93193327-48a38180-f779-11ea-8bfa-6be3f85bf3b0.png)
![Screenshot_1600162267](https://user-images.githubusercontent.com/32169552/93193337-4c370880-f779-11ea-8440-7837da3e0e27.png)
![Screenshot_1600162272](https://user-images.githubusercontent.com/32169552/93193366-578a3400-f779-11ea-8770-a3f38ab679e0.png)

**Comment by MathewSachin** [comment]
@the3dsandwich Seems to have a slight difference. I'll have to check though

**Comment by clymchi** [comment]
Here's NA gold exp x5 and x6 as well as silver exp x100
![Screenshot_20200915-130135](https://user-images.githubusercontent.com/71350692/93259635-fd777780-f754-11ea-99ba-a2cb99c17181.png)
![Screenshot_20200915-130315](https://user-images.githubusercontent.com/71350692/93259657-0700df80-f755-11ea-90c3-29361e6423fe.png)
![Screenshot_20200915-130336](https://user-images.githubusercontent.com/71350692/93259729-23048100-f755-11ea-98ec-de34ba202a83.png)

**Comment by MathewSachin** [comment]
Okay, so got it working for NA and JP.
The images for `x1`, `x2`, `x3, `x4` are included in the app.
Both JP and NA work with the same images.

I'm missing `x3`, `x4` for KR and `x1`, `x2` for TW.

**Comment by ScathachSkadi** [comment]
Gilfest will start in about 45hours in kr

**Comment by ScathachSkadi** [comment]
![Screenshot_2019-09-12-19-26-23.png](https://user-images.githubusercontent.com/70437676/93314926-663e1d00-f845-11ea-94e4-61b1b4621287.png)

I found it

**Comment by the3dsandwich** [comment]
Super excited for this update!
`x1` and `x2` for TW:

![Screenshot_1600251630](https://user-images.githubusercontent.com/32169552/93325069-50325b80-f849-11ea-956a-da47753f2bbc.png)

**Comment by ScathachSkadi** [comment]
![Screenshot_20200916-232109](https://user-images.githubusercontent.com/70437676/93350628-cfd52000-f873-11ea-9974-a02a40f1e044.png)
I did get a screenshot of the silver exp, but it's not 1~4

**Comment by MathewSachin** [comment]
it should be fine. Silver will be always checked by the script regardless of number.

**Comment by ScathachSkadi** [comment]
Oh right. No one actually uses it for leveling up servants when the lottery event is happening.

**Comment by MathewSachin** [comment]
The feature is pretty much ready.
CI builds available if anyone wants to check: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/258058166

Didn't do the scrollbar check part, that's was just a weird idea I had.
