### ISSUE TITLE
Not working on Huawei P20 (Android 9)

### ISSUE THREAD

**Issue by Akugen1** [MathewSachin/Fate-Grand-Automata#399]
> MAKE SURE YOU TESTED THE LATEST RELEASE.

Done.

> Did you look at other issues and the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)?

Yes. My phone is Not 16:9, but has a notch. It looks as it should. 
I have a Huawei P20, and Full-Screen Display lists neither FGO nor FGA.

**Describe the bug**
After programming everything into autoskills as according to the tutorial, FGA does not take any of the actions it is told. 
- When the play button is pressed on the quest selection screen, with the quest at the top-most position as shown in the tutorial, no actions occur.
- When the play button is pressed in the support list selection screen, the app either does nothing or scrolls down but doesn't select any of the supports, despite there being supports that match the criteria.
- When the play button is pressed in the battle screen, the app takes no actions other than display the following message: "Failed to determine Card type: [1, 2, 3, 4, 5]" (shown in screenshot)
To reproduce the error, it is sufficient to press the play button at any moment. The error is shown visually only in battle. The program was left running for 30s before being stopped in every condition.

**Screenshots**
Autolist Script:
![Screenshot_20200914_193432_com mathewsachin fategrandautomata 1](https://user-images.githubusercontent.com/71289747/93133564-bc8d4d80-f6d7-11ea-9ee5-1de716a3dfa6.jpg)
Settings on FGA:
![Screenshot_20200914_221658_com mathewsachin fategrandautomata 1](https://user-images.githubusercontent.com/71289747/93133843-27d71f80-f6d8-11ea-9468-0a0a28ef711f.jpg)
Situations in which FGA takes no actions:
![Screenshot_20200914_220602_com aniplex fategrandorder en 1](https://user-images.githubusercontent.com/71289747/93133612-cdd65a00-f6d7-11ea-8f08-bb1fd96588a9.jpg)
![Screenshot_20200914_220701_com aniplex fategrandorder en 1](https://user-images.githubusercontent.com/71289747/93133635-d62e9500-f6d7-11ea-94ff-583efc0dafc7.jpg)
![Screenshot_20200914_220808_com aniplex fategrandorder en 1](https://user-images.githubusercontent.com/71289747/93133690-e8a8ce80-f6d7-11ea-8195-cd4c0aa70170.jpg)
![Screenshot_20200914_220901_com aniplex fategrandorder en 1](https://user-images.githubusercontent.com/71289747/93133702-ee9eaf80-f6d7-11ea-9f58-4dbb884023df.jpg)

**Video**
This shows the in-battle error popup: https://youtu.be/zUCCEbtPZN4

**Device Info:**
 - Device model: Huawei P20
 - Screen size: 2244x1080
 - Android Version: Android 9
 - RAM: 4GB

**Comment by reconman** [comment]
Seems like it's caused by this: https://github.com/MathewSachin/Fate-Grand-Automata/issues/354#issuecomment-687152298

**Comment by Akugen1** [comment]
I feel really stupid. It works now. Thank you so much. Sorry for wasting your time (really am genuinely sorry, feel horrible for not reading well enough and having to chase after my issue). Best of luck with everything you're doing and you're a godsend for this!
