### ISSUE TITLE
[Enhancement] Option to delete and rename CE/support Servant image from App

### ISSUE THREAD

**Issue by saberkevin** [MathewSachin/Fate-Grand-Automata#40]
Sometimes event already passed and the rerun is already done, it will help to remove some steps if we can remove unused ce/servant image to save memory from app, can be a little trash bin icon per item (with confirmation) on the selection menu.

EDIT: rename function is good too, to rename image from support maker

Thanks mathew for this good app, really looking forward how this app will grow in the future.

**Comment by reconman** [comment]
Renaming was implemented in #94
