### ISSUE TITLE
Refill Setting

### ISSUE THREAD

**Issue by nFeyz** [MathewSachin/Fate-Grand-Automata#400]
What is the setting for refill if I want to use apples without repetitions limit. Just use apple as long as I have it. 

Currently setting repetitions to 0 (default) seems not refilling at all atm.
![Screenshot_2020-09-15-07-45-55-931_com mathewsachin fategrandautomata](https://user-images.githubusercontent.com/53361797/93149356-ab206180-f728-11ea-85b3-b00c87a64cdb.jpg)

**Comment by reconman** [comment]
Just set it to a high number like 500, that should be enough.
