### ISSUE TITLE
Not selecting Support

### ISSUE THREAD

**Issue by Willbito** [MathewSachin/Fate-Grand-Automata#401]
> MAKE SURE YOU TESTED THE LATEST RELEASE.

> Did you look at other issues and the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)?
I looked but I couldn't seem to find anything that worked for my issue but I may have missed it.

**Describe the bug**
After putting in my settings I run it and it selects the quest but as soon as it gets to the support screen it just stops no matter how I set my support settings.

**Screenshots*
This is my first time using this app so I don't know if they are relevant but here are my current settings.
Sorry if the images are too big.

![Fate1](https://user-images.githubusercontent.com/71303101/93159735-7da9c880-f6d4-11ea-8904-5b4648f0827b.jpg)
![Fate2](https://user-images.githubusercontent.com/71303101/93159842-ba75bf80-f6d4-11ea-8b7c-5d2b8ff79b71.jpg)
![Fate3](https://user-images.githubusercontent.com/71303101/93159890-db3e1500-f6d4-11ea-8830-67f42c291fe6.jpg)
![Fate4](https://user-images.githubusercontent.com/71303101/93159978-00cb1e80-f6d5-11ea-925b-a8ce0add9cce.jpg)
![Fate5](https://user-images.githubusercontent.com/71303101/93160025-16d8df00-f6d5-11ea-96bf-6a39b8055ffc.jpg)
![Fate6](https://user-images.githubusercontent.com/71303101/93160062-2bb57280-f6d5-11ea-8a3b-e0d40c525bc5.jpg)

**Video**
Here is a video showing what I'm talking about I even move the screen up and down manually to see if that does anything but it didn't.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/71303101/93161406-1b52c700-f6d8-11ea-8bb0-3a2ad0c5d6d3.gif)

**Device Info (please fill atleast 'Device model'):**
Samsung Galaxy S10e

**Comment by MathewSachin** [comment]
Look at the Troubleshooting guide again. You have to make FGO and FGA fullscreen.
This was linked in that guide: https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Game-Area-detection
