### ISSUE TITLE
Can't select preferred servants

### ISSUE THREAD

**Issue by ElvenSenpai** [MathewSachin/Fate-Grand-Automata#405]
> MAKE SURE YOU TESTED THE LATEST RELEASE.

> Did you look at other issues and the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)?

**Describe the bug**
Whenever i try to choose a preferred servant to select it i get nothing but a white text box

**Screenshots**
![image](https://user-images.githubusercontent.com/33261834/93245330-7a254880-f78b-11ea-82a6-e5a122112da4.png)

**Device Info (please fill atleast 'Device model'):**
Using Bluestacks with this settings

 - Device model: OnePLus3T
 - Screen size: 1600x900
 - Android Version: Android 7.1
 - RAM: 8GB

**Comment by reconman** [comment]
Click on the ... in the top right corner, select `Extract Default Support Images`.

**Comment by MathewSachin** [comment]
See wiki for details: https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Support-Image-Maker

**Comment by ElvenSenpai** [comment]
Okay, didnt know that, sorry, and thanks for your job! Is amazing
