### ISSUE TITLE
Leaving repetitions blank will cause the app to crash and not want to open again.

### ISSUE THREAD

**Issue by sebas1234tt** [MathewSachin/Fate-Grand-Automata#406]
Left repetitions blank on accident and the app crashed. Gonna have to reinstall.

**Comment by reconman** [comment]
What's your installed version? Is it up to date?

**Comment by reconman** [comment]
This was fixed in 3ffddeb6db4fd57112b44cd79f54d62ffa4f7642, which is already part of the newest app version.
