### ISSUE TITLE
Wave detection error after repeating quest

### ISSUE THREAD

**Issue by ScathachSkadi** [MathewSachin/Fate-Grand-Automata#408]
**Describe the bug**
The script would run fine on the first run, but after tapping the repeat quest, the app would use the commands for the 2nd wave when it is on the 1st wave. The script is set to use normal cards until it kills all enemies on the 1st wave, but on the 2nd turn it would use commands for the 2nd wave.

**Screenshots**
https://ibb.co/kXh0sTR

**Video**
https://www.youtube.com/watch?v=rTAuXHL80JI&feature=youtu.be

**Device Info (please fill atleast 'Device model'):**
 - Device model: [Galaxy S8]
 - Screen size: [FHD+ 2220x1080]
 - Android Version: [Android 9]
 - RAM: [Unrelated]

**Comment by MathewSachin** [comment]
For checking the current wave, it takes photo of the current wave number and matches it with the wave number every turn.
But, on this node, the background behind the wave number is animated, which causes the same wave to be recognized as different.
There's a Stage count similarity option in Fine-tune settings for such cases. Try reducing that.
I think it can fail on any run, not just repeats, but can happen randomly depending on the animation state.

This is the related Lua issue: https://github.com/29988122/Fate-Grand-Order_Lua/issues/382#issuecomment-629859967

**Comment by ScathachSkadi** [comment]
When reducing stage count similarity option to 66% ,it works fine. Problem solved. Closing issue.

**Comment by reconman** [comment]
As comparison, I went to 80 % because it wouldn't work in a few quests because of the background color.
