### ISSUE TITLE
Support Hang Up when Withdraw or accidental "non-repeated" quest

### ISSUE THREAD

**Issue by TryBane** [MathewSachin/Fate-Grand-Automata#409]
Currently, when running with "Withdraw" option turned on, if a Withdraw happens, the app will get stuck on selecting a support. This is caused by the App only following a loop expecting the "repeat" option to be pressed. When the repeat option is pressed, a click on the support you want is all you need to progress to load the stage, but when you choose from the main menu, after selecting a support, a click on the "start quest" button is required. When you Withdraw, the app still follows the process that is used for "repeat" and gets hung up without pressing "start quest" button. This problem also arises from manually clicking to "not repeat" the quest, but still having the app run. When it gets to the main menu, it will click on the node as usual, but only click on the support and not click start quest. The suggestion for fixing this is to create a loop back to main menu clicking if "repeat" is never clicked. You can do this a number of ways, but the simplest would be using a boolean variable (true/false) that is checked in Support window and is set to true when "repeat" is clicked and reset to false when clicking the node in main menu.

Don't really think the device matters for this particular problem, but here's some of the info.
 - Device model: Samsung S9
 - Android Version: Android 10

**Comment by MathewSachin** [comment]
Good catch. I was 3T farming all this time so didn't notice 😅

**Comment by TryBane** [comment]
https://github.com/MathewSachin/Fate-Grand-Automata/blob/fa872020697d990b38f7e57aeaee02b9b1abd684/scripts/src/main/java/com/mathewsachin/fategrandautomata/scripts/entrypoints/AutoBattle.kt#L153

After looking through the code, I saw you used the "isContinuing" boolean I made for the repeat option when it first came out, you can fix this right after this line by setting it to "false" here

**Comment by MathewSachin** [comment]
Did just what you said for the fix

**Comment by TryBane** [comment]
Cool, not sure how releases work on GPlay store, but I assume this isn't live on GPlay store yet?

**Comment by MathewSachin** [comment]
It's not live there yet, but you can get a test APK from GitHub Actions.

https://discordapp.com/api/webhooks/755765515770789941/xeUUK3Q8ulYoQ9ZxgDRDe-CluH0quKRJnCRUw8mP-uekmf1LGHHxKv_eHfWz8Vrjs-aH

It's still building right now

**Comment by TryBane** [comment]
I see, thanks much.

**Comment by MathewSachin** [comment]
Oh sorry wrong link. 😓
