### ISSUE TITLE
App stops itself on wave 2 or 3

### ISSUE THREAD

**Issue by mcshi** [MathewSachin/Fate-Grand-Automata#41]
Hi,

I'm trying to farm with this app; it seems to stop itself on wave 2 or 3 consistently; I end up having to tab to the app and hit "toggle" to get the play/stop button to show up again. The button disappears when I have more than 4 skills used in a row. I deactivated battery optimization per dontkillmyapp.com instructions, and I'm not sure what else I can do. I'm running a Samsun S8 with WQHD+ resolution

Thanks!

**Comment by MathewSachin** [comment]
I'm working on a few performance fixes right now. Hopefully, that'll solve the problem.

**Comment by MathewSachin** [comment]
We've done a few performance improvements and want to confirm with a  few more users before releasing a new version.

You can download the APK from this page: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/84478986
It'll be in a zipped folder.

Please, let me know if the app works fine now or not.

**Comment by mcshi** [comment]
Hi,

I ran the app through a full bar of AP on three different farming quests and there were no problems. Thank you so much!
