### ISSUE TITLE
App working but not attacking on Quest.

### ISSUE THREAD

**Issue by ChaseYamamiya** [MathewSachin/Fate-Grand-Automata#411]
I followed the guide posted by @reconman in YouTube and was able to get the app working on FGO.
But for some reason it's not starting the quest that I choose, and it doesn't automatically attack the enemies but it can activate my servants skills.

I tried looking at some fixes in the thread but to no avail.
Anyone can help me? I'm currently playing on an OPPO F9 Android

**Comment by MathewSachin** [comment]
https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting
