### ISSUE TITLE
No Selecting Support

### ISSUE THREAD

**Issue by Nathrath11** [MathewSachin/Fate-Grand-Automata#412]
hello so I did everything right, it picks the quest but then when arrived to the support list, it doesn't search for the servant I put in as preferred (Skadi), and the new Gil fest CE, I don't know why it's not working, can any of you help me please and thanks

**Comment by MathewSachin** [comment]
https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting

**Comment by reconman** [comment]
https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting
