### ISSUE TITLE
Clicking in top right corner every skill used.

### ISSUE THREAD

**Issue by fredrikie** [MathewSachin/Fate-Grand-Automata#413]
Just noticed that the bot is clicking in the top right corner after using buffs. It happens every buff and seems like it shouldnt happen cause that consistent click would make it look like a bot. 

Let me know if thats something wrong on my end or an actual bug.

Im using galaxy s20+ 5g

Thanks for the bot!
Ben

**Comment by MathewSachin** [comment]
It's a feature to close unwanted dialogs.

**Comment by fredrikie** [comment]
ahh. is there a way to disable this. looks suspect if it clicks in the top right every skill.

**Comment by fredrikie** [comment]
fair enough. Its a great bot, truly. Thank you for making it.

**Comment by fredrikie** [comment]
https://drive.google.com/file/d/1FOmcMN5Y0eYf1YxdQttJedwW8qtsqyAq/view?usp=sharing

theres a vid of the clicking. just if you were interested in looking. idrc. just an fyi.

thanks again man. do you have a patreon or paypal for donations?

**Comment by MathewSachin** [comment]
Umm, like I said it's a feature. I know it clicks. It has to click somewhere or other problems can happen in my experience developing the script. The top-left corner is the safest place to click without messing up anything else.

I have a PayPal link for donations: https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Donations
Thank you!

**Comment by fredrikie** [comment]
It def clicks in the top right though, not top left. Right next to the master's image basically off of the playable screen. But hey, you built it so I trust your judgement. It's just too suspect for me. DW could easily link top left clicks after skills to use of a bot and I'm too paranoid lmao.

Def worth supporting though. It's crazy how much functionality you packed into this. I build a shitty python bot a while back for farming EXP but it ain't even close to this.

**Comment by MathewSachin** [comment]
Ah, I'm just turning insane answering so many questions. It's top-right corner. My bad.

**Comment by fredrikie** [comment]
No worries. Thanks again for the bot. It's hella nice. Hope you keep at it.

Have a nice week.
