### ISSUE TITLE
Bug Report: It can't select any support

### ISSUE THREAD

**Issue by pablojose94** [MathewSachin/Fate-Grand-Automata#414]
**Describe the bug**
As the title says, the app can't select any support. It gets stuck in the support list. I tried with all the options and even the simplest one doesn't work.

**Screenshots**
My configuration:
![119454147_2952211914878458_3189003687260512705_n](https://user-images.githubusercontent.com/71397543/93364130-cb761c00-f80d-11ea-9034-b539ca390a01.jpg)

**Video**
https://drive.google.com/file/d/10Ad674zaS-qKWmvoHLqA9ob_piV8AFcN/view?usp=sharing

Device model: Samsung galaxy s20
Screen size: 1440x3200
Android version: Android 10
Ram: 8gb

**Comment by MathewSachin** [comment]
Regions are wrong BTW. By any chance, did you turn ON Ignore notch calculation.
The Troubleshooting guide you were asked to see before opening the issue details when you need to use it. It isn't required for your case.

**Comment by reconman** [comment]
Have you tried the stuff in https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting?

Seems like the game area is detected incorrectly.

**Comment by pablojose94** [comment]
> Regions are wrong BTW. By any chance, did you turn ON Ignore notch calculation.
> The Troubleshooting guide you were asked to see before opening the issue details when you need to use it. It isn't required for your case.

**Comment by pablojose94** [comment]
I turned on "Ignore notch calculation" because the app can't select any NP box. I'm doing a video right now
