### ISSUE TITLE
Toggle Service freezes screen on emulator

### ISSUE THREAD

**Issue by CountDookie** [MathewSachin/Fate-Grand-Automata#415]
Tried it on BlueStacks, for some reason the screen froze after I clicked Toggle Service, FGO and the app are still running, but I can only see the message "Fate/Grand Automata will start capturing everything..." without being able to click anything. My BlueStacks is updated to the latest version and the Android OS there is version 7
![freeze](https://user-images.githubusercontent.com/43048825/93371382-447e6f00-f820-11ea-9743-739aa48f3250.PNG)

**Comment by reconman** [comment]
https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Running-on-Emulators#bluestacks
