### ISSUE TITLE
Lottery 10 Spin Location

### ISSUE THREAD

**Issue by the3dsandwich** [MathewSachin/Fate-Grand-Automata#418]
I know this is more like a joke, but if the click location can be a little bit to the left...

![Screenshot_1600312532](https://user-images.githubusercontent.com/32169552/93416005-5d962700-f8d7-11ea-958e-eb28eb0200f4.png)

**Comment by MathewSachin** [comment]
Seriously speaking, a bit to the left might go outside the 10x summon button.

It's clicking at the perfect place for NA right now. YKWIM.

**Comment by the3dsandwich** [comment]
Ah. If it's clicking in the right place for NA then it's perfect ;)
