### ISSUE TITLE
FGA keeps clicking in the same spot

### ISSUE THREAD

**Issue by Brangelz** [MathewSachin/Fate-Grand-Automata#422]
**Describe the bug**
  The app opens the "Select Support" window and starts clicking in the same place forever, even in battle. Already tried with and without the full screen, the same thing happens. It's configured as Battle, not as Lottery.

**Video**
https://youtu.be/VYFsuV_1uYs

**Device Info:**
- Device model: Samsung Galaxy S10e
- Screen size: 1080 x 2280
- Android Version: 10.
- RAM: 6GB

**Comment by MathewSachin** [comment]
You're using another recorder alongside FGA which can mess things up.
Can you try restarting your phone and not use that other recorder or something else that accesses the screen and try running FGA?

**Comment by MathewSachin** [comment]
For reporting bugs, there is an in-built recorder in the app

**Comment by Brangelz** [comment]
Sure, I'll do it right now

**Comment by Brangelz** [comment]
Whaaaat, worked perfectly! I wasn't trying to record before and it kept making the same mistake, perhaps one of the apps wasn't on full-screen, or just the restart of the cellphone. Anyway, thanks for the attention and for programming FGA.
