### ISSUE TITLE
Unexpected Error: Not a directory

### ISSUE THREAD

**Issue by Kibouo** [MathewSachin/Fate-Grand-Automata#424]
> MAKE SURE YOU TESTED THE LATEST RELEASE.

Downloaded via play store. No update available, thus latest version.

> Did you look at other issues and the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)?

No hits for the error message in the existing issues. No guide section applies, aside from "It did work before". This doesn't seem to be a battery saver issue tho.

**Describe the bug**
When pressing the play button, the script exits with following error message:
```
Not a directory

java.io.IOException: Not a directory
    at java.io.UnixFileSystem.createFileExclusively0(Native Method)
    at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
    at java.io.File.createNewFile(File.java:1000)
    at b.a.a.b$a.c(com.android.tools.r8.jetbrains.kotlin-style lambda group:19)
    at k.h.getValue(LazyJVM.kt:6)
    at b.a.a.b.c(Unknown Source:2)
    at b.a.a.b$a.c(com.android.tools.r8.jetbrains.kotlin-style lambda group:20)
    at k.h.getValue(LazyJVM.kt:6)
    at b.a.a.b.b(Unknown Source:2)
    at b.a.a.a.b$a.x(com.android.tools.r8.jetbrains.kotlin-style lambda group:45)
    at b.a.a.a.h.i.b(SharedPreferenceReadOnly.kt:1)
    at b.a.a.a.b.f(Unknown Source:7)
    at b.a.a.c.a.a.w(AutoBattle.kt:22)
    at b.a.b.b.c(EntryPoint.kt:2)
    at k.n.a.run(Thread.kt:1)
```

- It used to work (used it this morning still)
- Happens regardless of which autoSkill is chosen
- Only happens with `Script Mode: Battle`
- Reboot didn't help
- Device has enough free storage

**Screenshots**
![image](https://user-images.githubusercontent.com/25766329/93534812-14c98700-f946-11ea-98be-b646be8bd12a.png)

**Video**
Battle script doesn't get to start, so not applicable.

**Device Info (please fill atleast 'Device model'):**
 - Device model: Huawei P8 Lite (2017) PRA-LX1
 - Screen size: 1920 x 1080
 - Android Version: v8.0.0
 - RAM: 3GB

**Comment by MathewSachin** [comment]
Did you hide the folder from your file manager? I recall someone doing that and the app wasn't able to access the files then.
Other than that, did you delete any Servant/CE/Friend images which are used in your condos?

**Comment by Kibouo** [comment]
Haven't changed anything regarding the file system.

Servant/CE/Friend dirs are present and contain the needed pictures (dirs are at `/SD Card/Fate-Grand-Automata/support`).

The app has storage permissions enabled.

**Comment by MathewSachin** [comment]
Did you move the dirs to SD Card recently? I've not done any SD Card check in the code, so not sure how that would work.
Don't have an SD Card with me right now to check either. So, the most obvious suggestion would be to try copying that folder to internal storage and see if that works.

**Comment by Kibouo** [comment]
Didn't make any conscious changes to the file system, so no I didn't move stuff. Tried copying to internal, but that didn't help.

However, I did get it to work by force closing the app via Android settings. The problem is resolved, don't know the cause tho :thinking:

**Comment by MathewSachin** [comment]
Hmm, I was also thinking it shouldn't happen unless some permission issue or something happens.
Ah, it's a Huawei phone. Could be something like Huawei's battery optimization killing the app and it then reviving in a corrupted state 🤔 
Huawei and Xiaomi do mess with background apps and AccessibilityServices. So, you should turn battery optimization off for the app as said in the Troubleshooting Guide for a smooth experience. If you want to keep them ON, you might be able to get away with clearing cache for the app.

**Comment by Kibouo** [comment]
Already had battery saving settings changed prior to this occurring.On 18 Sep 2020 19:37, Mathew Sachin <notifications@github.com> wrote:

Hmm, I was also thinking it shouldn't happen unless some permission issue or something happens.

Ah, it's a Huawei phone. Could be something like Huawei's battery optimization killing the app and it then reviving in a corrupted state 🤔

Huawei and Xiaomi do mess with background apps and AccessibilityServices. So, you should turn battery optimization off for the app as said in the Troubleshooting Guide for a smooth experience. If you want to keep them ON, you might be able to get away with clearing cache for the app.
