### ISSUE TITLE
Lottery for KR server

### ISSUE THREAD

**Issue by Lemonlimespicyashell** [MathewSachin/Fate-Grand-Automata#428]
Can you make the lottery function available in the KR server? Thank you always for making a great tool.

**Comment by MathewSachin** [comment]
I need images. See https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Lottery

One for empty lottery box, before resetting it.
Another for when Present Box full.

I'll also ping @sleeping-player @ScathachSkadi

**Comment by sleeping-player** [comment]
![Screenshot_20200918-143447_FateGO.png](https://user-images.githubusercontent.com/69798206/93618037-bbc72500-fa11-11ea-97cc-42a89d12b883.png)
Sorry I'm late.

**Comment by MathewSachin** [comment]
@sleeping-player no problem. ah, I want an image of an empty lottery box. before you reset.

Also, the script as it is right now is expected to be used for boxes after 10 anyway (when grand prizes are over) so you can take your time I guess.
Once your first box is empty, post an image of that.

**Comment by sleeping-player** [comment]
Oh i thought wrong image..

**Comment by sleeping-player** [comment]
![1600445828 (3).png](https://user-images.githubusercontent.com/69798206/93621722-f4b5c880-fa16-11ea-86a6-41efe6ae44f6.png)![1600445828 (2).png](https://user-images.githubusercontent.com/69798206/93621726-f5e6f580-fa16-11ea-9fea-11a8b940606d.png)
I asked and someone sent this

**Comment by sleeping-player** [comment]
Oh sorry bulletins mobile restrictions..

**Comment by sleeping-player** [comment]
![Screenshot_20200919-011627.png](https://user-images.githubusercontent.com/69798206/93621978-52e2ab80-fa17-11ea-8e4c-ed78c7862797.png)![Screenshot_20200919-010201.png](https://user-images.githubusercontent.com/69798206/93621982-5413d880-fa17-11ea-9080-9cc656f31390.png)
Oh no I think this is original size on that board..

**Comment by MathewSachin** [comment]
These images are fine. I'll get started.

**Comment by sleeping-player** [comment]
Thanks. I'll replace it in high resolution in a few days..

**Comment by MathewSachin** [comment]
Nah, this resolution should work good enough. Give it a try after the build is ready.

**Comment by MathewSachin** [comment]
I forgot to post a link to the CI build: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/261518424

Try this and let me know if it works. After that, I'll do a release on PlayStore by tomorrow

**Comment by ScathachSkadi** [comment]
Oh I was sleeping early yesterday. Testing now.

**Comment by ScathachSkadi** [comment]
Looks like it's working fine.
