### ISSUE TITLE
Severe FPS drop when starting the script for Battle.

### ISSUE THREAD

**Issue by NineRingsGZ** [MathewSachin/Fate-Grand-Automata#432]
**Describe the bug**
When hitting the Play button to start the battle script. FPS drops to 1-2  and stays that way until I hit stop. Usually I stop it pretty early. 
I am playing on Nox. I made sure I'm on Android 7. I get root on so the App does work. But not sure when it gets such a severe FPS drop when I start the battle script. I tried switching phone models when emulating to see if it helps but unfortunately it didn't.
My current Nox version is 6.6.0.0

**Screenshots**
https://i.imgur.com/ja9rWc7.png
This is just the standard with the FPS count in the corner. I can hover around 35-50 just idling. Starting the script drops it to 1-2 FPS.

**Device Info (please fill atleast 'Device model'):**
I'm using Nox. 
It is currently emulating Samsung S8+

**Comment by MathewSachin** [comment]
Doesn't FGO run at 30fps max? You using a modded APK or something?

You didn't tell your system specs or a video of fps dropping, so how can we know if it is even happening?

**Comment by NineRingsGZ** [comment]
> 
> 
> Doesn't FGO run at 30fps max? You using a modded APK or something?
> 
> You didn't tell your system specs or a video of fps dropping, so how can we know if it is even happening?

I updated from APKPure so I want to say no? Think its just me being stupid and giving bad info.

I apologize for not putting that information.
Specs
CPU-Ryzen 5 2600x
Mobo- Rog strix x470-f gaming
16G Ram
GPU- Nvidia Geforce GTX 1080

Heres a video.
https://youtu.be/CU3NvlNzQPE
I am actually not sure why I get that Card error. Arash was suppose to NP. 
I stop the script pretty early on. After finishing the battle. I start the battle again and attempt the script again but it shows the same results.

**Comment by MathewSachin** [comment]
The system specs are definitely good. Mine isn't even good but doesn't straight up lag like this. So, something else might be interfering.

Card error was due to the cards not coming up in time because of the FPS drop.

I'm assuming you're on Windows. Does the TaskManager show anything weird?

Otherwise, you can try BlueStacks as it doesn't need root to take screenshots which is comparatively slower.

**Comment by NineRingsGZ** [comment]
Yes I'm windows.

Task Manager just shows my CPU going up by like 10% whenever the FPS drop happens. It goes back down when it becomes smooth again like a normal run.

**Comment by NineRingsGZ** [comment]
I can now confirm it works on Bluestacks. Strange that it happens on Nox.

**Comment by reihunter360** [comment]
Nox is a resource hog, even on high spec'd computers. 
Bluestacks is lightweight enough for your emulator needs. (Ads though.)

**Comment by MathewSachin** [comment]
I confirmed with other users and also ran Nox on my laptop to check and I'm not seeing any performance drop with FGA.
So, I'll just write it off as something very specific happening on your system
