### ISSUE TITLE
Auto-resume script after performance hiccup

### ISSUE THREAD

**Issue by blind51de** [MathewSachin/Fate-Grand-Automata#433]
So depending on your phone, you may get intermittent periods where the game freezes up (except for the music) the longer the app is in service. This started with the engine update. I don't know if it's a phone make issue or a need-more-than-2GB-ram issue but when it happens, the script:
a) pauses at card selection screen until you input manually or,
b) if doing skills it goes off the rails and just facecards until the wave is over. 
In the end, you have to keep babysitting the phone in case something happens and not just leave it for a long period.

So while it's easy to write the problem off as "Get a better phone", I'm hoping that in one of these scenarios that the app can notice its inputs didn't go through correctly and resume where it left off. 

My Samsung is less than two years old, in case you do write it off that way.

**Comment by MathewSachin** [comment]
I myself 'Got a better phone' after the engine update, so, this isn't something I'll personally work on now. Maybe someone else can. 
I can't think of a way to detect lags anyway. My old phone had 3GB and still lagged. 2GB is like minimum requirement for FGO IIIRC. Running anything other than FGO with that much RAM is tough.

**Comment by blind51de** [comment]
Maybe if the battle and turn haven't changed and everything is inactive as though paused, it can loop and redo the old inputs? That would solve the issue of lagging at card selection.

**Comment by reconman** [comment]
Repeating skills would result in unexpected behavior when you've used a Servant's skills and then replaced it with Order Change. You would trigger the replacement's skills instead of the original one. And also you would have to close all the messages about skills being in cooldown.

I don't think there's any good solution we could come up with.

**Comment by MathewSachin** [comment]
Aside from the problems reconman pointed out, FGO itself is lagging on your device, so there's not much we can do.
