### ISSUE TITLE
JP Gift Box image

### ISSUE THREAD

**Issue by sleeping-player** [MathewSachin/Fate-Grand-Automata#435]
#397
![Screenshot_20200919-172859](https://user-images.githubusercontent.com/69798206/93662926-c1b71780-fa9e-11ea-9fbf-809b7ce7df47.png)
![Screenshot_20200919-172745](https://user-images.githubusercontent.com/69798206/93662927-c4197180-fa9e-11ea-8ead-6c0d2057de13.png)
![Screenshot_20200919-172517](https://user-images.githubusercontent.com/69798206/93662928-c54a9e80-fa9e-11ea-9705-ba2da6c2ec45.png)

Somebody asked from JP server unable to get gift box x1 automatically.
I heard some feature can be done from fallback image on NA,
however this time, no image is uploaded from JP.
So he sent these images.
He said 2 to 4 works correctly.

**Comment by MathewSachin** [comment]
I had confirmed with people that it works fine on JP server 🤔 
The font is pretty much same as for NA.
I'll check again though

**Comment by MathewSachin** [comment]
@sleeping-player Can you get me the 2-4 images too.
The `x1` is just matching at the borderline for JP on my phone.
I think I should check the other images too.

**Comment by sleeping-player** [comment]
![Screenshot_20200919-180641](https://user-images.githubusercontent.com/69798206/93663859-b5828880-faa5-11ea-9693-6f0811d6b546.png)
![Screenshot_20200919-180634](https://user-images.githubusercontent.com/69798206/93663861-b87d7900-faa5-11ea-8764-d94a22e2a5f6.png)

**Comment by MathewSachin** [comment]
I added new images for all 1-4 for JP.
But, a PlayStore release was already in progress, so JP users will have to wait till next release.
Or, you can give them a CI build from GitHub Actions once it is ready.

**Comment by sleeping-player** [comment]
OK
