### ISSUE TITLE
Skip the dying scene

### ISSUE THREAD

**Issue by kohcheeyit** [MathewSachin/Fate-Grand-Automata#437]
Can you make the app auto skip when servant is dying , For example I use Chen Gong np kill my own servant or use Arash to kill himself  ,it need spend few second to load the dying scene  if not click on the screen. This game only allow you to auto skill when enemy servant but dun have auto skip for self servant
![image](https://user-images.githubusercontent.com/56528815/93668545-75c89a80-fabf-11ea-8aa5-aa0d9b29970a.png)

**Comment by MathewSachin** [comment]
Another issue for the same thing.
Not possible: See #393 and linked issues on it.
