### ISSUE TITLE
Can't start Battle script (Dialogs don't show) on LG phones

### ISSUE THREAD

**Issue by mezedjjk** [MathewSachin/Fate-Grand-Automata#439]
https://youtu.be/furUmZJryps

V50S (LM-V510N)

battle script non-pop up and Does not run

Problems after the latest update

**Comment by MathewSachin** [comment]
Saw that a few minutes before. LG phone's seem to not follow standard Android behaviour in AlertDialogs.
Already have a fix in place. A new release should be up by tomorrow.

**Comment by MathewSachin** [comment]
New update with the fix is live on Play Store now.
So, I'm closing this issue now.

**Comment by mezedjjk** [comment]
thx!

**Comment by mezedjjk** [comment]
https://youtu.be/u_Ng-zo3q5I

The problem remains.  It doesn't disappear, but it doesn't pop up. :(

**Comment by MathewSachin** [comment]
LG phones are really messing up something here.
I'd need help from someone with an LG phone and development knowledge to find why `AlertDialog` of `APPLICATION_OVERLAY` type isn't showing up.
I don't know if LG has completely messed with the standard behaviour or there is a setting for configuring this either.

**Comment by mezedjjk** [comment]
I think it's a problem that happens with case by case in LG V series. There are some people who can do it. :(

**Comment by MathewSachin** [comment]
https://www.lg.com/us/support/help-library/lg-g7-thinq-gaming-tools-CT10000027-20150726480680

There is a game mode in LG phones.
And, it says it has the ability to TURN OFF ALERTS. That should be it. See if turning that OFF works.

**Comment by mezedjjk** [comment]
solve. LOL

**Comment by MathewSachin** [comment]
Customer: I want a smartphone
LG, Samsung, Xiaomi, Huawei: Here's you dumbphone 🤣

**Comment by mezedjjk** [comment]
Thank you for solving the cause. a solution too simple. LOL

**Comment by MathewSachin** [comment]
Have added this to the Troubleshooting Guide, so closing
