### ISSUE TITLE
Skill Target Always Defaulting to Servant 3 

### ISSUE THREAD

**Issue by dsalazar6** [MathewSachin/Fate-Grand-Automata#440]
I barely encountered this issue this morning, so I don't know what changed.
I have a skill config set up to apply buffs through both servant skills and master skills, but when running the script **any targeted skill ALWAYS goes to servant 3**. I had not changed the config recently, but even after deleting and remaking that config I get the same problem. I also tested a new config targeting a different servant but the targeted skill STILL go to servant 3. This happens every time I start the script, and I get no noticeable FPS drop so no lag is responsible.
**The command config in question: d1g1l14,#,ef1c4,#,hi1j14**

 - Device model: Moto G5 Plus
 - Screen size: 1080 x 1920 pixels
 - Android Version: Android 8.1.0
 - RAM: 2GB

**Comment by MathewSachin** [comment]
Did you read the Troubleshooting guide?:

> Uses skills on wrong servant or doesn't use skills at all
Do you have skill confirmation ON in FGO? If so, either turn that OFF or turn ON More options/Skill confirmtaion in FGA.

**Comment by dsalazar6** [comment]
I've had skill confirm OFF in FGO for years now, but for some reason it was ON in the autorun app. Considering I did not change settings since last night I assumed the same settings I've been using for days would still be saved.

**Comment by MathewSachin** [comment]
You changed it by accident then. There's no way it can turn itself ON automatically.
