### ISSUE TITLE
Getting Supports to Work

### ISSUE THREAD

**Issue by Serozyne** [MathewSachin/Fate-Grand-Automata#441]
Sorry if this is a stupid question but despite fiddling with the settings the support screen never picks the servant properly but just sits there instead. I've even toggled the app settings to make the apps fullscreen because I saw that it worked for someone else, but the entire macro decides to not work when that happens. I'm not sure if this counts as a bug but I don't want to flag it as one in case I'm just doing something stupid. The rest of the macro works great, it just stops at that one specific point each time.

**Comment by the3dsandwich** [comment]
Did you extract default support image (AutoSkill, top right button)? Is the game server set properly to match your server (more options)?

**Comment by Serozyne** [comment]
The server is proper, but I can't find the top right button. There's just import and export files, is it one of those?

**Comment by Serozyne** [comment]
Okay so I've made that I've done both of those things but it still refuses to automatically choose a servant.

**Comment by MathewSachin** [comment]
You want help or not?
No phone model. No video with debug mode.

**Comment by Serozyne** [comment]
Galaxy S10
![record_1](https://user-images.githubusercontent.com/41091192/93693427-52085300-fac5-11ea-86b1-53840cd666ac.gif)

**Comment by MathewSachin** [comment]
So, you didn't read the Troubleshooting guide: https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting
