### ISSUE TITLE
Quest Completed Screen not detecting

### ISSUE THREAD

**Issue by the3dsandwich** [MathewSachin/Fate-Grand-Automata#442]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
In Battle, if the current screen is item drop (the one you want to screenshot), if you con't decide to screenshot drops and somehow was stuck on the screen, FGA won't detect it nor click to skip it.

**Screenshots**
![Screenshot_1600561986](https://user-images.githubusercontent.com/32169552/93691713-f0270800-fb1b-11ea-97da-332a9e090e32.png)

**Video**
[recording](https://youtu.be/RP_w0QdlS2Q)

**Device Info (please fill at-least 'Device model'):**
 - Device model: [Pixel 2 API 30(Android Studio Emulator]

**Comment by the3dsandwich** [comment]
I think it's because the `mat_rewards.png` is missing for TW?

**Comment by the3dsandwich** [comment]
Just had it stuck at this screen too

![Screenshot_1600563908](https://user-images.githubusercontent.com/32169552/93692029-6af22200-fb20-11ea-88ec-13661c89adf0.png)

**Comment by MathewSachin** [comment]
Right, images for both screens aren't present for TW

**Comment by MathewSachin** [comment]
I cross-checked with KR and these 2 seem to be the only missing ones.
Can you take this up?

**Comment by the3dsandwich** [comment]
Sure! I'm on it

**Comment by the3dsandwich** [comment]
It's supposed to look like this right? I tried cropping it in different sizes but just couldn't get it to detect. Maybe I'm doing something wrong?

![mat_rewards](https://user-images.githubusercontent.com/32169552/93706176-45800b00-fb56-11ea-9e4f-baab6f63c9ab.png)

**Comment by MathewSachin** [comment]
Try with this:

<img width="62" alt="tw" src="https://user-images.githubusercontent.com/10654537/93706297-79e9cc00-fb42-11ea-933b-5ea84b1a8720.png">

The image size seems wrong to me. Before cropping, resize the original image to 1280x720
