### ISSUE TITLE
Choose Script Mode when starting script

### ISSUE THREAD

**Issue by gogito** [MathewSachin/Fate-Grand-Automata#447]
I'm wondering if it's possible to choose the mode when starting the script in-game. Should be a much better experience.
For example, I can choose to start script, choose my farm script. Let it run for a few times. Then stop the script and then change to lotto opening mode to open box. Then I can stop it and switch to the gift box mode. When that is done, I can start the farm script again.

Currently, each time I want to change mode I will have to open the app again. Granted it's not very important but would be a much better way of handling things.

I think another way of doing this would be to put some of the mode on the battle script selecting popup.

**Comment by reihunter360** [comment]
Like holding down on the float-y button to bring up options before you tap on it?

**Comment by MathewSachin** [comment]
You can change Script Mode from the notification without having to open FGA. That's the best realistically possible.

Putting Script Mode along the AutoSkill Picker in the same dialog was hell for me when I tried. Android's UI library is too shitty for things like that right now. It's a ton of code to write which I don't think is worth for this.

I also tried showing it on holding down on the Play button, but that UX felt weird since you also have to hold down for dragging.

**Comment by reihunter360** [comment]
Repitouch (the old macro i used) had 4 buttons, 1 was an anchor to drag the entire float-y rectangle around. 1's a star for menu options (hold click lets you kill the float-y app), a Play button and a Record Button. (The play button changes to Pause when a script is being replayed, and the Record button turns into a Stop Button.)

Could probably be like that? A 2nd button to allow for choosing scripts from a dropdown menu?

**Comment by MathewSachin** [comment]
Having another button for that would definitely be convenient. But, for our use-case it has problems:

We already have 2 buttons. One is Play/Stop, other is the Pause button which is opt-in.
Problem with multiple buttons is overlapping parts of FGO which FGA needs to look at or click on. Not everyone has a non-16:9 phone to place it outside FGO area.
There were many people misplacing the Play button over something important and complaining that the app doesn't work on GitHub Issues and Gamepress, I don't want to increase those cases by there being more buttons.

I personally think that the buttons in the notification should be convenient enough.

**Comment by reihunter360** [comment]
Oh, if its going to be on the notification bar, why not also put the "Region" up there as well. (To know which one is active and can be changed from there if necessary)

**Comment by MathewSachin** [comment]
The region setting doesn't exist in the latest version.
It's automatically detected from the package name of the app (FGO) running in the foreground.

**Comment by gogito** [comment]
Hmmm, I have limited experience in coding Android so I'm not sure if I'm understanding you correctly but my suggestion of putting script mode in the auto skill chooser was more like treating the Mode as a Script (UI wise). As in say a user has 2 script, normally it would shows as:
Script 1
Script 2

Now it would show as

Lottery
Gift Box
Summon
Script 1
Script 2

So now the user can choose the options using the old UI and the app will take care of the implementation.

**Comment by MathewSachin** [comment]
> If not possible then choosing from the notification would be great as well.

This is already present in the latest release.

I was thinking of Showing script mode as a dropdown and if Battle is selected, then show AutoSkill configs, but then also make sure that when mode is Battle, a AutoSkill config should always be selected. And, a few more cases and the complexity didn't feel worth it.

> Lottery
Gift Box
Summon
Script 1
Script 2

This way should be pretty easy to do. But, there are 5 types of scripts and on my phone, the dialog box shows 4 at a time.
Keeping Lottery, FP, etc. at the top would bury down the AutoSkill scripts and vice-verse.
Can't think of a good trade-off here.

**Comment by reihunter360** [comment]
Why not if you tap it on the Notification Bar, you can just cycle through the main scripts?
