### ISSUE TITLE
Stuck at "FGA will start capturing everything that's displayed on your screen"

### ISSUE THREAD

**Issue by whittu** [MathewSachin/Fate-Grand-Automata#448]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
I have FGA set up following the tutorial video and when I click toggle service, I was prompted to enable Accessibility which I did. After doing so, I click toggle service again and get the "FGA will start capturing everything that's displayed on your screen" popup. When I click start now, it freezes and  I cannot click anything after that. I do not get any play button which is suppose to happen according to the tutorial video. This bug happens with and without FGO running in the background. When I click cancel on the above dialogue, it doesn't freeze so only clicking start now freezes on the "FGA will start capturing everything that's displayed on your screen" popup. 

**Screenshots**
[Picture](https://i.imgur.com/NRtWb9I.png)

**Device Info (please fill at-least 'Device model'):**
 - Device model: BlueStacks 4.2220.0.1109 32bit
 - Screen size: 2560x1440 Landscape
 - Android Version: Android 7.1.2 Nougat (I think since bluestacks doesn't really say so anywhere unless I missed it)
 - RAM:  4GB

Additional detail since device is Bluestacks
 - CPU: 4 Cores
 - Profile: OnePlus 5
 - Graphics engine: Performance (legacy mode)
 - Graphics renderer: DirectX
 - GPU settings: Prefer dedicated coupter graphics (NVIDIA only)
 - ASTC texture: Disabled 
 - FPS: 60
 - ABI settings: Auto

**Comment by MathewSachin** [comment]
>  I read the Troubleshooting Guide

> Graphics renderer: DirectX

> Performance (legacy mode)

![image](https://user-images.githubusercontent.com/10654537/93735718-87af5800-fbfb-11ea-99f7-f30050d0a134.png)

**Comment by whittu** [comment]
You are indeed correct. I guess I didn't read the part under Windows and just read bluestacks instead. Sorry for wasting your time.
