### ISSUE TITLE
Can't start battle on LG G7

### ISSUE THREAD

**Issue by BaOH2** [MathewSachin/Fate-Grand-Automata#455]
From LG G7 (LM-G710ULM)
Ram: 4 gb
Android 8
Hello guys, I downloaded the app from google play, and, although I already reinstalled, I can't get the app to work. I followed the video pinned on the main page. Maybe I'm missing something? Sorry if the answer is too obvious. Thanks for your time
![Screenshot_2020-09-20-22-39-44](https://user-images.githubusercontent.com/71625956/93740297-1346cb80-fb9f-11ea-8144-fe4fef32306f.png)

**Comment by MathewSachin** [comment]
Didn't read the Troubleshooting Guide: https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Game-Area-detection#case-4-your-phone-is-android-7-or-8-and-has-a-notch

Notch not supported before Android 9
