### ISSUE TITLE
How to update app?

### ISSUE THREAD

**Issue by welknair** [MathewSachin/Fate-Grand-Automata#458]
I see both here and on the Google Play Store that version v0.22.1 is out, while my app is still in v0.20.0. When I navigate to the page on the Google Play Store, it just shows the "Open" button instead of "Update" as it should. I've restarted the google play store, I've restarted my phone, I've cleared the cache of the play store and play store services, restarted phone again, etc. and the update never shows up. I updated a few other apps just fine since encountering this issue. I've been googling for the past half-hour with no luck, but I'm pretty sure it's something silly that I'm missing. Apologies if this is a silly question, I did search through current and closed issues to see if anyone else had asked about this, but couldn't find one. Similarly, I found no reference to this in the troubleshooting guide. 

The only possible explanation I could find is if it was downloaded as an APK instead of through the play store. I don't actually recall if I installed it from the play store or an APK directly from the website if such was previously available (it doesn't seem to be now), but in either case I've successfully received at least one update previously. I'm pretty sure that simply reinstalling the app would get me the latest version, but I'm not aware of a good way to export and import my various battle scripts. I don't know how this data is stored on phone; if I reinstall, will my battle scripts persist, or will I need to re-enter them? Of course if this is the only way to get the latest version I can do it, it'd just be nice to avoid the nuclear option.

Device Info:
Device model: Google Pixel 3a
Android Version: 11
App Version: v0.20.0

**Comment by reihunter360** [comment]
In the autoskill menu, there should be an option on the top right. 
Tap on that to bring out Import and Export All.
Export All should dump all your scripts into a folder of your choosing.
Then you can uninstall the app, pick up the newest update from Play Store. 
Afterwards, you can use the import function.
(You still have to set your More Options up.)

**Comment by welknair** [comment]
Ah, thank you very much, I totally missed that UI for import/export!
