### ISSUE TITLE
Stuck on support screen (ignore notch is off)

### ISSUE THREAD

**Issue by HayanShiro** [MathewSachin/Fate-Grand-Automata#461]
Before opening an issue:

[O] I tested the latest release
[O] I looked at other issues (even the closed ones)
[O] I read the Troubleshooting Guide
[O] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
It gets stuck on supports screen even when "ignore notch calculations" is off

**Screenshots**

**Video**
https://youtu.be/_Gy_YYijvLI

**Device Info (please fill at-least 'Device model'):**
 - Device model: Samsung Galaxy S20+
- Screen size: 6.7 inch
- Android Version: Android 10
- RAM: 12GB

**Comment by reconman** [comment]
What is your support preference in the video?

**Comment by HayanShiro** [comment]
It's Rider - Francis Drake

**Comment by HayanShiro** [comment]
> What is your support preference in the video?

It's Rider - Francis Drake

**Comment by OrYangatan** [comment]
I'm having a similar issue (Galaxy Note 10+). From what I've been reading, the punch hole for the front camera counts as a notch so we need to have the "ignore notch" option selected. It works fine in battle, but it stops working on the support screen. 

Disabling the "ignore notch" option doesn't fix it and also causing it to stop working in battles so I'm keeping it on.

See if the enabling the ignore option will fix it for you though.

**Comment by MathewSachin** [comment]
@HayanShiro have you made FGA full-screen?

@OrYangatanThere are people using it just fine on Note 10+, so I'm pretty sure it's a mistake in following the troubleshooting guide: https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Game-Area-detection.
Could even have just searched for Note 10+: https://github.com/MathewSachin/Fate-Grand-Automata/issues/143

**Comment by HayanShiro** [comment]
> @HayanShiro have you made FGA full-screen?

Yes it's full screen
![Screenshot_20200924-181712_FateGO](https://user-images.githubusercontent.com/39473180/94126186-42588800-fe92-11ea-8274-a297859e1884.jpg)

**Comment by MathewSachin** [comment]
I mean not just FGO, but also FGA (this app). Check Settings on your phone.

**Comment by HayanShiro** [comment]
There are people using it just fine on Note 10+, so I'm pretty sure it's a mistake in following the troubleshooting guide: https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Game-Area-detection.

Now I see that I do have a notch. I'll see if turning on "ignore notch" works.

**Comment by MathewSachin** [comment]
You don't have to turn ON Ignore notch for your phone.

**Comment by HayanShiro** [comment]
> I mean not just FGO, but also FGA (this app). 

Making FGA fullscreen made it work again ^-^ thank you so much, Matthew. 

Isn't having a little black gap at the left side of the screen mean that I have a notch(front on screen camera hole)?

**Comment by MathewSachin** [comment]
Your phone does have a notch. Turning ON that setting would Ignore the notch, which only helps in the case where FGO also ignores the notch and extends over it. But, right now FGO is leaving the notch area black, so no need to ignore it.
