### ISSUE TITLE
Servant activating NP on the first wave despite script saying otherwise

### ISSUE THREAD

**Issue by kayanomatsuoka** [MathewSachin/Fate-Grand-Automata#463]
Intended Output: Wipe the first wave with face cards (takes 3-4 turns), clear the second wave with Nitocris's NP and some more face cards (2-3 turns), and then finally clear the 3rd wave with Gil.

My Output: For some reason, Nitocris activates her first two skills (a,b), then unleashes her NP on the second turn on the first wave despite the script not wanting that. I have set Cast Noble Phantasm to none, so there shouldn't be any unexpected NPs.

This is my setup: (support is a waver)
![image](https://user-images.githubusercontent.com/71777932/94032851-f60a3b00-fdf2-11ea-9de2-d0e8bb329222.png)

0,0,0,0,0,#,ab4,x11,#,afeihg1d1jkt14

**Comment by reconman** [comment]
See #462
