### ISSUE TITLE
Start quest button doesn't function until you switch to a new team

### ISSUE THREAD

**Issue by tigerdragon71** [MathewSachin/Fate-Grand-Automata#465]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
Everything else about the app works but whenever it tries to start up a quest after selecting the support, the start quest button will not function until you switch to a new team. Even manually pressing the button does nothing.

**Screenshots**

**Video**

**Device Info (please fill at-least 'Device Model's"):
 - Device model: Samsung galaxy s10+
 - Screen size: 6.4 in
 - Android Version: Android 10
 - RAM: 8gb

**Comment by tigerdragon71** [comment]
https://www.youtube.com/watch?v=q_QZFBIWgDU&feature=youtu.be

**Comment by MathewSachin** [comment]
First of all, having to switch to a different team is a bug in FGO itself.
And, the app handles it well, but, you have configured the regions wrong.

The regions are totally wrong and the app is working by chance. Turn OFF Ignore notch calculation as it is not needed for your phone. Troubleshooting Guide/Game Area detection details on when you need to turn it ON.
