### ISSUE TITLE
NP spam option behaviour changed?

### ISSUE THREAD

**Issue by CptBurtReynolds** [MathewSachin/Fate-Grand-Automata#466]
Noticed yesterday that the NP spam option seemed to no longer only use NPs after all pre-programmed commands had been used, but instead would spam NPs whenver available. This means that if saving NPs for wave 3 but there was a full bar on wave 2 it would be used there instead of waiting.
I'm not sure if this was always the intended way of it working, but the change/bug/feature means that some of my farming runs failed, which was how I'd noticed. I only noticed this occuring yesterday evening (23/9/20). I couldn't see any commits that were recent enough to maybe cause this change so I'm unsure if it's intended behaviour or not. Thanks

**Comment by MathewSachin** [comment]
If you're playing Gilfest on NA, this is pretty much the result of the background animations,
See #462

**Comment by CptBurtReynolds** [comment]
Yeah that's right, missed that one sorry. I'll close this.
