### ISSUE TITLE
Support Emiya's skill upgrade

### ISSUE THREAD

**Issue by Regulusttt** [MathewSachin/Fate-Grand-Automata#467]
With the new mechanism, I think it would be great to add a touch area for skills that have 2 cards like Emiya Third Skill

Tried it with default choice (Target 1 and 2) but the touch missed since the card centered 

![Screenshot_20200924-193829](https://user-images.githubusercontent.com/68319933/94140858-7d60b880-fe9e-11ea-8d1a-8b1d460c7b3d.png)

**Comment by MathewSachin** [comment]
I don't have Emiya on JP.
So, someone check this build and let me know: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/288118983

**Comment by Regulusttt** [comment]
It Work Perfectly, Thanks a lot
