### ISSUE TITLE
Porting the app to Windows

### ISSUE THREAD

**Issue by MathewSachin** [MathewSachin/Fate-Grand-Automata#47]
If we're able to run the app on Windows, we'll be able to use any version of Android on an emulator to play the game.

Due to the way the app is written, we can pretty much share all the code which is not in the Android project.
I already am experienced with writing Windows apps, so I hope this won't be much difficult.
But, don't hope too much on this or expect it to happen soon.
I'll only start working on this once the Android version becomes more stable.

**Comment by MathewSachin** [comment]
Closing in favour of #80.
This solution would require the emulator to be always on screen which isn't very convenient for people without multiple screens.
We're instead planning on adding root support.
FGO JP should work with root by default.
You can use MagiskHide with FGO NA till the engine update arrives.

**Comment by metapea** [comment]
> This solution would require the emulator to be always on screen which isn't very convenient for people without multiple screens.
To be honest as a emu user i don't mind that, if you don't have 12-16gb ram then the emu is mostly likely going to take most of you're ram, leaving you with little space of other programs in the first place.  
I can just leave it running when i'm resting, outside or just doing others things. Come on man, my enhancement request was closed for this.

**Comment by reconman** [comment]
Look into #80, it's much better, trust me. You can minimize the Emulator that way.
