### ISSUE TITLE
Prioritize cards based on critical rate?

### ISSUE THREAD

**Issue by minhducsun2002** [MathewSachin/Fate-Grand-Automata#470]
Before opening an issue:
- [x] No one has asked for this feature before in other issues (even the closed ones)

> ~~If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.~~

_pls don't_

As the title says.
This can be made as an extension of the existing card priority mechanism.

**Comment by MathewSachin** [comment]
Ok. PRs accepted.

**Comment by minhducsun2002** [comment]
Now that I think about it again, this feature might not be really useful. Most of the time, the card type matters so much that critical hits might not even be able to compensate the difference - for example, a critting Buster card never gains NP.

I guess I'll close this, at least until I can figure out a prioritization mechanism that is deterministic enough for actual usage.
