### ISSUE TITLE
Alternate way of retrieving EXP from present box

### ISSUE THREAD

**Issue by clymchi** [MathewSachin/Fate-Grand-Automata#472]
Before opening an issue:
- [x] No one has asked for this feature before in other issues (even the closed ones)

Instead of scrolling down and checking the boxes, could the script instead tap on the exp individually and only scroll once there's nothing on the screen that matches what it's looking for?

I think it would be faster even accounting for the momentary loading after each tap,

**Comment by MathewSachin** [comment]
I'm not that dumb, would have done this already if possible. That's just common sense 😂.
Scrolling code in this app is not precise enough to scroll large amounts right now.
Precise scrolling, even when we do implement, will only be possible on Android 8 and above.

**Comment by reconman** [comment]
@MathewSachin I think they meant actually collecting the EXP cards, which always leads to a Connecting... delay, so it's much slower.

**Comment by MathewSachin** [comment]
I think I misunderstood it before, but having a connecting delay after each receive should be even slower.
