### ISSUE TITLE
Support screen error (3rd time)

### ISSUE THREAD

**Issue by HayanShiro** [MathewSachin/Fate-Grand-Automata#473]
Before opening an issue:

[O] I tested the latest release
[O] I looked at other issues (even the closed ones)
[O] I read the Troubleshooting Guide
[O] I'll fill this template properly

Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

Describe the bug
It gets stuck on supports screen even when FGA is full screen. I'm sorry for coming back with same issue for 3rd time but it keeps on stopping on me (×-×)  

Screenshots

Video
https://youtu.be/_Gy_YYijvLI

Device Info (please fill at-least 'Device model'):

Device model: Samsung Galaxy S20+
Screen size: 6.7 inch
Android Version: Android 10
RAM: 12GB

**Comment by MathewSachin** [comment]
Is it not the same video?
Post a video of when you made FGA full-screen.

**Comment by HayanShiro** [comment]
https://youtu.be/6tIkXFqlKGc
Here it is, but it looks the same.

**Comment by HayanShiro** [comment]
I'm sorry I uploaded the wrong vid(it'sthe same thing rhough). Here's the one with FGA full screen. https://youtu.be/NMkDJ5sL6rg

**Comment by HayanShiro** [comment]
Something new happened when I recorded it with same settings. https://youtu.be/j2iod6Zaasc

**Comment by HayanShiro** [comment]
Seems like that happens whenever I flip the phone in other direction so the black border is on ghe right and not left

**Comment by HayanShiro** [comment]
> Is it not the same video?
> Post a video of when you made FGA full-screen.
https://youtu.be/NMkDJ5sL6rg (when black gap is on the left side)
https://youtu.be/j2iod6Zaasc (black gap on the right side)

**Comment by HayanShiro** [comment]
I hope this issue gets solved soon so I could make the best out of this Roulette event.

**Comment by HayanShiro** [comment]
I'll post one again in more organized form.
