### ISSUE TITLE
In gift box, takes only x amount of gold exp and all silver exp?

### ISSUE THREAD

**Issue by decade5z** [MathewSachin/Fate-Grand-Automata#475]
Before opening an issue:
- [ ] No one has asked for this feature before in other issues (even the closed ones)

> If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Comment by reconman** [comment]
You can adjust the amount of Gold EXP to be collected in `More options` -> `Gift Box`-> `Max Gold ember set size`.

Is your question answered?

**Comment by decade5z** [comment]
Ah my bad didn't see that option, thanks! i'll close the issues
