### ISSUE TITLE
Join Lottery/Gift Box modes into a single mode

### ISSUE THREAD

**Issue by matthewasage** [MathewSachin/Fate-Grand-Automata#476]
In order to avoid having to constantly back and forth between FGO and FGA during long unboxing sessions, it would be best to join Lottery and Gift Box modes into a single one. Pretty sure you can figure this out better than I can, but I'd say the flow could be like this:

if (UI element check says we are in Present Box) then GiftBox()
else Lottery()

**Comment by reconman** [comment]
There's already an option of switching modes through the Script Mode button in the notification. You have to click on the `V` button on the right side of the notification if you don't see it.

But you're right, it could be a bit optimized, at least the present box detection through `No. of Presents` or one of the `Receive` buttons. For Lottery, almost everything is transparent. The only thing I can find that's not transparent and should be consistent in all lottery events is the `Roulette Details` button at the bottom of the screen.

**Comment by nevets1219** [comment]
I think another possibility is that we can have an option to auto switch from "Lottery" to "Gift Box" once we detect we are full. It doesn't solve the problem of going back from "Gift Box" to "Lottery" though -- maybe a long press to toggle between the two modes?

**Comment by mpetrovic** [comment]
Just a way to switch modes without having to open the notification pane would be helpful. Long-press or swipe on the play button to open the dialog with all the options, or something like that.
