### ISSUE TITLE
Roulette option to not press reset

### ISSUE THREAD

**Issue by HayanShiro** [MathewSachin/Fate-Grand-Automata#477]
Before opening an issue:
- [O] No one has asked for this feature before in other issues (even the closed ones)

> If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

What if you could choose not to press reset when you don't have enough tickets and you got the best item? 
That way you can get every single roulette item for every round.

**Comment by reconman** [comment]
I don't understand your request. Reset is only pressed when the box is empty.

**Comment by HayanShiro** [comment]
I thought I saw it reset when it was 200/300 because there wasn't any tickets left to spend.

**Comment by HayanShiro** [comment]
> I don't understand your request. Reset is only pressed when the box is empty.

I thought I saw it reset when it was 200/300 because there wasn't any tickets left to spend.

**Comment by FiQ1** [comment]
> > I don't understand your request. Reset is only pressed when the box is empty.
> 
> I thought I saw it reset when it was 200/300 because there wasn't any tickets left to spend.

That was for the first 10 lottery isn't it? When the grand prize is acquired the reset button will available and when the tickets is all used up but there's still prizes in there...it will thought that the box needs to reset....I recommend that you don't use the lottery function before the first 10 boxes

**Comment by HayanShiro** [comment]
> > > I don't understand your request. Reset is only pressed when the box is empty.
> > 
> > 
> > I thought I saw it reset when it was 200/300 because there wasn't any tickets left to spend.
> 
> That was for the first 10 lottery isn't it? When the grand prize is acquired the reset button will available and when the tickets is all used up but there's still prizes in there...it will thought that the box needs to reset....I recommend that you don't use the lottery function before the first 10 boxes

Yes that's what I meant. But I was wondering if it was possible to not reset for the first 10 roulette as well.

**Comment by MathewSachin** [comment]
Not really. It won't detect the box number. Testing with the first 10 boxes isn't really possible either.
The wiki warns about this too.
