### ISSUE TITLE
Support scrolling will have drags with no effect on Android 8+

### ISSUE THREAD

**Issue by reconman** [MathewSachin/Fate-Grand-Automata#48]
Right now the app misses some drags because it's too quick.

We can add a wait() at the end of the drag operation to both address this issue and avoid issues with image recognition.

**Comment by Inkaflare** [comment]
As a heads-up, this issue doesn't seem to be happening on my device despite running on Android 10 (Honor View 20). It may be possibly not be entirely related to the Android version running the app.

**Comment by consistentescape** [comment]
Does Android 8+ include Android 8 too? Because I am using an Android 8.0 Samsung Device (no notch if that matters) and there's no problem for me either.

**Comment by reconman** [comment]
Yes, it includes Android 8. Some swipes are not picked up correctly by FGO because the app doesn't wait long enough after swiping.
