### ISSUE TITLE
FGA doesn't recognize the supports screen. 

### ISSUE THREAD

**Issue by HayanShiro** [MathewSachin/Fate-Grand-Automata#481]
Before opening an issue:
[O] I tested the latest release
[O] I looked at other issues (even the closed ones)
[O] I read the Troubleshooting Guide
[O] I'll fill this template properly

Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

Describe the bug
It gets stuck on supports screen as if it doesn't recognize it (even when FGA is full screen and when ignore notch is off). Then when I manually select a support and it goes to the battle screen it keeps on being stuck. 

Screenshots

Video
https://youtu.be/NMkDJ5sL6rg 
(when black gap is on the left side)
https://youtu.be/j2iod6Zaasc 
(black gap on the right side)

Device Info (please fill at-least 'Device model'):
Device model: Samsung Galaxy S20+
Screen size: 6.7 inch
Android Version: Android 10
RAM: 12GB

**Comment by HayanShiro** [comment]
https://youtu.be/1_3xXK_Zno8
As you can see here it doesn't even scroll. 
What should I do?

**Comment by reihunter360** [comment]
The first 2 videos return a 404 error.

Does it run the battlescript in battle?

**Comment by Oduna** [comment]
I have the same problem with the same phone with the notch setting for samsung flipped on. It works fine during the battle but afterwards freezes on trying to pick a support.

**Comment by HayanShiro** [comment]
> The first 2 videos return a 404 error. (Nvm had to remove your comments)
> 
> EDIT: Looks like you've got a notch, check the troubleshooting guide to check your settings for Notch Calculation

"Your phone does have a notch. Turning ON that setting would Ignore the notch, which only helps in the case where FGO also ignores the notch and extends over it. But, right now FGO is leaving the notch area black, so no need to ignore it." - MathewSachin

Therefore ignore notch is turned off in all videos I linked.
I don't know what to do anymore.

**Comment by MathewSachin** [comment]
I don't know either.
Last 2 times I asked you to change some settings and you said that those worked.
So, I'm confused about what more can be done now.

**Comment by HayanShiro** [comment]
> I don't know either.
> Last 2 times I asked you to change some settings and you said that those worked.
> So, I'm confused about what more can be done now.

First it was solved by turning off ignore notch then second time it was solved by making FGA full screen. 
Maybe I should turn up the delay or turn down similarity?

**Comment by MathewSachin** [comment]
> First it was solved by turning off ignore notch then second time it was solved by making FGA full screen.

I'm confused that If it was solved before, what happened to make the regions wrong again.

> Maybe I should turn up the delay or turn down similarity?

Regions are wrong for you, so, changing delay or similarity isn't the right solution.

**Comment by HayanShiro** [comment]
> > First it was solved by turning off ignore notch then second time it was solved by making FGA full screen.
> 
> I'm confused that If it was solved before, what happened to make the regions wrong again.
> 
> > Maybe I should turn up the delay or turn down similarity?
> 
> Regions are wrong for you, so, changing delay or similarity isn't the right solution.

Then how do I change region from auto detect?

**Comment by reihunter360** [comment]
The region he's talking about is FGA's detection regions for what's on screen to match with images for KR.

There's not much you can do... have you changed your phone's resolution as of late?

**Comment by HayanShiro** [comment]
> The region he's talking about is FGA's detection regions for what's on screen to match with images for KR.
> 
> There's not much you can do... have you changed your phone's resolution as of late?

Not that I know of. 
Let me see if I can get it working with different resolutions(if it's possible to change it)

**Comment by HayanShiro** [comment]
I found the solution while scrumbling through settings. 
It was the "font size". 
I saw that my font size was little bit larger than default so I turned it all the way down to minimum. 
Then for some reason, region detection started working again. 
Thanks everyone and I really hope I don't come back with this issue again haha.

**Comment by MathewSachin** [comment]
I don't think font size should matter 
Post a video of it working this time.
Every time you said it worked and came again with the same issue, so I want to confirm.

**Comment by HayanShiro** [comment]
> I don't think font size should matter
> Post a video of it working this time.
> Every time you said it worked and came again with the same issue, so I want to confirm.

https://youtu.be/B0j9ja5ajfM
Here it is. I can get more video if you want to see anything else.

**Comment by MathewSachin** [comment]
That's a really weird configuration. I think now the regions are detected right but shown wrong.
Ideally, FGA's Play button shouldn't go into the notch area.
But, well, if it's working, then it's fine I guess.
