### ISSUE TITLE
Don´t Work in Huawey Y7

### ISSUE THREAD

**Issue by Bryantaker** [MathewSachin/Fate-Grand-Automata#482]
Before opening an issue:
- [Y] My question isn't answered in any other issues (even the closed ones)
- [Y] I'm not reporting a bug/error

> If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

I installed the app today and configured it but don´t make nothing, or better say, the only thing that does is used apples and restart the battle when is finished, but don´t select the support ni used carts during the battle

![image](https://user-images.githubusercontent.com/71955836/94355815-b89cec00-0044-11eb-9863-58660365d818.png)
![image](https://user-images.githubusercontent.com/71955836/94355826-cc485280-0044-11eb-923b-2aeb6dccdef3.png)
![image](https://user-images.githubusercontent.com/71955836/94355836-d702e780-0044-11eb-8959-ca6e1214ff6b.png)
![image](https://user-images.githubusercontent.com/71955836/94355842-df5b2280-0044-11eb-8a9c-2d99bef63d0e.png)
![image](https://user-images.githubusercontent.com/71955836/94355848-eb46e480-0044-11eb-8036-83512035178d.png)
![image](https://user-images.githubusercontent.com/71955836/94355852-f6017980-0044-11eb-8f5b-3a8f89b86e2b.png)
![image](https://user-images.githubusercontent.com/71955836/94355857-00237800-0045-11eb-9287-39da96534e9a.png)

Device model: Huawei Y7 (Dub-LX1)
Screen size: 6.3 inch (1520 X 720)
Android Version: Android 8.1
RAM: 3GB

**Comment by MathewSachin** [comment]
Phones having notch should be Android 9 or above, otherwise, FGA won't work

See https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Game-Area-detection#case-4-your-phone-is-android-7-or-8-and-has-a-notch
