### ISSUE TITLE
Option to use both SQ and Apples for refill

### ISSUE THREAD

**Issue by Whatwaq** [MathewSachin/Fate-Grand-Automata#484]
What the title says. Reason for this is that I have basically no apples, but a few bronze apples and some SQ left over, and I would like FGA to make full use of all of them.

A potential problem with this is that there may be too many options, as maybe someone in the future may ask to use SQ and only a specific type of apple, and the list would look like

-All Apples (NO SQ)
-Gold Apples
-Silver Apples
-Bronze Apples
-Rainbow Apples (SQ)
-All Apples + SQ
-Gold Apples +SQ
-Silver Apples +SQ
-Bronze Apples +SQ

**Comment by MathewSachin** [comment]
I think it would be better to go with checkboxes in that case instead of the dropdown we have now

- [x] Bronze apples
- [ ] Silver apples
- [ ] Gold apples
- [x] SQ

**Comment by Whatwaq** [comment]
That sounds good

**Comment by Whatwaq** [comment]
Video of apple looping problem:
https://imgur.com/a/loOkU2P
Screenshot of apple settings:
![image](https://user-images.githubusercontent.com/47783328/94708975-c2418f00-0377-11eb-9c48-1c124ca0201c.jpg)
![image](https://user-images.githubusercontent.com/47783328/94709000-ca013380-0377-11eb-97e0-6a81b2bab44a.jpg)

**Comment by MathewSachin** [comment]
So I was right, order isn't maintained.
