### ISSUE TITLE
App is stuck in a loop if the inventory is full

### ISSUE THREAD

**Issue by reconman** [MathewSachin/Fate-Grand-Automata#49]
The app will run in a loop if this screen pops up:

![](https://dl3.pushbulletusercontent.com/gwIwTSQrkSU07JR9zpP2J4Q2Ee5ii0jT/Screenshot_20200422-164910.jpg)

It should exit if this screen is detected.

**Comment by MathewSachin** [comment]
We'll have to check this where we check for apples

**Comment by reconman** [comment]
So somewhere around here: https://github.com/MathewSachin/Fate-Grand-Automata/blob/master/FateGrandAutomata.Core/AutoBattle.cs#L116

**Comment by MathewSachin** [comment]
Right before this line:

https://github.com/MathewSachin/Fate-Grand-Automata/blob/5ffea3e91bdb8533356ddf63f1319ff40a9329a0/FateGrandAutomata.Core/AutoBattle.cs#L123

**Comment by MathewSachin** [comment]
For now, should I implement this as an NA only thing?
@reconman I think it will be difficult for you to get your inventory full on a new account.

**Comment by reconman** [comment]
I have 500 inventory spaces in JP....

**Comment by reconman** [comment]
Someone was so nice to provide a screenshot:
![image](https://user-images.githubusercontent.com/12360257/80466322-b111d380-893c-11ea-99e0-6e0710cfa564.png)

https://community.gamepress.gg/t/request-screenshot-of-an-inventory-full-message/72978/3

**Comment by reconman** [comment]
Still doesn't work

**Comment by MathewSachin** [comment]
Can you check if it is a timing problem or the region is coming out wrong using Debug mode?

**Comment by reconman** [comment]
Here's a video: https://i.imgur.com/LFJNlFS.mp4

**Comment by MathewSachin** [comment]
I think making the region bigger should solve this problem.
It never missed on my phone. So, the reason should probably be it going off by a pixel when scaling.

And, we made that change to not match if the target region is smaller than what we want to match:
https://github.com/MathewSachin/Fate-Grand-Automata/blob/bac369a11316d806567d956b19a4b16466fb554b/app/src/main/java/com/mathewsachin/fategrandautomata/imaging/DroidCvPattern.kt#L65
