### ISSUE TITLE
Script unable to use servant 1 NP

### ISSUE THREAD

**Issue by mreyasluna** [MathewSachin/Fate-Grand-Automata#490]
Before opening an issue:
- [ ] I tested the latest release
Yes
- [ ] I looked at other issues (even the closed ones)
Yes
- [ ] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
Yes
- [ ] I'll fill this template properly
Yes

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
Include steps to reproduce the error if required

The title says it all. The script can't use sevant 1 np. The video shows it happening twice, once as a part of the auto skill script, while the other happened as a part of the spam NP function. It seems to be clicking to the right of the button.

**Screenshots**
It is recommended that you at-least add one screenshot of FGO running on your device.

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON
Recording functionality is available within the app in `More options`.

**Device Info (please fill at-least 'Device model'):**
 - Device model: [e.g. Xiaomi Redmi 4]
Samsung galaxy s10e
 - Screen size: [e.g. 1280x720]
 - Android Version: [e.g. Android 7.1]
10
 - RAM: [e.g. 3GB]
6GB

**Comment by reconman** [comment]
You have to replace the \[ \] parts in the template. And include a video.

**Comment by mreyasluna** [comment]
@MathewSachin 
Fixed it. Its 3am, sorry for my stupidity.
