### ISSUE TITLE
Select face cards based on targeted skill

### ISSUE THREAD

**Issue by kayanomatsuoka** [MathewSachin/Fate-Grand-Automata#492]
Can we have a feature such that if a Servant gets a buff, their face cards will be prioritized? Also, is it possible to use skills only based on the face cards that we see? For example, use NP gain skill only if that Servant's Arts/Quick card appears, then proceed to use that Arts/Quick card. Otherwise, do not use NP gain skill.

**Comment by reconman** [comment]
No sorry, that's too difficult to implement. You would have a library of buff icons to check for and also if all of your servants have buffs, it won't help you. For example, if you use Charisma or Waver's attack buff.
