### ISSUE TITLE
Doesn't detect Friend request screen on NA

### ISSUE THREAD

**Issue by Whatwaq** [MathewSachin/Fate-Grand-Automata#493]
Before opening an issue:
- [x] I tested the latest release
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I looked at other issues (even the closed ones)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
After a battle, if FGA chooses a non-friend support and the friend request screen comes up  it will go into an infinite loop of waiting for something.

**Screenshots**
![](https://cdn.discordapp.com/attachments/755763097788088330/761104366723137546/Screenshot_20201001-002136.png)

**Video**
https://cdn.discordapp.com/attachments/755763097788088330/761107089283874816/record_1.mp4

**Device Info (please fill at-least 'Device model'):**
<img src="https://cdn.discordapp.com/attachments/755763097788088330/761108603804975164/Screenshot_20201001-141333.png" width="250">

**Comment by MathewSachin** [comment]
This icon used to be present before the classes:

![friend request](https://github.com/MathewSachin/Fate-Grand-Automata/blob/master/app/src/main/assets/En/friendrequest.png?raw=true)

I think this might be a glitch in FGO in the latest update and not intended since JP still has that icon:

![Screenshot_20201001-122756](https://user-images.githubusercontent.com/10654537/94777746-9955e400-03e1-11eb-906c-0861bd204ac5.png)

**Comment by MathewSachin** [comment]
No, it's not in the same place. See from my screenshot that Follow option changes position of cancel button.
Also, if we just detect Cancel button, we might cancel something we don't want to cancel.

**Comment by randoomdude** [comment]
Is the friend request thing still broken? Every time I get to the end of a fight, it skips the friend request if it's there at the end

**Comment by reconman** [comment]
@randoomdude Friend requests are skipped by default, you can't enable it right now.

**Comment by randoomdude** [comment]
Then could you at least just have the script stop at this screen instead of right after it?
