### ISSUE TITLE
Space Ishitar 2th skill

### ISSUE THREAD

**Issue by Dwide13** [MathewSachin/Fate-Grand-Automata#495]
How i can use  SpaceI shitar 2th skill in auto?

**Comment by NovemRivers** [comment]
1. roll for space ishtar
2. level her and ascend till she gets the second skill
3. put her in your party and set up the autoskill config
4. run on a node

**Comment by reconman** [comment]
Have you tried using it as a targeted skill?

**Comment by Dwide13** [comment]
what type of target skill?

**Comment by Whatwaq** [comment]
what kind of target skills are there, Dwide13?

**Comment by Dwide13** [comment]
I have a problem when using space ishitar second skill for change her np type in auto mode

**Comment by Dwide13** [comment]
ok, i resolve by myself
