### ISSUE TITLE
CN lottery feature

### ISSUE THREAD

**Issue by kohcheeyit** [MathewSachin/Fate-Grand-Automata#497]
I need a auto open lottery box for CN server
[Screenshot.zip](https://github.com/MathewSachin/Fate-Grand-Automata/files/5321175/Screenshot.zip)

**Comment by MathewSachin** [comment]
Also need a present/gift box full image

See https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Lottery

**Comment by kohcheeyit** [comment]
> Also need a present/gift box full image
> 
> See https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Lottery

i had provided the image , in the Screenshot.zip

**Comment by MathewSachin** [comment]
No, you've not.
I'm not asking for lottery box finished image, but the screen that shows that present box is filled with embers.

**Comment by kohcheeyit** [comment]
> No, you've not.
> I'm not asking for lottery box finished image, but the screen that shows that present box is filled with embers.

ok ,later i sent because now i got exam

**Comment by kohcheeyit** [comment]
This?
![Uploading 命运-冠位指定_Screenshot_2020.10.03_17.47.54.jpg…]()

**Comment by kohcheeyit** [comment]
![StopGifts](https://user-images.githubusercontent.com/56528815/94988619-1d09ff00-05a1-11eb-8cb9-60dd91b4249e.jpg)
This?

**Comment by MathewSachin** [comment]
Try this build: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/285841675

**Comment by kohcheeyit** [comment]
> Try this build: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/285841675

Tested, no problem
