### ISSUE TITLE
App doesn't work on Galaxy Note 9

### ISSUE THREAD

**Issue by Tom3kk** [MathewSachin/Fate-Grand-Automata#503]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

**Describe the bug**
Script does nothing. 
Overlay works. I tried changing autoskill etc. Enabling refills or limiting runs makes it say "ran 0 out of X times" over and over.

**Device Info (please fill at-least 'Device model'):**
 - Device model: Galaxy Note 9 512gb

**Comment by MathewSachin** [comment]
If it doesn't work on Samsung phones even after reading the Troubleshooting Guide and looking at other issues, then you're out of luck.
The Bot closed your issue once and even then there's no Debug mode video either and you claimed to fill the template properly, so not much we can do to help you.

Add to it the way you didn't follow my instructions properly in your past issue (#289) and I don't feel like bothering now.
