### ISSUE TITLE
Giftbox script starts on any screen

### ISSUE THREAD

**Issue by FleetingComet** [MathewSachin/Fate-Grand-Automata#509]
Before opening an issue:
- [✓] I tested the latest release
- [✓] I looked at other issues (even the closed ones)
- [✓] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [✓] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
Currently the Giftbox script works even outside the giftbox screen

It will work with any screen (I accidentally clicked back and clicked a singularity and it will infinitely scroll there)

And screen with scrollbars (like the singularity list, roulette's prices)

**Screenshots**
No screenshot available 

**Video**
No video available

**Device Info (please fill at-least 'Device model'):**
 - Device model: Xiaomi Redmi Note 7
 - Screen size: 1080 x 2340
 - Android Version: Android 9
 - RAM: 3GB

**Comment by MathewSachin** [comment]
The Lottery and FP scripts also work anywhere :-P

**Comment by MathewSachin** [comment]
Should be fixed when #483 is merged

**Comment by FleetingComet** [comment]
Thanks
