### ISSUE TITLE
Area detection is suddenly broken

### ISSUE THREAD

**Issue by sleeping-player** [MathewSachin/Fate-Grand-Automata#522]
Before opening an issue:
- [x] I tested the latest release
 Actually I'm on CI build 1025.
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
Area detection is broken. The detection area is skewed to the right.
It has been working fine for several days, but one day it suddenly goes like this.
I personally used the Play Store release version, but suddenly this bug occurred and I changed it to recent CI build version.
However, even a CI build a few hours ago did this.
I know that clearing the app data will fix the bug, but once this bug occurs, it cannot be recovered again.
I think issue 481 is likely to be the closest to this, but since this bug comes up suddenly during normal operation, it actually seems to be different from that.

**Screenshots**
See video

**Video**
https://www.youtube.com/playlist?list=PLO3MfKaPeDuSZkpfODgMfB5TjFKD1wGDO
This is a link to a YouTube playlist.
Since the recording function built into FGA cannot record all actions across Android, I used the recording function of the Galaxy mobile phone. Video 1 was recorded through this.
However, as the FGA starts operating in the middle, the recording of the Galaxy is stopped because the FGA takes away the recording right.
To record the last scene, I turned on the FGA's recording function, and video 2 was recorded with it.

**Device Info (please fill at-least 'Device model'):**
 - Device model: [e.g. Galaxy S10+]
 - Screen size: [e.g. 3040x1440]
 - Android Version: [e.g. Android 10]
 - RAM: [e.g. 8GB]

**Comment by MathewSachin** [comment]
I'm pretty sure this happens because you're opening FGA as a floating/windowed app. It can't detect the notch size this way.
To my knowledge, to detect notch, the app's window should get affected by notch, i.e. opened in the normal way instead of as a window.

**Comment by sleeping-player** [comment]
I couldn't believe it, but that's right. After deleting the app data, run the app normally, set it up, and run the script, so it works.
But even so, it's amazing how it suddenly malfunctions after I've been running it this way for quite some time.

**Comment by MathewSachin** [comment]
The thing is the AccessibilityService keeps running even when the app is closed and it keeps the cutout value stored till the app is killed by Android. You opened the app normally once, that value got stored, so it kept working.
Android can kill apps when needed so you shouldn't rely on the value getting stored.

**Comment by sleeping-player** [comment]
The reason why this app hasn't entered android quick settings yet is that there seems to be some reason, so I tried another method, but this is also an inappropriate method for technical reasons, so I should find a launcher that can be executed in notification...
Interestingly, I need to know not only how to use the app, but also the structure of the app's operation, why it should be used that way.
