### ISSUE TITLE
Add Friend Screen Failure

### ISSUE THREAD

**Issue by chairmanxyz** [MathewSachin/Fate-Grand-Automata#532]
Ive been running into a new issue I haven't seen before and I can't explain why. As far as I've seen this hasn't been reported, but lately the script gets struck on the screen where you add or reject a new friend after completing the battle using a non friend support. It seems like it's not recognizing that screen at all and eventually it just exits the script saying either the user suspended or screen turned off - so it's not even throwing an error. This is on NA by the way, on the oniland raids.

**Comment by MathewSachin** [comment]
Duplicate of #493
