### ISSUE TITLE
How often do you update the play store version?

### ISSUE THREAD

**Issue by duradara** [MathewSachin/Fate-Grand-Automata#534]
Because I am having problems with the friend request window in NA and I saw that you already fixed it here #525 but this fix is not in the play store version yet.  
Sorry if my english is bad.

**Comment by minhducsun2002** [comment]
When they are confident that no bugs happen. It is always better to minimize bugs in releases.

You can always grab the latest builds from GitHub Actions.

**Comment by MathewSachin** [comment]
@minhducsun2002 said right about testing stuff before putting on PlayStore. It's not like the PlayStore version has any problems. The friend screen issue is basically DW messing up on NA. All other servers have that button which somehow got deleted on NA.

I can't put up a new release and expect people to understand how to use it.
Sorry for the bad editing, but this is how people are on the YouTube video on the current version:

![image](https://user-images.githubusercontent.com/10654537/97104847-eecd9a00-16dc-11eb-8075-5ea020b37208.png)

All the wikis and have to be updated and a new tutorial video is needed for them. I don't want to be flooded with everyone asking the same questions again and again.

**Comment by MathewSachin** [comment]
You can get the latest Canary build here: https://github.com/MathewSachin/Fate-Grand-Automata/releases/tag/canary
It has the latest features we have implemented.

Things have changed quite a lot from the PlayStore version and not everything is very well-tested.
