### ISSUE TITLE
AP ran out does not stop the script in the right order

### ISSUE THREAD

**Issue by reconman** [MathewSachin/Fate-Grand-Automata#536]
**Describe the bug**
With the new pause triggers for screen turned off, I discovered one issue with old code.

If AP runs out, the script is stopped only AFTER you click on OK. If the screen is locked while the AP message is on screen, the message about the script being paused appears on top of that.

So I think the order of the messages and the actual action (stop) need to be switched. The order for pausing seems to be correct, since there's no pause button anymore.

**Screenshots**
![](https://i.imgur.com/IFaMXl1.jpg)

**Comment by MathewSachin** [comment]
ah, I had changed the stop to actually happen only after the dialog is dismissed, so that accidentally another instance isn't started in the meanwhile.
It was a miss on my part. This should be easy to fix I think.
