### ISSUE TITLE
Skill Spam Seems to sometimes skip skills.

### ISSUE THREAD

**Issue by Rajvir8** [MathewSachin/Fate-Grand-Automata#540]
Overall Skill Spam just isn't triggering at times

![Screenshot_20201028-093612](https://user-images.githubusercontent.com/17600697/97443182-19983800-1901-11eb-9087-f3f451a38e06.png)

I was watching and paused it when it saw all my skills and skipped past using them this turn.

The auto I was using to test this out
abcdefgh1i456

Overall it does remember at times, so it's definitely useful on to add to stall team, but it's probably best to still just plan everything out manually as usual and then after it's over it might use some skills on Cooldown.

Overall this remains a great new feature that sadly cannot be relied on as a primary feature just yet.  

Works great as a add-on though.

Also just noticed this new version perfectly avoids stunning cards and I really appreciate that for the record.

**Comment by MathewSachin** [comment]
I had encountered it not using skills before but didn't pay much attention since others said it worked fine and I mostly 3T.
I adjusted the skill check regions and added delays in between in case it was checking for skills before they were visible after the animation.

Try the APK from this page: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/333852920

**Comment by MathewSachin** [comment]
Ah, there's one more case to thing to take care of. I'll post a new build after a workaround.

**Comment by MathewSachin** [comment]
New build: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/333946957

**Comment by Rajvir8** [comment]
Downloaded the new build, I'll try it out later today when I have so more AP.

**Comment by Rajvir8** [comment]
Actually you know what I'll go do one Salem run for 20AP.  Best place to do it since it's all Casters and Tamamo for my team.

**Comment by Rajvir8** [comment]
It should still be Version 1,087 right?

Nox annoyingly doesn't tell me when it updates it by dragging APK so I always have to wonder if it actually worked.

**Comment by Rajvir8** [comment]
No it did change to 1,093 after I opened it.  Just had a delay and I also manually added it through options as well as just dragging it.

**Comment by reconman** [comment]
1094 also exists, you can see the builds here https://github.com/MathewSachin/Fate-Grand-Automata/actions?query=event%3Apush

**Comment by Rajvir8** [comment]
Yea I'll add that to my notes and swap to that now so I can better test this.

**Comment by Rajvir8** [comment]
Also just noticing that it automatically notices when a skill has been used and clicks off immediately, deeply appreciate that and it will allow me to be a  lot more free with my skill uses.

That's always been the hardest plan when thinking these things through after all.

**Comment by Rajvir8** [comment]
Failed this round, but that's likely because of the fact that I started this again I had already used all my skills due to needing to swap from 1093 to 1094.

![Screenshot_20201028-145540](https://user-images.githubusercontent.com/17600697/97483337-aeb12600-192d-11eb-868d-d7f17ddfbd6c.png)

After I finish this round I'll try again and see if that fixes it.

**Comment by Rajvir8** [comment]
Starting from the beginning and I might still be able to see if it works smoothly thanks to the final round taking the longest due to taking all Casters against a Caster boss.

**Comment by Rajvir8** [comment]
Yea it seems to run a lot smoother now, still didn't do Gil and Tamamo's first skill.  But that's almost certainly because Auto didn't see those skills pulled off successfully.  Gil's was on cool-down and Tamamo killed him before the next turn where it would have come out.

Will test again with a more normal round now, but so far I'm completely satisfied.

**Comment by Rajvir8** [comment]
New one seems to work flawlessly. 

Closing this issue since it fixed the problem.
