### ISSUE TITLE
Stuck in support list on version 0.10.1

### ISSUE THREAD

**Issue by dekar63** [MathewSachin/Fate-Grand-Automata#55]
> MAKE SURE YOU TESTED THE LATEST RELEASE.

> See 'SAMSUNG.md' first, if you're a Samsung user.

**Describe the bug**
Include steps to reproduce the error if required

After updating to version 0.10.1 the app is not able to select a support servant and keeps looping through the support list until timeout

**Screenshots**
If an error occurred, you can find the message by expanding the app's notification.
It is recommended that you atleast add one screenshot of FGO running on your device.

https://imgur.com/a/C2KB1OH

**Device Info (please fill atleast 'Device model'):**
 - Device model: Xiaomi Poco phone F1
 - Screen size: 2246x1080
 - Android Version: Android 10
 - RAM: 6GB

**Comment by reconman** [comment]
@dekar63 Please provide the following things:

1. Screenshot of the Support (Manage Support Selection) screen
2. Screenshot of the Auto Skill screen
3. If an Autoskill Config is selected, please also provide a screenshot of the "Edit AutoSkill Item" screen that pops up when you click on the entry under "Manage Autoskill Configurations"

**Comment by reconman** [comment]
And More Options -> Ignore Notch Calculation is set to disabled, right?

**Comment by dekar63** [comment]
Sorry I forget to add the rest of the screenshots
![Screenshot_2020-04-23-04-09-05-578_com mathewsachin fategrandautomata](https://user-images.githubusercontent.com/64052060/80051424-6812e700-8518-11ea-9c3a-2e0cbd5d6a9c.jpg)
![Screenshot_2020-04-23-04-10-06-696_com mathewsachin fategrandautomata](https://user-images.githubusercontent.com/64052060/80051426-68ab7d80-8518-11ea-8c21-94ee769df729.jpg)
![Screenshot_2020-04-23-04-10-02-799_com mathewsachin fategrandautomata](https://user-images.githubusercontent.com/64052060/80051427-69441400-8518-11ea-95e3-93c8245bc8c5.jpg)
The ignore notch calculation option is disabled

**Comment by reconman** [comment]
And another one of the AutoSkill screen, please. (with Enable Auto Skill, Skill Confirmation, ...)

**Comment by reconman** [comment]
We were able to reduce it to an issue related to only having setting mona lisa without a servant. We're still in the middle of debugging why that happens.

**Comment by MathewSachin** [comment]
@dekar63 The Android 7 scrolling method is working fine on my phone even though it is a bit slow.
So, I've made a build that uses the same method on Android 8 and above.

Will you test: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/85513859

There would be an apk link on that link and it should download as a zipped folder.

**Comment by dekar63** [comment]
> @dekar63 The Android 7 scrolling method is working fine on my phone even though it is a bit slow.
> So, I've made a build that uses the same method on Android 8 and above.
> 
> Will you test: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/85513859
> 
> There would be an apk link on that page and it should download as a zipped folder.

Sorry for taking too long to answer. 
The fix works perfectly now it select the correct servant without being stuck on a infinite loop thought the list thanks for the help

**Comment by MathewSachin** [comment]
> Sorry for taking too long to answer.

No problem, sometimes we also are late to respond. Everyone has other things to do too.

Glad that this worked. Feel free to open another issue if you face any other problem.
