### ISSUE TITLE
Add NP card Type Selection setting for EMIYA and Space Ishtar

### ISSUE THREAD

**Issue by HellProphet0** [MathewSachin/Fate-Grand-Automata#559]
![image](https://user-images.githubusercontent.com/53113292/99084078-c263ba00-25c6-11eb-9422-61775e83718f.png)
shouldnt this be fixed? Emiya is my only current Arts Servant that can actually loop

**Comment by gesalt** [comment]
Emiya doesn't work, but space ishtar does by setting skill target the same way as targeting a servant.

**Comment by reconman** [comment]
It's fixed in the canary version: https://github.com/MathewSachin/Fate-Grand-Automata/releases/tag/canary
