### ISSUE TITLE
[LDPlayer] Start Quest button not pressable with FGA on

### ISSUE THREAD

**Issue by Sunspawn** [MathewSachin/Fate-Grand-Automata#561]
**Describe the bug**
Can't press the Start Quest button when turning FGA overlay on from outside the node. 

Turning FGA off does not enable the button by itself. Entering a servant/CE select screen or going back to reselect a support with FGA off enables the button.

Starting from within the button works perfectly fine, it's just the button not working.

**Video**
[debug mode recording from within the app](https://streamable.com/shnfkh)

[video from the emulator recording, with the workaround](https://streamable.com/k1vw5q)

**Device Info (please fill at-least 'Device model'):**
 - Device model: LDPlayer emulator

**Comment by reconman** [comment]
This was a bug from a few months ago: When you click on the dots at the top to change the party (for example 1st dot to change to the 1st party), and you're already on that party, the Start Quest button doesn't do anything anymore.

The workaround introduced back then was to not click on the dot if it's already yellow.

Ths works on 99 % of all devices, but on your emulator it seems to fail. I can't tell you why, though.

**Comment by Sunspawn** [comment]
Well, I guess nothing to do about it then.
