### ISSUE TITLE
Doesn't always use 3 cards and finish the Battle Phase

### ISSUE THREAD

**Issue by Rajvir8** [MathewSachin/Fate-Grand-Automata#565]
Before opening an issue:
    [ O ] I tested the latest release
    [ O ] I looked at other issues (even the closed ones)
    [ O ] I read the Troubleshooting Guide
    [ O ] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
For some reason for the past several updates the script sometimes pauses after only doing two cards and will stay like that until I complete the chain.  In the Screenshot I grabbed it skipped an NP to do so weirdly enough as it was on NP Spam and Skill spam with no more commands at the time.

That said generally there is only one NP when this bug happens and at it then proceeds to hit one card and then stop.  My best guess on why this bug has persisted through a couple of updates may be a buffer in my internet or Nox which causes it to slow down and miss the click possibly?  I am unsure of what is causing it to be honest.

It is very inconsistent on when it happens.  Sometimes it runs several runs without running into the issue, other times I have to click it once a round to complete a chain.

At the moment I am running version 1132 but like I said before it's happened for awhile now.

**Screenshots**
![Screenshot_20201122-101405](https://user-images.githubusercontent.com/17600697/99907726-6840b400-2cac-11eb-88ca-1c6ffd27afd2.png)

**Device Info (please fill at-least 'Device model'):**
 - Device model: Nox - 6.6.1.2 - Samsung Galaxy S9+
 - Screen size: [1280x720]
 - Android Version: [Android 7]

**Comment by Rajvir8** [comment]
Happened again this time when I left it overnight sadly it only did 2 rounds so it spent 60AP only which left it overfilled.

![Screenshot_20201123-095837](https://user-images.githubusercontent.com/17600697/99977658-ef585f80-2d72-11eb-9a30-e96ddbaea3f5.png)

**Comment by Rajvir8** [comment]
Happening more frequently I've noticed.  Maybe me turning my computer on and off for a bit might help a bit if it is indeed happening due to buffering issues.

**Comment by Rajvir8** [comment]
Been awhile since this issue got posted, it hasn't fully gone away as it happened again today but it's a fairly rare occasion on my faster rounds so I'll close it and might make a new issue if it becomes more prominent in future versions.

**Comment by MathewSachin** [comment]
Wait, does your screen turn OFF or your system gets locked or goes into sleeping/hibernation?
In such cases, it would obviously halt.

**Comment by Rajvir8** [comment]
No I'm on a Computer running Nox and the system never goes to sleep when Nox is running, closes that happens is my monitor turns off but the game keeps running Nox and FGA, but I was also running version 1146 still.  I just updated to the most current build in 1178.

So I guess I'll see if the issue pops up again, it was never something that popped up every run regardless so I'd have to wait to see if the issue still occurs.

My best previous guess is it might be due to lag at some points, or something similar.
