### ISSUE TITLE
JP: Script inconsistent NP usage

### ISSUE THREAD

**Issue by zyleet** [MathewSachin/Fate-Grand-Automata#579]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**  
On JP, using a double castoria + summer musashi + para setup for 3t looping various free nodes.

On Fuyuki X-E, it nps all 3 waves smoothly  
On Babylonia Observatory, it nps the first 2 waves, but does not pick the np card on wave 3  
On Olympus Machine God Cloister, it nps the first turn, but does not pick the np card from wave 2 onwards. Space ishtar also yields the same issue.

**Screenshots**  
![com aniplex fategrandorder_Screenshot_2020 12 01_01 16 18](https://user-images.githubusercontent.com/12456310/100642857-4b734300-3374-11eb-97f6-d1707b56d0f9.jpeg)

**Video**  
https://streamable.com/042912

**Device Info (please fill at-least 'Device model'):**
 - Device model: [BlueStacks 4.240.30.1002]
 - Screen size: [1920 x 1080]
 - Android Version: [Android 7.1.2]
 - RAM: [4 GB]

**Comment by MathewSachin** [comment]
Stage counter region has shifted even for 16:9 devices after the update and that causes it to not recognize different waves.

See [GP#2058](https://community.gamepress.gg/t/automatic-farming-app-fate-grand-automata/72155/2058?u=mathewsachin) for a temporary workaround.

**Comment by zyleet** [comment]
Yep, that seems to have done the trick. Thanks!

**Comment by MathewSachin** [comment]
I'll keep this open since this would be faced by more people.
