### ISSUE TITLE
FGA Battle Mode unable to loop with Nox 6.6.1.5

### ISSUE THREAD

**Issue by Azure0219** [MathewSachin/Fate-Grand-Automata#582]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
Include steps to reproduce the error if required

While using Nox 6.6.1.5, Android 7, FGA works well until the Results screen appears. When the results screen appears, as well as when the option to repeat the quest appears, the macro begins zooming in on the bottom right corner 3-4 times and it is unable to repeat the quest. 

Troubleshooting done:

- Moving the FGA Play button to bottom left corner, bottom right, top right, and top left has no effect. 
- Switching the Mobile Phone model has no effect. Switched from Samsung Note 10+ to Samsung Galaxy S9+.
- Disabled al Keymapping that may be triggering the pinch zoom, no effect. 

**Screenshots**
It is recommended that you at-least add one screenshot of FGO running on your device.

Attached.
![Screenshot_20201204-031649](https://user-images.githubusercontent.com/75475485/101271274-09b51480-3747-11eb-9578-9e0ebf014bcb.png)
![Screenshot_20201205-222008](https://user-images.githubusercontent.com/75475485/101271421-243bbd80-3748-11eb-9714-a190207e3797.png)
![Screenshot_20201205-222310](https://user-images.githubusercontent.com/75475485/101271472-9f04d880-3748-11eb-92b4-c76f26d7eccb.png)

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON
Recording functionality is available within the app in `More options`.

I tried using Nox's built-in video recorder and a third party app as a workaround for Nox using root for screenshots in the FGA app but they didn't couldn't capture any video, just sound. Thankfully, I believe this to be easily reproducible within the latest release of Nox. 

**Device Info (please fill at-least 'Device model'):**
 - Device model: [Samsung S9+, Samsung Note 10+]
 - Screen size: [e.g. 1280x720]
 - Android Version: [Android 7]
 - RAM: [4 Core CPU, 3072 MB Memory]

**Comment by MathewSachin** [comment]
Nope, this issue is not reproducible on my Nox.

But, I'm pretty sure you have Magnification turned ON. See [GP#1364](https://community.gamepress.gg/t/automatic-farming-app-fate-grand-automata/72155/1364).
