### ISSUE TITLE
JP Script Keep Refreshing on Support Selection

### ISSUE THREAD

**Issue by Regulusttt** [MathewSachin/Fate-Grand-Automata#583]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
It keep refreshing support selection even though the perferred CE and Servant is there 
Already tested other setting (creating new Auto skill,Change the preferred Class,Servant,CE to Any) but it still refreshing on support select

**Screenshots**
![Screenshot_20201206-231150](https://user-images.githubusercontent.com/68319933/101284130-6da80d80-3819-11eb-8510-98d7cd10b5e7.png)

**Video**
https://streamable.com/avrs3b

**Device Info (please fill at-least 'Device model'):**
 - Device model: [LG V35]
 - Screen size: [1440x2880]
 - Android Version: [Android 9]
 - RAM: [6GB]

**Comment by MathewSachin** [comment]
Troubleshooting Guide already mentions that it isn't working properly on JP.
Also, there a JP problems issue pinned on top: #571.
