### ISSUE TITLE
Suppport servant maker is not working 

### ISSUE THREAD

**Issue by Radix12222333444** [MathewSachin/Fate-Grand-Automata#591]
Hi there,i am new to Fate grand automata app and there is a problem with support servant maker.
What happens is hard to explain for me so please see the photos and help me to solve the problem
And please tell me how to add video in an issue it can help ypu to understand my problem

Samsung A70s
1080×2400
Android 10
Ram 8GB

![Screenshot_20201207-070529_FGA](https://user-images.githubusercontent.com/68287816/101322488-2491a100-388d-11eb-81ea-509b0ddb09ae.jpg)

![Screenshot_20201207-082411_FateGO](https://user-images.githubusercontent.com/68287816/101322730-85b97480-388d-11eb-9b6e-0e3c626e68a3.jpg)

@MathewSachin

**Comment by reconman** [comment]
Your issues will keep getting closed as long as you don't use the template. Look at the other bug reports, people fill out the template correctly over there. Also for videos you can use streamable.com.
