### ISSUE TITLE
Make the play/stop button a bit bigger 

### ISSUE THREAD

**Issue by Mysty-chan** [MathewSachin/Fate-Grand-Automata#61]
I have trouble getting the button to activate sometimes. A little bigger, or option to adjust the size per user's preference, would be nice. No rush though, it's a little thing.

**Comment by MathewSachin** [comment]
Actually, it might not be the size that's the problem, but the dragging sensitivity. It'll treat clicks sometimes as drag, since the finger moves a bit while clicking too. I'll reduce the sensitivity.

Have to get this up before the raids begin.

**Comment by Mysty-chan** [comment]
Could be right about that. The button does often wiggle when it doesn't start playing.

**Comment by MathewSachin** [comment]
I've already tweaked the button. It should be much easier to use now.
That change will be available in the release we do before the raids.
We also took care of the Melt-Olga issue and almost fixed servants being clicked accidently while scrolling.

**Comment by MathewSachin** [comment]
@Mysty-chan Does the play button work fine now?
Can I close this issue?

**Comment by MathewSachin** [comment]
@Mysty-chan Can you test this build: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/89336305

I made it so that the play button becomes a bit bigger on bigger screens. It's not manually tweakable though. Let me know if you want the size to be further adjusted.

**Comment by Mysty-chan** [comment]
Only just saw this, apparently github emails are going to a surpressed folder in my email and didn't see it.

Button must easier to hit at this size. And at my table's screen size it doesn't block anything important. 
![Screenshot_20200430-164009_Fate_GO](https://user-images.githubusercontent.com/64169016/80766188-106d1080-8b02-11ea-91cd-c98b28ca7a22.jpg)

**Comment by reconman** [comment]
@Mysty-chan We actually made the button a bit smaller again. It will be part of the next release.

**Comment by Mysty-chan** [comment]
A bit smaller is fine. Actually if you leave FGA toggled on during a cutscene it obscures a bit of the text.
