### ISSUE TITLE
Error during EXP mission.

### ISSUE THREAD

**Issue by Limpe-e** [MathewSachin/Fate-Grand-Automata#613]
During missions that drop EPX - and only during it - the application does not. He clicks the "attack" button and does nothing for minutes, only after a varied interval of time that he will select the cards. And the other screens that come after the battle is over also have this problem.
However, the app works correctly on all other missions!
Device: Motorola Moto G (5).
Screen: 1080 x 1920 pixels.
Android: 8.1.0.
Ram: 1867 MB. 
Thank you very much in advance!

**Comment by MathewSachin** [comment]
This is a weak phone problem. FGO requires 2GB RAM. There's no way FGO and FGA can work with that much RAM.
