### ISSUE TITLE
A random click closes the skill confirmation

### ISSUE THREAD

**Issue by shiosakun** [MathewSachin/Fate-Grand-Automata#614]
Before opening an issue:
- [x ] I tested the latest release
- [x ] I looked at other issues (even the closed ones)
- [ x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [ x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
The script path goes well until the first turn. The script selects correctly Arash 3rd skill, but before to confirm the skill, it does a random click outside the confirmation box, an then it closes (this is a non-target skill, I selected it that way in the auto-skill configuration). After that, the scripts stop by 2 seconds, then procced to attack using random cards (that I didin't programmed).

**Screenshots**
This is a random click so I can't take any, and my cellphone doesn't support screen records.

**Video**
https://youtu.be/TyPiQp_5nfQ

**Device Info (please fill at-least 'Device model'):**
 - LG K40
 - Screen size:  720 x 1440
 - Android Version: 9
 - RAM: 2Gb

**Comment by reconman** [comment]
Enable Skill Confirmation in FGA or turn it off in FGO.
