### ISSUE TITLE
Error during EXP missions

### ISSUE THREAD

**Issue by Limpe-e** [MathewSachin/Fate-Grand-Automata#615]
Before opening an issue:
- [X] I tested the latest release
- [X] I looked at other issues (even the closed ones)
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
During missions that drop EPX - and only during them - the application does not work. He clicks the "attack" button and does nothing for minutes, only after a varied interval of time that he will select the cards. screens that come after the battle is over also present this problem of slowness.
However, the application works correctly in all other missions, even using the same script that I use in EXP missions.
Note: If I pull the bar of the phone with the buttons "back", "home" and "tabs open", the application performs the actions, but stops immediately afterwards.

**Screenshots**
It is recommended that you at-least add one screenshot of FGO running on your device.

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON
Recording functionality is available within the app in `More options`.

**Device Info (please fill at-least 'Device model'):**
 - Device model: [Moto G 5]
 - Screen size: [1080 x 1920 pixela]
 - Android Version: [Android 8.1.0]
 - RAM: [1867 MB]

**Comment by MathewSachin** [comment]
Already told in https://github.com/MathewSachin/Fate-Grand-Automata/issues/613#issuecomment-747576711.

Please don't spam.
