### ISSUE TITLE
[JP] Lottery not resetting on emulator

### ISSUE THREAD

**Issue by bobhale1** [MathewSachin/Fate-Grand-Automata#617]
Before opening an issue:
- [x ] I tested the latest release
- [x ] I looked at other issues (even the closed ones)
- [x ] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x ] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
When I run the Lottery script on the recent JP Christmas Event lottery on Bluestacks, the script can't reset the lottery box. I am using the most recent CI build.

**Screenshots**
See Video

**Video**
https://youtu.be/Zg-pdZle8qI
This is a Youtube video of the recording. 

**Device Info (please fill at-least 'Device model'):**
 - Device model: Bluestacks
 - Screen size: 1600 x 900
 - Android Version: Unknown
 - RAM: 4GB

**Comment by reconman** [comment]
Seems like they changed the label on the button. Can you please take a screenshot of the screen before you reset?

**Comment by reconman** [comment]
I made the area a bit wider to the left so the new `1` position is included. Can you try the newest Canary build?

**Comment by bobhale1** [comment]
It's working now. Thank you so much.
