### ISSUE TITLE
Doesn't always use 3 cards and finish the Battle Phase

### ISSUE THREAD

**Issue by Rajvir8** [MathewSachin/Fate-Grand-Automata#619]
Before opening an issue:
[ O ] I tested the latest release
[ O ] I looked at other issues (even the closed ones)
[ O ] I read the Troubleshooting Guide
[ O ] I'll fill this template properly

    Your issue will get closed/locked by the bot in case proper info isn't provided
    If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

Describe the bug
I'm afraid the bug happened again where the script seemed to pause after only doing two cards and stay that way until I completed the chain.

I was coming and checking every few hours and stopping and restarting to check if I had gotten enough CE's.  

After around 6 hours of running perfectly.  I left it for another 2 and a half hours.  But when I came back it had broken as the screenshot shows.  I completed the chain and started it up again afterwards.

Surprisingly only a few minutes later it broke again.

I am currently using FGA version 1178 and will update it to the newest one and restart my computer just to be safe.

My auto is also currently running NP Spam and Skill Spam for when my directions run out just to be safe although most of the time it finishes without needing it on 4 minutes on average.

Due to the break the last one was closer to 7 minutes as half of the time was spend dead.

![Screenshot_20201220-102854](https://user-images.githubusercontent.com/17600697/102717207-d0d08000-42ae-11eb-9d5f-92a8433f5775.png)

Device Info (please fill at-least 'Device model'):

    Device model: Nox - 6.6.1.5 - Samsung Galaxy S9+
    Screen size: [1280x720]
    Android Version: [Android 7]

**Comment by Rajvir8** [comment]
Just to be safe and since I don't need it and am just using it out of habit, I've now shut down both NP Spam and Skill Spam, as it only really plays in at the end for the final bit and is slowing it down a little.

I can also see if this glitch ever pops up again and if it does I know it's not related to either of those two things.

I have also restarted my computer and updated to 1183

**Comment by Rajvir8** [comment]
Happened again, which at least confirms it's not either the NP Spam or the Skill spam that causes it.

Also shows that updating to 1183 sadly didn't fix the issue.

I'll watch closely to see if the issue repeats itself in the next hour or so, if it does I'll reset the computer again as that at least seems to keep the problem from happening as repeatedly if last time is any indication. 

![Screenshot_20201220-192138](https://user-images.githubusercontent.com/17600697/102728242-aefbeb00-42f8-11eb-9602-62ff8043f654.png)

**Comment by Rajvir8** [comment]
Just continuing the update by saying it did not run into the issue again and is still running smoothly, going to to sleep now so I'll report if it stopped during the 8 hours of sleep I get.  Hopefully it'll run perfectly the entire time.

**Comment by Rajvir8** [comment]
Happened again when I checked up on it after 4 hours of sleep

![Screenshot_20201221-045230](https://user-images.githubusercontent.com/17600697/102764009-7e43a200-4348-11eb-9404-6a5c31346791.png)

**Comment by reconman** [comment]
We would need a recording of when it happens, but most likely it's lag.

**Comment by Rajvir8** [comment]
Certainly possible that it's lag yea, just not sure how to combat it if it is, as when I leave my computer alone for long periods of time I'm closing all other files.  Where as in comparison when I'm checking every 30ish minutes I'm actively using Firefox, YouTube, Discord App, Microsoft Teams etc, and it's running completely fine.

Updating to 1189 now as well.

I could try figuring out how to make a recording of the aftermath which is when I notice it, but if I wanted it to notice WHEN it happened I'd have to be running recordings that last for hours at a time.

And doing so is more likely to induce lag so it very much feels like a catch 22.

**Comment by Rajvir8** [comment]
Closest I can think of a fix is some sort of timer that checks to see if your still in the card menu after 2 minutes at which point it just clicks any cards to finish it.

**Comment by reconman** [comment]
Can you tell me what your card priority is? The default WB WA WQ but with `Rearrange Cards` activated?

**Comment by Rajvir8** [comment]
Of course my Battle Command
a2bce2i,#,h6,6,6,6,#,fk25,5,5,56

I use WA,WB,WQ,A,B,Q,RB,RA,RQ for wave 1 and 2

For wave 3 I swap Weak Buster first so it's
WB,WA,WQ,A,B,Q,RB,RA,RQ

I'm assuming Rearrange cards is Shuffle Cards?

In which case I don't have that active at all, or maybe your just asking if I have reshuffled in which case the answer is yes I have.

![Screenshot_20201221-124948](https://user-images.githubusercontent.com/17600697/102806519-0a76b900-438b-11eb-8c6c-b1e94dcd9350.png)

**Comment by Rajvir8** [comment]
Almost have Jailter at Bond 10 though so I'll be changing it soon, but that's my current set up

**Comment by reconman** [comment]
`Rearrange Cards` is the new name of `Shuffle Cards`, I think, since the old name didn't indicate what it does.

I see that it doesn't press the 3rd card.

Can you try increasing the `Wait after clicking` interval in the `Fine-tune` settings? Maybe that will help with the missed clicks.

**Comment by Rajvir8** [comment]
Will do, I increased wait from 300 to 450, and length from 50 to 60.

Hopefully that fixes it.

Thanks for the advice

**Comment by Rajvir8** [comment]
Also I'm using the most of to date version in 1189, why is it still called Shuffle cards?

![Screenshot_20201221-131439](https://user-images.githubusercontent.com/17600697/102808599-88888f00-438e-11eb-936c-db6bed26136a.png)

**Comment by Rajvir8** [comment]
Did my standard check every few hours and it never broke after being adjusted and went the entire 8 hours of sleep with it being fine.  For now I'm considering this issue fixed, and if it pops again I might ask but I might also just adjust it to be higher than 450 & 60 since that seemed to have helped.
