### ISSUE TITLE
Using a Face Card before NP - Command Line

### ISSUE THREAD

**Issue by Rajvir8** [MathewSachin/Fate-Grand-Automata#621]
Before opening an issue:
- [X] My question isn't answered in any other issues (even the closed ones)
- [X] I'm not reporting a bug/error

I know that if you use the Command Maker that you can add in to use Face cards before NP, is there a way to access that purely through typing something into the command window?  Or is it purely for the Maker?

If it is Purely for the maker after selecting it once does it effect all NP's or just that specific one?

**Comment by Cascadess** [comment]
Type n1/n2 followed by "np"

**Comment by reconman** [comment]
1. Why would you want to type in commands if you're not fully familiar with the syntax and implications?
2. If you add it via the command maker, you can see what you would need to type to reach the same result.
3. It will only have an effect for that 1 turn

**Comment by Rajvir8** [comment]
I was trying to add it in Command Maker in my brother's earlier version since my one was still running.  But it didn't seem to have any difference in text for some reason.

But I'll experiment with it more after the lottery.

Still thank you for your answers, I appreciate it.

**Comment by reconman** [comment]
He must have a really ancient version from June then.

**Comment by Rajvir8** [comment]
He might, his one came from the Google Play Store I think.

Not entirely sure as I installed it for him awhile ago.  Might have just given him an APK of it honestly.
