### ISSUE TITLE
App not selecting apples when repeating

### ISSUE THREAD

**Issue by DemosMirak** [MathewSachin/Fate-Grand-Automata#628]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
When at the apple selection screen after repeating a quest, nothing happens. Debug shows red squares all over the screen. Apples must be manually selected to proceed. When an apple is selected, a green square briefly appears over the SQ image, after which the app tries to select the apple(s) it is meant to select, after which it proceeds as normal. Oddly enough, swiping down anywhere on the screen, which triggers the normal Android UI bars to pop in to view (i.e. the back and menu buttons and the battery status bar) also triggers apple selection. 

This bug shows up in the most recent app store versions as well as the canary version (most recent release at time of writing).

**Device Info (please fill at-least 'Device model'):**
 - Device model: Moto G5S(XT1794)
 - Screen size: 1920x1080
 - Android Version: Android 8.1
 - RAM: 3GB

**Comment by reconman** [comment]
Please provide a video with debug mode, otherwise we can't diagnose the source of the problem.

**Comment by DemosMirak** [comment]
Well, this is going to sound weird, but when I use the recording functionality, it fixes the problem. While this is a work-around, I'm not so sure my storage space is going to like it.

**Comment by reconman** [comment]
The old [Heisenbugs](https://en.wikipedia.org/wiki/Heisenbug)

**Comment by MathewSachin** [comment]
Works when recording is usually a case a phone not able to handle running both FGO and FGA, but recording giving the process priority.
