### ISSUE TITLE
"Script Mode" missing in latest canary build

### ISSUE THREAD

**Issue by metapone** [MathewSachin/Fate-Grand-Automata#630]
Before opening an issue:
- [X] I tested the latest release
- [X] I looked at other issues (even the closed ones)
- [X] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [X] I'll fill this template properly

**Describe the bug**
"Script Mode" option is missing from the latest canary build "FGA canary-1190".

**Screenshots**
<img src="https://user-images.githubusercontent.com/52821877/102906119-c37de600-44a6-11eb-8a01-00f6443b5f29.jpg" height="500px" />

**Device Info:**
 - Device model: Xiaomi Redmi 5 Plus
 - Screen size: 1080x2160
 - Android Version: Android 8.1.0
 - RAM: 4GB

**Comment by Whatwaq** [comment]
When you press the play button in fgo it will show the option of Lottery/Giftbox/Support maker so this button is no longer needed.

**Comment by reconman** [comment]
Thanks for the explanation, @Whatwaq
