### ISSUE TITLE
Script Error Popup

### ISSUE THREAD

**Issue by achavezz** [MathewSachin/Fate-Grand-Automata#631]
Before opening an issue:
- [x] I tested the latest release
- [x] I looked at other issues (even the closed ones)
- [x] I read the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)
- [x] I'll fill this template properly

> Your issue will get closed/locked by the bot in case proper info isn't provided
If you open unnecessary/dumb issues, you'll be rewarded with appropriate tags.

**Describe the bug**
Include steps to reproduce the error if required

After I run the app and open FGO, I click the play button to open my lotto boxes, I get a pop-up error saying that it couldn't detect the script. I downloaded the apk off the website like normal and my phone screen is compatible.

**Screenshots**
It is recommended that you at-least add one screenshot of FGO running on your device.

![Screenshot_20201222-122242_FateGO](https://user-images.githubusercontent.com/45801952/102920768-ebdaf580-4450-11eb-90d5-b73a2afba0f6.jpg)
![Screenshot_20201222-121207_FateGO](https://user-images.githubusercontent.com/45801952/102920776-ee3d4f80-4450-11eb-819c-2228c39ba9f1.jpg)

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON
Recording functionality is available within the app in `More options`.

**Device Info (please fill at-least 'Device model'):**
 - Device model: Samsung Galaxy S8

**Comment by reconman** [comment]
You didn't replace the `[]` values at the bottom, that's why the bot closed your issue.

**Comment by achavezz** [comment]
Did I fix it now?

**Comment by MathewSachin** [comment]
@reconman JP and not 16:9

**Comment by reconman** [comment]
Yup, I just saw it when I copied the screenshot to Photoshop.

This is a duplicate of #571.
