### ISSUE TITLE
Allow different card priorities on different waves.

### ISSUE THREAD

**Issue by thetwig131** [MathewSachin/Fate-Grand-Automata#64]
On the node that I am currently farming, I want to blitz through wave 1, so I have the card priority set to the default BAQ. On wave 2 however I want to prioritise quick cards (even resisted quick cards) because I know that I can kill the wave with an NP and I want extra stars for wave 3.

**Comment by MathewSachin** [comment]
In the version released right now, Card priority looks like this:

<kbd><img src="https://user-images.githubusercontent.com/10654537/82420602-921ae300-9a9d-11ea-867e-c5abd25debc3.jpg" width="200px" border="20"></kbd>

I'm not really a fan of that design, so I've already change it to be as in the image below. This should be available in the next release we do.

<kbd><img src="https://user-images.githubusercontent.com/10654537/82420626-9cd57800-9a9d-11ea-888c-7b5aa290722f.jpg" width="200px"></kbd>

And, this view can be extended as follows, in the future, to support different card priorities on different waves.
Don't mind the bad editing, I've made it as a prototype.

<kbd><img src="https://user-images.githubusercontent.com/10654537/82420696-b4acfc00-9a9d-11ea-8458-b7f287f4c865.jpg" width="200px"></kbd>

Don't expect it soon though, I'm a bit busy and all right now. Just wanted to make it clear that it is something I really want to do.
