### ISSUE TITLE
Script clicking too fast after order change

### ISSUE THREAD

**Issue by saberkevin** [MathewSachin/Fate-Grand-Automata#67]
> MAKE SURE YOU TESTED THE LATEST RELEASE.

> See 'SAMSUNG.md' first, if you're a Samsung user.
Ignore notch is already activated

**Describe the bug**
So im grinding apocrypha raid, after order change the script is programmed to use second waver first skill, but because the order change is not finished yet , it click the first skill too soon and open the second servant info.

**Screenshots**
If an error occurred, you can find the message by expanding the app's notification.
It is recommended that you atleast add one screenshot of FGO running on your device.

i think the description is enough. if need something for ss tell me.

**Device Info (please fill atleast 'Device model'):**
 - Device model: [Samsung s9+]
 - Screen size: [2220*1080]
 - Android Version: [Android 10]
 - RAM: [6 GB]

**Comment by saberkevin** [comment]
now im using the workaround by using other fake skill first like a2bcx11**b**a2bc, b in there is the fake skill to give time.

**Comment by consistentescape** [comment]
Yeah I have the same problem but with the True Ether MC. Any skill of MC causes a delay big enough that the next skill gets clicked before it's even there. Adding some fodder skills serves as a fix for now. An optional increase in the wait times would help.

**Comment by reconman** [comment]
You can also add a `t2` to target an enemy instead of using a skill. One thing that was already changed in an unreleased version is that the delay between showing the master skills and clicking on them was increases, because it was regularly missing the NP charge skill.

**Comment by consistentescape** [comment]
That sounds like a better solution for now, I'll try that. Thanks.

**Comment by MathewSachin** [comment]
Hmm, the `SelectSubMember` function calls `WaitForAnimationsToFinish`

https://github.com/MathewSachin/Fate-Grand-Automata/blob/d1748279a6f2a112ae04d72b39b4312d45de04b8/FateGrandAutomata.Core/Modules/AutoSkill.cs#L122-L133

So, an additional wait of around 1s after detecting the `Attack` button should solve most problems with script clicking too soon after Order change or even skills.

https://github.com/MathewSachin/Fate-Grand-Automata/blob/d1748279a6f2a112ae04d72b39b4312d45de04b8/FateGrandAutomata.Core/Modules/AutoSkill.cs#L27-L35

I'll give this a try

**Comment by MathewSachin** [comment]
@saberkevin @consistentescape Does it take more than 15s for order change on your device. The script keep checking if order change has completed around 3 times per second. After 15s it assumes that order change must have completed. 
I'll increase the 15s timeout if that's the case. And, this wouldn't cause problems for faster devices.
Otherwise, I'll add an extra wait of half a second after detecting the `Attack` button which should allow for animations to any remaining animations to finish.

**Comment by saberkevin** [comment]
no, i think it is under 10 second, because my device samsung s9+ is pretty fast

**Comment by MathewSachin** [comment]
Fine. I'll increase the other waiting time then and give you a build ASAP.

**Comment by MathewSachin** [comment]
@saberkevin Can you download the APK from this link: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/88043362

It should be in a zipped folder. I've added an extra wait time of 1s after order change

**Comment by saberkevin** [comment]
alrite i will test it right now

**Comment by saberkevin** [comment]
i can confirm it is already working, my fake skill is clicked, thank you so much matthew :D

**Comment by MathewSachin** [comment]
Keep testing it a bit more and let me know later. I'll keep this issue open for a while.

**Comment by saberkevin** [comment]
okay so i already done 3 run (used SQ) , and all of it is working as expected 👌, i can't test more right now because my apple is all gone so i need to wait for my AP to refill.

**Comment by MathewSachin** [comment]
Thank you for testing!
I think it should work fine for others too since I didn't change much.
I'll close this issue and release v0.11.4 right away with the fix.
