### ISSUE TITLE
Lessen time between skill selection and target selection

### ISSUE THREAD

**Issue by arkteck** [MathewSachin/Fate-Grand-Automata#69]
Phone: Samsung Galaxy S9, no notch

Is there a reason for the lag between selecting a skill and then the target for the skill? It seems to sit on the "Select Target" window for about two seconds even though the script tells it exactly what to do. Or is it because it doesn't know it's a targetable skill so it's the usual lag between button presses? In that case, it seems like you could parse it so if there's a target after a skill to do the target immediately?

Sorry if this is a known issue or I'm completely off base.

**Comment by reconman** [comment]
There are lots of static wait times so we don't have to check the current screen in every step.

If you use a syntax for a skill that will target, but the skill doesn't target, the app will click where it would expect the target click location to be.

**Comment by arkteck** [comment]
Well then that click will be useless anyway because the skill will be animating (assuming the click is immediate).

**Comment by MathewSachin** [comment]
That delay is to give time to FGO for opening the target selection dailog on slow devices. Your's should be a high-performance device, but, there are many users, including me, who're using low-performance devices. If the delay isn't there, the clicks would miss on these devices.

In future, we'll add a wait multiplier (#27) which could be configured according to your device's performance.

**Comment by arkteck** [comment]
True, you do have to account for all sorts of devices. I did see the wait multiplier option, so yeah, I think that could work.

Thank you for everything! I discovered this just in time for these raids and it's been a big help, this was just something I wondered about.
