### ISSUE TITLE
Option to use daemon 

### ISSUE THREAD

**Issue by metapea** [MathewSachin/Fate-Grand-Automata#71]
With the other fgo script, Media Projection does not work at all and same thing is happening with this one, i need daemon to even used the scripts in the first place with my nox setup. Pleases give us an option to just enable/auto enable, so the script can run instead of it doing nothing at all and making others confused on what's wrong with the app.

**Comment by reconman** [comment]
daemon is an Ankulua specific thing, we won't be able to implement or use anything like that.

Right now, Nox only returns black screenshots for an unknown reason.

But we have #47 as a potential future solution.
