### ISSUE TITLE
The app won't do anything if it's stuck in the Master EXP or Material Drop windows

### ISSUE THREAD

**Issue by reconman** [MathewSachin/Fate-Grand-Automata#77]
If the app gets through the bond point screen, but doesn't click enough to go through all the following windows, it gets stuck.

Here are JP screenshots of those screens:
![image](https://user-images.githubusercontent.com/12360257/80284329-281d5100-871e-11ea-8fe6-17ae7bec6cd1.png)
![image](https://user-images.githubusercontent.com/12360257/80284295-f73d1c00-871d-11ea-8663-864b6af4e436.png)

**Comment by MathewSachin** [comment]
I've got the NA images.

These are the parts I'm going to use:
<img width="49" alt="master_exp" src="https://user-images.githubusercontent.com/10654537/80352860-21174f80-8892-11ea-9c18-780f03d34c77.png">
<img width="58" alt="mat_rewards" src="https://user-images.githubusercontent.com/10654537/80352864-22487c80-8892-11ea-97fd-10778d5c9329.png">
<img width="53" alt="master_exp" src="https://user-images.githubusercontent.com/10654537/80352886-2b394e00-8892-11ea-9969-cc8af4d2122e.png">
<img width="60" alt="mat_rewards" src="https://user-images.githubusercontent.com/10654537/80352890-2d031180-8892-11ea-88c1-0bfbb7105f44.png">

**Comment by reconman** [comment]
Sadly there are 2 more screens, master level up and command code level up:
![image](https://user-images.githubusercontent.com/12360257/80411308-4a54d180-88cc-11ea-80a3-4a3fae04961b.png)
![image](https://user-images.githubusercontent.com/12360257/80412330-0236ae80-88ce-11ea-95ab-6e3ecd48c9be.png)

On NA I'm already max level.

**Comment by reconman** [comment]
I think we can use the big UP, it's the same in NA.

**Comment by MathewSachin** [comment]
Or we can use the same icon used for bond up

**Comment by reconman** [comment]
Yes, but make the region bigger.

**Comment by reconman** [comment]
Your code change definitely works in JP for the 2 new handled windows.
