### ISSUE TITLE
Changing the click for targetables skills

### ISSUE THREAD

**Issue by Yandirin** [MathewSachin/Fate-Grand-Automata#78]
I am currently farming Siegfried raid. I choose Chiron, Ishtar and Gil as my prefered support servants in autoskill. I set up my autoskill so I can use Chiron third skill and target himself when the script get him as my support. But Gil and Ishtar thirds skill aren't targetable so when they're in combat with my autoskill setup the script click a bit too low and it popup the servant info which break the rest of the autoskill setup (can't click on skills nor attack button).
If the click was I bit higher the servant info wouldn't popup even if I trigger a non-targetable skill in my   targetable skill setup.

To sum up:

I think the script click around here if I want to target Chiron with his targetable third skill : https://puu.sh/FCFU4/a7b34268b0.jpg

If I the script choose another of my prefered servant (Gil or Ishtar) when it tries trigger the third skill it also click in the abovementionned area which popup the servant info and break the rest of the command setup : https://puu.sh/FCFUg/d22e897619.jpg

If the click for targetable skills was around here : https://puu.sh/FCFTT/f55b80bbc8.jpg

it would still target if it's a targetable skill and wouldn't popup the servant info if it isn't a targetable skill.

Device Info (please fill atleast 'Device model'):

Device model: Honor 8X
Screen size: 2340 x 1080
Android Version: Android 8.1.0
RAM: 4 GB

**Comment by MathewSachin** [comment]
Thank you for the detailed and well-researched issue. I'd consider it both as a feature as well as bug fix.
I can already see this being very useful for the cases where I won't mind if either Waver or Merlin was selected as friend support.

I actually want to implement this right now, expect a build soon.

**Comment by MathewSachin** [comment]
This can cause enemy target change if the skill isn't targetable.
So, the user still has to use `t` before the next skill/NP if the enemy target matters.

**Comment by MathewSachin** [comment]
@Yandirin Can you test the apk on this page: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/88206159

It'll be in a zipped folder. I've made it click a bit higher for targeting servants.

**Comment by Yandirin** [comment]
Ah, indeed it changes the targets, I didn't thought of that. Maybe a workaround would be to add a click after the target choosing click (not the one I suggested but the original one) on this corner between battle menu and master skills https://puu.sh/FCH7h/fb432c1e4c.png

If it's a targetable skill, it would work normally. If it isn't, the servant popup would appear but be closed after that without causing problems.

**Comment by MathewSachin** [comment]
Adding another click is indeed possible, I'd make it click on the top-right corner of the screen.
We're already doing this when selecting enemy targets.
If you hold an enemy target, an enemy status info dialog pops up. So, after selecting an enemy target we click on top-right corner of the screen to close if it accidentally opened.

Timing the clicks right can be a problem... I'll give you a build to test in a while.

**Comment by MathewSachin** [comment]
@Yandirin  Here's the build doing what I wrote above: https://github.com/MathewSachin/Fate-Grand-Automata/actions/runs/88287590

Seems to be working perfectly for me. I'm working on a few more things right now so can't test extensively, but, it should work good enough. Let me know if there's any problem.

**Comment by Yandirin** [comment]
I tested your build with an almost impossible command like a1b1c1d2e2f2g3h3i3,0,0,0... and it works like a charm and that first turn wasn't very long compared to a simple abcdefghi command. Thanks!
