### ISSUE TITLE
Use file selectors instead of Strings for PreferredServants and PreferredCEs

### ISSUE THREAD

**Issue by reconman** [MathewSachin/Fate-Grand-Automata#8]
Right now you have to type in the file paths with the Android keyboard, typos are dangerous.

It would be a great feature if a list of files in the support folder are shown when you want to edit the Servant or CE values.

You should be able to select multiple Servants or CE files at the same time and there should be some way to mark CEs as MLB.

Btw, when I saw the speed of your support selection script, I was like this: 
<img src="https://i.kym-cdn.com/entries/icons/facebook/000/027/475/Screen_Shot_2018-10-25_at_11.02.15_AM.jpg" width="200" />

**Comment by MathewSachin** [comment]
I wanted to use a multiple selection dropdown here. But, then the problem was how to mark MLB.

This would be easy to do for a single file. Pick the file and use a checkbox to mark MLB. I'm not sure how I should create the UI for multiple CEs.

Oh, and was the support selection too fast. I was also thinking of slowing down the scrolling speed a bit.

**Comment by reconman** [comment]
Do you mean too fast for humans or for the script? Humans definitely can't keep up with tracking what the script does. I can't say much about the majority of your script yet, because I'm still manually farming the current event.

Regarding your MLB problem, I wasn't able to find any good solution for integrating the MLB part into the file selector, but you could just introduce an MLB checkbox. If the checkbox is checked, append `*` to all file names.

There may be some few users who want to have non-MLB CE1 and MLB CE2 at the same time, but the majority will only use 1 CE image at the same time.

Also you shouldn't forget cases where users want to reset the Servant and CE settings to `""`.

**Comment by MathewSachin** [comment]
I meant the scrolling was too fast for the game. It sometimes started scrolling even before list of servants was loaded.

I'll try making a custom UI for this.

Also, a case I was thinking about was having to specify filenames for all ascensions of a servant.
Merlin, for example, has 4 ascensions and a costume.
I was thinking of optionally allowing putting servant images into folders. If you select a folder, all images in that folder are used.

I'm thinking of the following folder structure.
```
Fate-Grand-Automata/
-- support/
-- -- servants/
-- -- -- Merlin/
-- -- -- -- merlin1.png
-- -- -- -- merlin2.png
-- -- -- -- merlin3.png
-- -- -- -- merlin4.png
-- -- -- -- merlin_c.png
-- -- -- Waver/
-- -- -- -- waver1.png
-- -- -- -- waver2.png
-- -- -- -- waver3.png
-- -- -- -- waver4.png
-- -- ce/
-- -- -- kscope.png
-- -- -- black_grail.png
-- -- friend/
-- -- -- (I honestly haven't tried this feature yet)
```

I think I should also include Waver and Merlin in the app. They are the most commonly used supports after all.
Also, considering adding Kaleidoscope, Black Grail and other general pool CEs.
I'd rather avoid putting event CEs in the app unless they are like Golden Sumo, Holy Night Supper, Aerial Drive, etc.

**Comment by reconman** [comment]
Your plan regarding folders sounds kinda good to me. Regarding whether to include images in your app, it's very intransparent right now on what's part of the app and what's not.

Is it possible to copy the default images into the support folder automatically? That way you don't have to deal with the logic of it being either built-in or from the support folder.

**Comment by MathewSachin** [comment]
I've almost implemented it as you suggested (in-progress PR #9).

![WhatsApp Image 2020-04-15 at 7 20 24 PM](https://user-images.githubusercontent.com/10654537/79345407-b2abc680-7f4e-11ea-91e6-f8f3c2a3c4e7.jpeg)

![WhatsApp Image 2020-04-15 at 7 20 31 PM](https://user-images.githubusercontent.com/10654537/79345395-ae7fa900-7f4e-11ea-8291-898b7b70c2f1.jpeg)

I don't think I can do better than this with Android's default picker. Adding something like search functionality to the picker will require me to rewrite the whole picker which I don't consider worth the effort.

As you said, I'm also farming the current event manually and it's too grindy.
I'll properly test this after the event before merging.

Currently, only `mona_lisa.png` and `chaldea_lunchtime.png` are included.
With only 2 images, the code is pretty manageable right now.
Regarding copying default images to support folder automatically, I'll have to take care of edge cases here and also make sure the copying is done only once. I'll give it a shot.

**Comment by MathewSachin** [comment]
How about having an `Extract Default Support Images` button in the app?
The user can extract the images if/when he wants.
I'll think including this in the Getting Started should be enough to let the user know.

**Comment by reconman** [comment]
I guess users could live with the button.

Is it possible to use a custom file picker like https://github.com/TutorialsAndroid/FilePicker?

**Comment by MathewSachin** [comment]
Actually, I'm using Android's Preference library. This makes saving preferences very easy without having to maintain a database myself. So, that's why I can't really use 3rd party options here which aren't compatible with that library. I technically can by writing a wrapper, but again, not worth the effort, I think.
We don't need a full-blown file picker anyway, the images will be in a specific folder, so I think the current picker should be sufficient.

**Comment by reconman** [comment]
> We don't need a full-blown file picker anyway, the images will be in a specific folder, so I think the current picker should be sufficient.

Okay, I got it. With the normal file pickers you can switch directories and we don't want that to be an option.

**Comment by MathewSachin** [comment]
I've implemented `Extract Default Support Images` option. I'll give you a build once this event is over and I've tested it.

Do people use the `Support Selection Mode = friend` option frequently?
Would it be worth making a picker for the friend images right now?

**Comment by reconman** [comment]
I have only seen one issue related to that where they would have been better off not using it. https://github.com/29988122/Fate-Grand-Order_Lua/issues/275

Most use `preferred`, and `first` comes after that, I think.
