### ISSUE TITLE
Screenshots/Clicks/Scroll using Root

### ISSUE THREAD

**Issue by MathewSachin** [MathewSachin/Fate-Grand-Automata#80]
We'll add support for taking screenshots and doing clicks and scrolls using root.
This will allow the app to run on Android 5 phones and emulators.

FGO JP should work with root by default.
You can use MagiskHide with FGO NA till the engine update arrives.

Don't expect immediate availability. We'd need some time to implement and test this.

And, please don't ask for daemon support, AFAIK that's AnkuLua specific thing. We don't want to spend time on implementing something like that since it doesn't work on Android 8+ anyway.

**Comment by potchy** [comment]
Did you rewrite all the .lua files from the original repo by hand?
This is amazing! :o

**Comment by MathewSachin** [comment]
Yup. Did it step by step over a few weeks

**Comment by reconman** [comment]
@potchy How did you find this project? Looked through old comments?

**Comment by potchy** [comment]
~~I'm a stalker~~
[from here](https://github.com/29988122/Fate-Grand-Order_Lua/pull/363)
 
I have absolutely zero experience with Xamarin/Android in general, but I'm very comfortable around C#, so I hope I can help somehow in the future. :grin:

**Comment by reconman** [comment]
That's what I thought. It's also the path that lead me here.

**Comment by MathewSachin** [comment]
Now, since FGO NA is getting the engine update in a month. We don't need the Clicks/Scroll using Root to make the app work on Nox Android 7 anymore! Just the Screenshots using Root which is already done should be enough.
White screen when launching the app on Nox (#106) will be fixed with the Kotlin port (#108).
