### ISSUE TITLE
Battle script doesn't work no taps/clicks

### ISSUE THREAD

**Issue by Claey** [MathewSachin/Fate-Grand-Automata#91]
I use android 7 on nox 6.5.0.3
I set up the auto skill and all and it doesn't work, no clicks.
Though somehow the lotto and friend gacha script work properly

**Comment by reconman** [comment]
See #80 

Nox doesn't allow us to take screenshots, it's always black. So Mathew is currently implementing screenshotting via root.

And because FGO NA doesn't run on Nox' Android 7, we are also implementing swiping and clicking using root.

**Comment by Claey** [comment]
I forgot to mention that I tried it on FGO NA but thanks for the confirmation, I was confused since I saw Mathew said something about testing it on nox with android 7 maybe I read it wrong.

**Comment by reconman** [comment]
Wait, you got FGO NA running on Nox with Android 7?

**Comment by Claey** [comment]
oh my bad then I didn't know that you need to enable root

**Comment by reconman** [comment]
I can't even get FGO NA to run on Nox Android 7, it just crashes when connecting to the server. (before the download)

**Comment by reconman** [comment]
Sad news, we only have it working on FGO JP right now, FGO NA would only work if either:

* We find a way to get MediaProjection to work on Nox
* We find a way to run FGO NA on Android 7 Nox with Root being enabled
* We create a C# application that only works as long as Nox is on the screen, which is much work and not really end user friendly.
