### ISSUE TITLE
Denying root permissions crashes the app

### ISSUE THREAD

**Issue by reconman** [MathewSachin/Fate-Grand-Automata#98]
Here are the steps to reproduce the issue on Nox:

1. Enable root mode
2. Start the Service
3. Deny the SU permission
4. Try stopping the Service

Then the app will crash.

**Comment by MathewSachin** [comment]
Currently, I can't find a good way to find if the user gave root permission unless something is run like when a screenshot is taken.
Will preventing the crash on stopping the service be enough?

Starting the script already gives an error. I'll also make that error more readable.

**Comment by reconman** [comment]
There is a way to detect root permission, that is running `id` after `su`, which should return `uid=0(root) gid=0(root) groups=0(root) context=<some string>`.

The play button shouldn't even be there if root permission was denied.

**Comment by MathewSachin** [comment]
This does seem to work. I'll put up a PR soon.
